"""Generate the explicit IF packet layout and TT-style IF datapath.

The schema keeps stall snapshots and IP payload fields identical. Hardware
replication is expressed as Verilog generate, not Python-unrolled registers.
"""
from pathlib import Path
from rtl_style import layout

ROOT = Path(__file__).resolve().parents[1]
P = []


def port(direction, names, width=1):
    for name in names.split():
        P.append((direction, width, name))


port('input', 'forever_cpuclk cpurst_b cp0_ifu_icache_en')
port('input', 'cp0_yy_priv_mode', 2)
port('input', 'region_ifdp_attr', 5)
port('input', 'ifctrl_ifdp_issue ifctrl_ifdp_hold ifctrl_ifdp_held ifctrl_ifdp_pipedown')
port('input', 'ifctrl_ifdp_issue_pc', 32)
port('input', 'ifctrl_ifdp_issue_way ifctrl_ifdp_issue_kind', 2)
port('input', 'lbuf_ifdp_source')
port('input', 'lbuf_ifdp_word_mask', 4)
port('input', 'icache_if_ifdp_inst_data0 icache_if_ifdp_inst_data1', 128)
port('input', 'icache_if_ifdp_precode0 icache_if_ifdp_precode1', 32)
port('input', 'icache_if_ifdp_tag_data0 icache_if_ifdp_tag_data1', 18)
port('input', 'icache_if_ifdp_fifo l1_refill_ifdp_acc_err')
port('input', 'l1_refill_ifdp_inst_data', 128)
port('input', 'l1_refill_ifdp_precode', 32)
port('input', 'btb_ifdp_vld')
port('input', 'btb_ifdp_pc', 32)
port('input', 'btb_ifdp_hit', 4)
port('input', 'btb_ifdp_target', 128)
port('input', 'btb_ifdp_way', 8)
port('input', 'l0_btb_ifdp_hit bp_recovery_stall')
port('input', 'l0_btb_ifdp_index', 4)
port('input', 'l0_btb_ifdp_slot l0_btb_ifdp_way', 2)
port('input', 'l0_btb_ifdp_type', 3)
port('input', 'l0_btb_ifdp_target', 32)
port('input', 'had_ifu_bkpta_en had_ifu_bkptb_en')
port('input', 'had_yy_xx_bkpta_base had_yy_xx_bkptb_base had_yy_xx_bkpta_mask had_yy_xx_bkptb_mask', 32)
port('input', 'sfp_ifdp_vld')
port('input', 'sfp_ifdp_pc', 32)
port('input', 'sfp_ifdp_no_spec', 4)
port('output', 'ifdp_ifctrl_fault ifdp_ifctrl_l0_vld')
port('output', 'ifdp_ifctrl_l0_target ifdp_l0_btb_pc ifdp_bht_pc', 32)
port('output', 'ifdp_ifctrl_l0_way', 2)

# Every item is registered atomically into IP and, on a stall, into a hold copy.
fields = [
    ('lbuf_on',1,'is_lbuf'),
    ('vpc',32,'if_pc'), ('attr',5,'if_attr'), ('priv_mode',2,'if_priv'),
    ('way_pred',2,'if_way'), ('refill_on',1,'is_refill'),
    ('cache_bypass',1,'is_bypass'), ('fifo',1,'raw_fifo'),
    ('fault',1,'if_fault'), ('cause',4,'if_cause'), ('word_mask',4,'word_mask'),
    ('bkpta',4,'breakpoint_hit[0] & word_mask'), ('bkptb',4,'breakpoint_hit[1] & word_mask'),
    ('inst_data0',128,'way_data[0]'), ('inst_data1',128,'way_data[1]'),
    ('precode0',32,'way_precode[0]'), ('precode1',32,'way_precode[1]'),
    ('tag_match0',3,'tag_match[0]'), ('tag_match1',3,'tag_match[1]'),
    ('btb_vld',1,'btb_match'), ('btb_hit',4,'btb_ifdp_hit & {4{btb_match}}'),
    ('btb_target',128,'btb_ifdp_target & {128{btb_match}}'),
    ('btb_way',8,'btb_ifdp_way & {8{btb_match}}'),
    ('l0_hit',1,'l0_eligible'), ('l0_index',4,'l0_btb_ifdp_index'),
    ('l0_slot',2,'l0_btb_ifdp_slot'), ('l0_type',3,'l0_btb_ifdp_type'),
    ('l0_target',32,'l0_btb_ifdp_target'), ('l0_way',2,'l0_btb_ifdp_way'),
    ('no_spec',4,'sfp_mask & word_mask'),
]
for n,w,_ in fields:
    port('output', 'ifdp_ipdp_'+n, w)
port('output', 'ifdp_ipdp_seq_pc', 32)
port('output', 'ifdp_ipdp_word_pc', 128)
port('output', 'ifdp_ipdp_l0_entry_mask', 16)
port('output', 'ifdp_ipdp_l0_btb_target_match', 4)

header = '''/*Copyright 2019-2021 T-Head Semiconductor Co., Ltd.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// RV32I adaptation of ct_ifu_ifdp.v; generated by scripts/build_ifdp.py.
// IF compares Tag slices; IP combines them and decides hit/miss/Way replay.
// All full PCs are physical byte addresses. Word0 is data[31:0].
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
module rv32_ifu_ifdp (
'''
header += ',\n'.join(f'  {d} wire '+(f'[{w-1}:0] ' if w>1 else '')+n for d,w,n in P)+'\n);\n'
total = sum(w for _,w,_ in fields)
offset = 0
field_offsets = {}
for n,w,_ in reversed(fields):
    field_offsets[n] = offset
    offset += w
s = header+f'  localparam PACKET_WIDTH = {total};\n'
for n,w,_ in fields:
    s += f'  localparam P_{n.upper()} = {field_offsets[n]};\n'
s += '''
  localparam [1:0] CACHE = 2'd0, FAULT = 2'd1, BYPASS = 2'd2, REFILL = 2'd3;
  localparam META_WIDTH = 218;
  genvar capture;
  genvar way;
  genvar part;
  genvar slot;
  genvar breakpoint;
  genvar entry;
  reg [META_WIDTH-1:0] meta_q;
  wire [META_WIDTH-1:0] meta_nxt;
  wire meta_en;
  reg [PACKET_WIDTH-1:0] packet_q [0:1];
  wire [PACKET_WIDTH-1:0] packet_nxt [0:1];
  wire [1:0] packet_en;
  wire [PACKET_WIDTH-1:0] response_packet;
  wire [PACKET_WIDTH-1:0] selected_packet;
  wire [31:0] if_pc;
  wire is_lbuf;
  wire [3:0] lbuf_mask;
  wire [4:0] if_attr;
  wire [1:0] if_priv;
  wire [1:0] if_way;
  wire [1:0] if_kind;
  wire if_cache_en;
  wire [127:0] forward_data;
  wire [31:0] forward_precode;
  wire forward_error;
  wire [3:0] breakpoint_hit [0:1];
  wire [3:0] breakpoint_issue_hit [0:1];
  wire [63:0] breakpoint_base;
  wire [63:0] breakpoint_mask;
  wire [1:0] breakpoint_enable;
  wire is_cache;
  wire is_refill;
  wire is_bypass;
  wire if_fault;
  wire [3:0] if_cause;
  wire [3:0] word_mask;
  wire raw_fifo;
  wire btb_match;
  wire l0_eligible;
  wire [3:0] sfp_mask;
  wire [127:0] array_data [0:1];
  wire [31:0] array_precode [0:1];
  wire [17:0] array_tag [0:1];
  wire [127:0] way_data [0:1];
  wire [31:0] way_precode [0:1];
  wire [2:0] tag_match [0:1];

  //----------------------------------------------------------------------------
  // Metadata belongs to the granted request, never to a later live PC bus.
  //----------------------------------------------------------------------------
  assign meta_en = ifctrl_ifdp_issue;
  assign meta_nxt = {lbuf_ifdp_source,lbuf_ifdp_word_mask,ifctrl_ifdp_issue_pc, region_ifdp_attr, cp0_yy_priv_mode,
                     ifctrl_ifdp_issue_way, ifctrl_ifdp_issue_kind, cp0_ifu_icache_en,
                     l1_refill_ifdp_inst_data, l1_refill_ifdp_precode, l1_refill_ifdp_acc_err,
                     breakpoint_issue_hit[1], breakpoint_issue_hit[0]};
  assign {is_lbuf,lbuf_mask,if_pc, if_attr, if_priv, if_way, if_kind, if_cache_en,
          forward_data, forward_precode, forward_error,
          breakpoint_hit[1], breakpoint_hit[0]} = meta_q;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_meta
    if (!cpurst_b) begin
      meta_q <= {META_WIDTH{1'b0}};
    end else if (meta_en) begin
      meta_q <= meta_nxt;
    end
  end

  assign breakpoint_base = {had_yy_xx_bkptb_base, had_yy_xx_bkpta_base};
  assign breakpoint_mask = {had_yy_xx_bkptb_mask, had_yy_xx_bkpta_mask};
  assign breakpoint_enable = {had_ifu_bkptb_en, had_ifu_bkpta_en};
  generate
    for (breakpoint = 0; breakpoint < 2; breakpoint = breakpoint + 1) begin : g_breakpoint
      for (slot = 0; slot < 4; slot = slot + 1) begin : g_slot
        localparam [1:0] SLOT = slot;
        wire [31:0] word_pc;
        assign word_pc = {ifctrl_ifdp_issue_pc[31:4], SLOT, 2'b00};
        // Excel mask bit=1 means ignore this bit.
        assign breakpoint_issue_hit[breakpoint][slot] = breakpoint_enable[breakpoint] &&
          ((word_pc & ~breakpoint_mask[breakpoint*32+:32]) ==
           (breakpoint_base[breakpoint*32+:32] & ~breakpoint_mask[breakpoint*32+:32]));
      end
    end
  endgenerate

  //----------------------------------------------------------------------------
  // Raw IF data selection and partial physical Tag comparisons.
  //----------------------------------------------------------------------------
  assign is_cache = (if_kind == CACHE);
  assign is_refill = (if_kind == REFILL);
  assign is_bypass = (if_kind == BYPASS);
  assign if_fault = (if_kind == FAULT) || (is_refill && forward_error);
  assign if_cause = (|if_pc[1:0]) ? 4'd0 : 4'd1;
  assign array_data[0] = icache_if_ifdp_inst_data0;
  assign array_data[1] = icache_if_ifdp_inst_data1;
  assign array_precode[0] = icache_if_ifdp_precode0;
  assign array_precode[1] = icache_if_ifdp_precode1;
  assign array_tag[0] = icache_if_ifdp_tag_data0;
  assign array_tag[1] = icache_if_ifdp_tag_data1;
  assign raw_fifo = is_cache && icache_if_ifdp_fifo;
  generate
    for (way = 0; way < 2; way = way + 1) begin : g_way
      assign way_data[way] = if_fault ? 128'b0 :
                             is_refill ? ((way == 0) ? forward_data : 128'b0) :
                             array_data[way] & {128{is_cache && if_way[way]}};
      assign way_precode[way] = if_fault ? 32'b0 :
                                is_refill ? ((way == 0) ? forward_precode : 32'b0) :
                                array_precode[way] & {32{is_cache && if_way[way]}};
      for (part = 0; part < 3; part = part + 1) begin : g_tag_part
        wire equal_part;
        if (part == 2) begin : g_valid_and_high
          assign equal_part = array_tag[way][17:16] == {1'b1, if_pc[31]};
        end else begin : g_low
          assign equal_part = array_tag[way][part*8+:8] == if_pc[15+part*8+:8];
        end
        assign tag_match[way][part] = !if_fault &&
          ((is_refill && (way == 0)) || (is_cache && if_cache_en && equal_part));
      end
    end
    for (slot = 0; slot < 4; slot = slot + 1) begin : g_word
      localparam [1:0] SLOT = slot;
      assign word_mask[slot] = if_fault ? (SLOT == if_pc[3:2]) :
        (SLOT >= if_pc[3:2]) && (!is_lbuf || lbuf_mask[slot]);
      assign ifdp_ipdp_word_pc[slot*32+:32] = {ifdp_ipdp_vpc[31:4], SLOT, 2'b00};
      assign ifdp_ipdp_l0_btb_target_match[slot] = ifdp_ipdp_btb_vld && ifdp_ipdp_btb_hit[slot] &&
        ifdp_ipdp_l0_hit && (ifdp_ipdp_btb_target[slot*32+:32] == ifdp_ipdp_l0_target);
    end
    for (entry = 0; entry < 16; entry = entry + 1) begin : g_l0_entry
      localparam [3:0] ENTRY = entry;
      assign ifdp_ipdp_l0_entry_mask[entry] = ifdp_ipdp_l0_hit && (ifdp_ipdp_l0_index == ENTRY);
    end
  endgenerate

  assign btb_match = btb_ifdp_vld && (btb_ifdp_pc == if_pc) && !if_fault && !is_bypass;
  assign l0_eligible = l0_btb_ifdp_hit && !if_fault && !is_bypass &&
                       (l0_btb_ifdp_slot >= if_pc[3:2]) && !(|l0_btb_ifdp_target[1:0]);
  assign sfp_mask = (sfp_ifdp_vld && (sfp_ifdp_pc == if_pc) && !if_fault) ? sfp_ifdp_no_spec : 4'b0;
'''
s += '  assign response_packet = {\n    '+',\n    '.join(expr for _,_,expr in fields)+'\n  };\n'
s += '''
  // First stalled edge saves the complete response before another array owner
  // can overwrite SRAM Q. Subsequent stalls never re-sample changing predictors.
  assign selected_packet = ifctrl_ifdp_held ? packet_q[0] : response_packet;
  assign packet_en = {ifctrl_ifdp_pipedown, ifctrl_ifdp_hold};
  assign packet_nxt[0] = response_packet;
  assign packet_nxt[1] = selected_packet;
  generate
    for (capture = 0; capture < 2; capture = capture + 1) begin : g_capture
      always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_packet
        if (!cpurst_b) begin
          packet_q[capture] <= {PACKET_WIDTH{1'b0}};
        end else if (packet_en[capture]) begin
          packet_q[capture] <= packet_nxt[capture];
        end
      end
    end
  endgenerate
  assign ifdp_ifctrl_fault = selected_packet[P_FAULT];
  // C910 defers speculative RAS/IND repair until the recovery retirement point.
  // A held indirect L0 hint must also be suppressed while that state is unsafe.
  assign ifdp_ifctrl_l0_vld = selected_packet[P_L0_HIT] && !selected_packet[P_FAULT] &&
    !((selected_packet[P_L0_TYPE+:3] == 3'd3) && bp_recovery_stall);
  assign ifdp_ifctrl_l0_target = selected_packet[P_L0_TARGET+:32];
  assign ifdp_ifctrl_l0_way = selected_packet[P_L0_WAY+:2];
  assign ifdp_l0_btb_pc = if_pc;
  assign ifdp_bht_pc = if_pc;
'''
for n,w,_ in fields:
    s += f'  assign ifdp_ipdp_{n} = packet_q[1][P_{n.upper()}+:{w}];\n'
s += "  assign ifdp_ipdp_seq_pc = {ifdp_ipdp_vpc[31:4] + 28'd1, 4'b0};\nendmodule\n"
(ROOT/'rtl/rv32_ifu_ifdp.v').write_text(layout(s))
print('Generated rv32_ifu_ifdp: '+str(total)+'-bit atomic IF/IP packet')
