"""C910-style initialization/maintenance, debug entry and SF/BAR support."""
from build_memory import ROOT,emit as memory_emit,regs,PRODUCTS
begin=len(PRODUCTS)

def emit(name,spec,body):
    memory_emit(name,spec,body)
    path=ROOT/'rtl'/f'rv32_ifu_{name}.v'
    path.write_text(path.read_text().replace(
        'RV32I adaptation of C910 refill/IPB responsibilities; no Cache lookup FSM.',
        'RV32I adaptation of C910 support-stage duties. See doc/pipeline_zh.md.').replace(
        'Generated by scripts/build_memory.py.', 'Generated by scripts/build_support.py.'))

emit('maintenance','''
input 1 forever_cpuclk cpurst_b
input 1 recovery
input 32 recovery_pc
input 1 memory_idle refill_array_req
input 1 bp_init_done bp_maint_ready bp_maint_done
output 1 bp_maint_vld
output 5 bp_maint_mask
input 1 cp0_ifu_maint_vld
output 1 ifu_cp0_maint_ready
input 2 cp0_ifu_maint_op
input 32 cp0_ifu_maint_pa cp0_ifu_maint_resume_pc
input 8 cp0_ifu_maint_pred_mask
output 1 ifu_cp0_maint_done
input 1 lsu_ifu_icache_inv_vld lsu_ifu_icache_inv_all
input 32 lsu_ifu_icache_inv_pa lsu_ifu_icache_inv_resume_pc
output 1 ifu_lsu_icache_inv_ready ifu_lsu_icache_inv_done
output 1 init_done busy invalidate flush resume
output 32 resume_pc
output 1 clear_sfp
output 1 maintenance_array_req
input 1 ifctrl_maintenance_grant
output 32 ifctrl_icache_if_index
output 1 ifctrl_icache_if_inv_fifo ifctrl_icache_if_inv_on ifctrl_icache_if_reset_req ifctrl_icache_if_tag_req
output 3 ifctrl_icache_if_tag_wen
output 1 ifctrl_icache_if_read_req_data0 ifctrl_icache_if_read_req_data1 ifctrl_icache_if_read_req_tag
output 32 ifctrl_icache_if_read_req_index
input 128 icache_if_ifctrl_inst_data0 icache_if_ifctrl_inst_data1
input 18 icache_if_ifctrl_tag_data0 icache_if_ifctrl_tag_data1
input 32 icache_if_ifdp_precode0 icache_if_ifdp_precode1
input 1 icache_if_ifdp_fifo
input 1 cp0_ifu_icache_read_req
output 1 ifu_cp0_icache_read_ready
input 11 cp0_ifu_icache_read_index
input 1 cp0_ifu_icache_read_way
input 2 cp0_ifu_icache_read_kind
input 1 cp0_ifu_icache_read_data_ready
output 1 ifu_cp0_icache_read_data_vld
output 128 ifu_cp0_icache_read_data
output 1 software_idle
''', '''
  localparam [3:0] INIT=0,BOOT=1,IDLE=2,DRAIN=3,BP_REQ=4,BP_WAIT=5,
    ALL=6,LINE_READ=7,LINE_WRITE=8,DONE=9,SW_READ=10,SW_CAPTURE=11,SW_RESPONSE=12;
  wire cp0_fire,lsu_fire,command,sw_fire,grant,tag_operation,all_operation;
  wire [1:0] line_match;
  wire [17:0] sw_tag;
  wire [127:0] sw_data,sw_payload;
  wire [31:0] sw_precode;
  wire [3:0] after_bp;
  assign ifu_lsu_icache_inv_ready=state_q==IDLE && !recovery;
  assign ifu_cp0_maint_ready=state_q==IDLE && !recovery && !lsu_ifu_icache_inv_vld;
  assign lsu_fire=lsu_ifu_icache_inv_vld && ifu_lsu_icache_inv_ready;
  assign cp0_fire=cp0_ifu_maint_vld && ifu_cp0_maint_ready;
  assign command=lsu_fire || cp0_fire;
  assign flush=command;
  assign busy=state_q< IDLE || (state_q>=DRAIN && state_q<=DONE);
  assign invalidate=busy || command;
  assign init_done=init_q;
  assign resume=state_q==DONE && !recovery;
  assign resume_pc=resume_q;
  assign ifu_cp0_maint_done=state_q==DONE && !source_q;
  assign ifu_lsu_icache_inv_done=state_q==DONE && source_q;
  assign clear_sfp=command && !lsu_fire &&
    (cp0_ifu_maint_op==0 || (cp0_ifu_maint_op==3 && cp0_ifu_maint_pred_mask[6]));
  assign bp_maint_vld=state_q==BP_REQ;
  assign bp_maint_mask=pred_q;
  assign after_bp=op_q==3 ? DONE : op_q==2 ? LINE_READ : ALL;
  assign all_operation=state_q==INIT || state_q==ALL;
  assign tag_operation=all_operation || state_q==LINE_READ || state_q==LINE_WRITE;
  assign maintenance_array_req=tag_operation || (state_q==SW_READ && !refill_array_req);
  assign grant=maintenance_array_req && ifctrl_maintenance_grant;
  assign ifctrl_icache_if_index=all_operation ? {17'b0,index_q,6'b0} : pa_q;
  assign ifctrl_icache_if_inv_fifo=1'b0;
  assign ifctrl_icache_if_reset_req=1'b0;
  assign ifctrl_icache_if_inv_on=all_operation || state_q==LINE_WRITE;
  assign ifctrl_icache_if_tag_req=tag_operation;
  assign line_match={icache_if_ifctrl_tag_data1=={1'b1,pa_q[31:15]},
                     icache_if_ifctrl_tag_data0=={1'b1,pa_q[31:15]}};
  assign ifctrl_icache_if_tag_wen=state_q==LINE_READ ? 3'b111 :
    state_q==LINE_WRITE ? {1'b1,~line_match} : 3'b000;
  assign ifu_cp0_icache_read_ready=state_q==IDLE && !recovery &&
    !lsu_ifu_icache_inv_vld && !cp0_ifu_maint_vld && !refill_array_req;
  assign sw_fire=cp0_ifu_icache_read_req && ifu_cp0_icache_read_ready;
  assign ifctrl_icache_if_read_req_index={17'b0,sw_desc_q[13:3],4'b0};
  assign ifctrl_icache_if_read_req_data0=state_q==SW_READ && !sw_desc_q[2] && sw_desc_q[1:0]!=1;
  assign ifctrl_icache_if_read_req_data1=state_q==SW_READ && sw_desc_q[2] && sw_desc_q[1:0]!=1;
  assign ifctrl_icache_if_read_req_tag=state_q==SW_READ && sw_desc_q[1:0]==1;
  assign sw_data=sw_desc_q[2] ? icache_if_ifctrl_inst_data1 : icache_if_ifctrl_inst_data0;
  assign sw_tag=sw_desc_q[2] ? icache_if_ifctrl_tag_data1 : icache_if_ifctrl_tag_data0;
  assign sw_precode=sw_desc_q[2] ? icache_if_ifdp_precode1 : icache_if_ifdp_precode0;
  assign sw_payload=sw_desc_q[1:0]==0 ? sw_data : sw_desc_q[1:0]==1 ?
    {109'b0,icache_if_ifdp_fifo,sw_tag} : sw_desc_q[1:0]==2 ? {96'b0,sw_precode} : 128'b0;
  assign ifu_cp0_icache_read_data_vld=state_q==SW_RESPONSE;
  assign ifu_cp0_icache_read_data=sw_response_q;
  assign software_idle=state_q<SW_READ;
''' + regs([
 ('state',4,'INIT',"1'b1",'''state_q==INIT ? ((grant && index_q==511) ? BOOT : INIT) :
  state_q==BOOT ? (bp_init_done ? IDLE : BOOT) : command ? DRAIN :
  state_q==DRAIN ? (memory_idle ? BP_REQ : DRAIN) :
  state_q==BP_REQ ? (bp_maint_ready ? BP_WAIT : BP_REQ) :
  state_q==BP_WAIT ? (bp_maint_done ? after_bp : BP_WAIT) :
  state_q==ALL ? ((grant && index_q==511) ? DONE : ALL) :
  state_q==LINE_READ ? (grant ? LINE_WRITE : LINE_READ) :
  state_q==LINE_WRITE ? (grant ? DONE : LINE_WRITE) : state_q==DONE ? IDLE :
  sw_fire ? SW_READ : state_q==SW_READ ? (grant ? SW_CAPTURE : SW_READ) :
  state_q==SW_CAPTURE ? SW_RESPONSE :
  (state_q==SW_RESPONSE && cp0_ifu_icache_read_data_ready) ? IDLE : state_q'''),
 ('init',1,"1'b0",'state_q==BOOT && bp_init_done',"1'b1"),
 ('index',9,"9'b0",'command || (all_operation && grant)',"command ? 9'b0 : index_q+9'd1"),
 ('source',1,"1'b0",'command','lsu_fire'),
 ('op',2,"2'b0",'command',"lsu_fire ? (lsu_ifu_icache_inv_all ? 2'd1 : 2'd2) : cp0_ifu_maint_op"),
 ('pa',32,"32'b0",'command','lsu_fire ? lsu_ifu_icache_inv_pa : cp0_ifu_maint_pa'),
 ('resume',32,"32'b0",'command || (busy && recovery)',
  'recovery ? recovery_pc : lsu_fire ? lsu_ifu_icache_inv_resume_pc : cp0_ifu_maint_resume_pc'),
 ('pred',5,"5'b0",'command',"lsu_fire ? 5'b0 : cp0_ifu_maint_op==0 ? 5'b11111 : cp0_ifu_maint_op==3 ? cp0_ifu_maint_pred_mask[4:0] : 5'b0"),
 ('sw_desc',14,"14'b0",'sw_fire','{cp0_ifu_icache_read_index,cp0_ifu_icache_read_way,cp0_ifu_icache_read_kind}'),
 ('sw_response',128,"128'b0",'state_q==SW_CAPTURE','sw_payload'),
]))

emit('vector','''
input 1 forever_cpuclk cpurst_b init_done
input 32 cp0_ifu_rvbr
output 1 vector_pcgen_reset_on vector_pcgen_pcload
output 32 vector_pcgen_pc
''','''
  assign vector_pcgen_reset_on=!loaded_q;
  assign vector_pcgen_pcload=init_done && !loaded_q;
  assign vector_pcgen_pc=pc_q;
'''+regs([
 ('captured',1,"1'b0","!captured_q","1'b1"),
 ('pc',32,"32'b0","!captured_q",'cp0_ifu_rvbr'),
 ('loaded',1,"1'b0",'vector_pcgen_pcload',"1'b1"),
]))

emit('debug','''
input 1 forever_cpuclk cpurst_b rtu_ifu_dbgon quiescent global_cancel
input 1 had_ifu_pcload had_ifu_ir_vld
input 32 had_ifu_pc had_ifu_ir
output 1 ifu_had_cmd_ready debug_pcgen_pcload inject_valid inject_query inject_pipedown debug_busy debug_restore
output 32 debug_pcgen_pc inject_pc inject_inst
input 1 inject_accept
''','''
  wire command,inject;
  assign ifu_had_cmd_ready=rtu_ifu_dbgon && quiescent && !valid_q && !global_cancel;
  assign command=ifu_had_cmd_ready && (had_ifu_pcload ^ had_ifu_ir_vld);
  assign inject=command && had_ifu_ir_vld;
  assign debug_pcgen_pcload=command && had_ifu_pcload;
  assign debug_restore=(rtu_ifu_dbgon && !debug_on_q) || debug_pcgen_pcload;
  assign debug_pcgen_pc=had_ifu_pc;
  assign inject_valid=valid_q && delay_q==2 && !global_cancel;
  assign inject_query=valid_q && delay_q==0 && !global_cancel;
  assign inject_pipedown=valid_q && delay_q==1 && !global_cancel;
  assign debug_busy=valid_q;
  assign inject_pc=payload_q[63:32];
  assign inject_inst=payload_q[31:0];
'''+regs([
 ('debug_on',1,"1'b0","1'b1",'rtu_ifu_dbgon'),
 ('valid',1,"1'b0",'inject || inject_accept || global_cancel', 'inject && !global_cancel'),
 ('payload',64,"64'b0",'inject','{had_ifu_pc,had_ifu_ir}'),
 ('delay',2,"2'b0",'inject || (valid_q && delay_q!=2)',"inject ? 2'b0 : delay_q+2'd1"),
]))

emit('sfp','''
input 1 forever_cpuclk cpurst_b enable invalidate cancel lookup_accept
input 32 lookup_pc
input 4 lookup_mask
output 4 no_spec
input 3 retire_valid retire_load retire_store retire_hit retire_miss retire_mispred
input 96 retire_pc
''','''
  // C910 SF/BAR pair: store feedback identifies SF, subsequent load feedback
  // identifies its barrier. Oldest retirement feedback wins the single port.
  reg [66:0] entry_q [0:11];
  wire [66:0] entry_nxt [0:11];
  wire [11:0] entry_en,hit,selected;
  wire [2:0] event_valid,choose;
  wire [31:0] event_pc;
  wire event_store,event_miss,event_hit,event_mispred,feedback;
  wire [31:0] key;
  wire allocate;
  wire [4:0] read_bar;
  wire [3:0] sf_hit,bar_hit;
  genvar lane,entry;
  assign event_valid=retire_valid & (retire_load | retire_store) &
    (retire_hit | retire_miss | retire_mispred);
  assign choose={event_valid[2] && !(|event_valid[1:0]),
                 event_valid[1] && !event_valid[0],event_valid[0]};
  assign event_pc=({32{choose[0]}} & retire_pc[31:0]) |
    ({32{choose[1]}} & retire_pc[63:32]) | ({32{choose[2]}} & retire_pc[95:64]);
  assign event_store=|(choose & retire_store);
  assign event_miss=|(choose & retire_miss);
  assign event_hit=|(choose & retire_hit);
  assign event_mispred=|(choose & retire_mispred);
  assign feedback=enable && (|choose) && !invalidate;
  assign key=event_store ? event_pc : last_store_q;
  assign allocate=feedback && event_store && event_miss && !(|hit);
  assign read_bar[0]=mode_q;
  generate
    for(entry=0;entry<12;entry=entry+1) begin : g_entry
      wire [1:0] count,increment,decrement,updated;
      assign hit[entry]=entry_q[entry][66] && entry_q[entry][31:0]==key;
      assign selected[entry]=feedback && (hit[entry] || (allocate && pointer_q==entry));
      assign count=entry_q[entry][65:64];
      assign increment=count==3 ? 2'd3 : count+2'd1;
      assign decrement=count==0 ? 2'd0 : count-2'd1;
      assign updated=event_store ? (event_mispred ? 2'd0 : event_miss ? 2'd1 : count) :
        event_miss ? 2'd1 : event_hit ? increment : decrement;
      assign entry_en[entry]=invalidate || selected[entry];
      assign entry_nxt[entry]=invalidate ? 67'b0 :
        {1'b1,updated,(event_store ? (allocate ? 32'b0 : entry_q[entry][63:32]) : event_pc),key};
      always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_entry
        if(!cpurst_b) entry_q[entry]<=67'b0;
        else if(entry_en[entry]) entry_q[entry]<=entry_nxt[entry];
      end
    end
    for(lane=0;lane<4;lane=lane+1) begin : g_lookup
      localparam [1:0] LANE=lane;
      wire [11:0] sf_matches,bar_matches;
      wire [31:0] pc;
      assign pc={lookup_pc[31:4],LANE,2'b0};
      for(entry=0;entry<12;entry=entry+1) begin : g_compare
        assign sf_matches[entry]=entry_q[entry][66] && (|entry_q[entry][65:64]) && entry_q[entry][31:0]==pc;
        assign bar_matches[entry]=entry_q[entry][66] && (|entry_q[entry][65:64]) && entry_q[entry][63:32]==pc;
      end
      assign sf_hit[lane]=lookup_mask[lane] && (|sf_matches);
      assign bar_hit[lane]=lookup_mask[lane] && (|bar_matches);
      assign no_spec[lane]=enable && !invalidate && (sf_hit[lane] || (read_bar[lane] && bar_hit[lane]));
      assign read_bar[lane+1]=sf_hit[lane] || (read_bar[lane] && !bar_hit[lane]);
    end
  endgenerate
'''+regs([
 ('pointer',4,"4'b0",'invalidate || allocate',"invalidate ? 4'b0 : pointer_q==11 ? 4'b0 : pointer_q+4'd1"),
 ('last_store',32,"32'b0",'invalidate || (feedback && event_store)',"invalidate ? 32'b0 : event_pc"),
 ('mode',1,"1'b0",'invalidate || cancel || lookup_accept','!invalidate && !cancel && read_bar[4]'),
]))

(ROOT/'rtl/support_files.f').write_text('\n'.join(PRODUCTS[begin:])+'\n')
print('Generated',len(PRODUCTS)-begin,'support modules')
