"""RV32 word-stage adaptation of C910 IP/IB/IBUF/PCFIFO/ADDRGEN.

Only layout/port boilerplate is generated in Python. Repeated hardware is
expressed using Verilog generate; all next-state logic uses assign.
"""
from pathlib import Path
from rtl_style import layout, public_ports

ROOT = Path(__file__).resolve().parents[1]
PRODUCTS = []


def emit(name, ports, body, params=''):
    header = '''// SPDX-License-Identifier: Apache-2.0
// RV32I word-stage adaptation of the corresponding C910 IFU stage duties.
// Generated by scripts/build_pipeline.py. See doc/pipeline_zh.md.
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
'''
    s = header + 'module rv32_ifu_' + name + params + ' (\n'
    s += ',\n'.join(f'  {d} wire '+(f'[{w-1}:0] ' if w > 1 else '')+n
                    for d,w,n in ports) + '\n);\n' + body + '\nendmodule\n'
    (ROOT/'rtl'/f'rv32_ifu_{name}.v').write_text(layout(s))
    PRODUCTS.append('rtl/rv32_ifu_'+name+'.v')


def ports(spec):
    return [(d,int(w),n) for line in spec.strip().splitlines()
            for d,w,names in [line.split(maxsplit=2)] for n in names.split()]


emit('ibuf', ports('''
input 1 forever_cpuclk cpurst_b flush
input 3 in_count
input 512 in_packet
output 1 in_ready
input 2 idu_ifu_accept_num
output 2 out_count
output 384 out_packet
output 6 occupancy
output 1 empty
'''), '''
  // Ring entries contain complete, already allocated instruction packets.
  // Admission uses only OLD queue pop, so candidate valid cannot depend on
  // accept when IB is visible in an output lane (old count is then < 3).
  reg [127:0] entry_q [0:31];
  wire [127:0] entry_nxt [0:31];
  wire [31:0] entry_en;
  reg [4:0] head_q, tail_q;
  wire [4:0] head_nxt, tail_nxt;
  reg [5:0] count_q;
  wire [5:0] count_nxt;
  wire pointer_en;
  wire [2:0] accepted, pop_count, bypass_count, push_count, admitted;
  wire [6:0] available_count;
  genvar entry, lane;
  assign occupancy = count_q;
  assign empty = count_q == 0;
  assign pop_count = flush ? 3'd0 :
    (({4'b0,idu_ifu_accept_num} < count_q) ? {1'b0,idu_ifu_accept_num} : count_q[2:0]);
  assign in_ready = !flush && (in_count <= 4) &&
    ({1'b0,count_q} + {4'b0,in_count} <= 7'd32 + {4'b0,pop_count});
  assign admitted = in_ready ? in_count : 3'd0;
  assign available_count = {1'b0,count_q} + {4'b0,admitted};
  assign out_count = flush ? 2'd0 : available_count >= 3 ? 2'd3 : available_count[1:0];
  assign accepted = flush ? 3'd0 : {1'b0,idu_ifu_accept_num};
  assign bypass_count = accepted - pop_count;
  assign push_count = admitted - bypass_count;
  assign pointer_en = flush || (|pop_count) || (|push_count);
  assign head_nxt = flush ? 5'd0 : head_q + {2'b0,pop_count};
  assign tail_nxt = flush ? 5'd0 : tail_q + {2'b0,push_count};
  assign count_nxt = flush ? 6'd0 : count_q - {3'b0,pop_count} + {3'b0,push_count};
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_head
    if (!cpurst_b) head_q <= 5'd0;
    else if (pointer_en) head_q <= head_nxt;
  end
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_tail
    if (!cpurst_b) tail_q <= 5'd0;
    else if (pointer_en) tail_q <= tail_nxt;
  end
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_count
    if (!cpurst_b) count_q <= 6'd0;
    else if (pointer_en) count_q <= count_nxt;
  end
  generate
    for (entry=0; entry<32; entry=entry+1) begin : g_entry
      localparam [4:0] INDEX = entry;
      wire [4:0] distance;
      wire [2:0] source;
      assign distance = INDEX - tail_q;
      assign source = distance[2:0] + bypass_count;
      assign entry_en[entry] = !flush && ({1'b0,distance} < {3'b0,push_count});
      assign entry_nxt[entry] = in_packet[{source,7'b0}+:128];
      always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_entry
        if (!cpurst_b) entry_q[entry] <= 128'b0;
        else if (entry_en[entry]) entry_q[entry] <= entry_nxt[entry];
      end
    end
    for (lane=0; lane<3; lane=lane+1) begin : g_lane
      localparam [5:0] LANE = lane;
      wire [4:0] index;
      wire [5:0] source;
      assign index = head_q + LANE[4:0];
      assign source = LANE - count_q;
      assign out_packet[lane*128+:128] = (LANE >= {4'b0,out_count}) ? 128'b0 :
        (LANE < count_q) ? entry_q[index] : in_packet[{source,7'b0}+:128];
    end
  endgenerate
''')

# 192-bit internal lane: IDU[127:0], static_target[159:128], chk_idx[184:160],
# dst[185], unknown[186], RAS push/pop/usable[189:187], BTB used[190].
emit('pcfifo_if', ports('''
input 1 flush accept
input 3 candidate_count
input 768 candidate_packet
input 2 iu_ifu_pcfifo_credit
input 13 iu_ifu_pcfifo_alloc0_token iu_ifu_pcfifo_alloc1_token
output 3 allowed_count
output 512 instruction_packet
output 2 create_en
output 64 create_pc create_target create_npc
output 6 create_type
output 2 create_dst create_pred create_unknown
output 50 create_chk
output 1 credit_stall
'''), '''
  wire [2:0] pc_count [0:4];
  wire [3:0] allowed;
  wire [25:0] tokens;
  genvar lane, record, bit_index;
  assign tokens = {iu_ifu_pcfifo_alloc1_token,iu_ifu_pcfifo_alloc0_token};
  assign pc_count[0] = 3'd0;
  assign allowed_count = {2'b0,allowed[0]}+{2'b0,allowed[1]}+
                         {2'b0,allowed[2]}+{2'b0,allowed[3]};
  assign credit_stall = !flush && allowed_count < candidate_count;
  generate
    for (lane=0;lane<4;lane=lane+1) begin : g_lane
      localparam [2:0] LANE=lane;
      wire [191:0] packet;
      wire [12:0] token;
      assign packet=candidate_packet[lane*192+:192];
      assign pc_count[lane+1]=pc_count[lane]+{2'b0,(LANE<candidate_count && packet[105])};
      assign allowed[lane]=!flush && LANE<candidate_count && pc_count[lane+1]<=(packet[191] ? 3'd1 : 3'd2) &&
        pc_count[lane+1]<={1'b0,iu_ifu_pcfifo_credit};
      assign token=packet[105] ? tokens[({29'b0,pc_count[lane]}*32'd13)+:13] : 13'b0;
      assign instruction_packet[lane*128+:128]=allowed[lane] ?
        {5'b0,packet[122],token,packet[108:0]} : 128'b0;
    end
    for (record=0;record<2;record=record+1) begin : g_record
      localparam [2:0] RECORD=record;
      wire [3:0] select_lane;
      wire [191:0] selected;
      for (lane=0;lane<4;lane=lane+1) begin : g_select
        assign select_lane[lane]=allowed[lane] && candidate_packet[lane*192+105] &&
          pc_count[lane]==RECORD;
      end
      wire [191:0] mux_value [0:4];
      assign mux_value[0]=192'b0;
      for (lane=0;lane<4;lane=lane+1) begin : g_mux
        assign mux_value[lane+1]=mux_value[lane] |
          ({192{select_lane[lane]}} & candidate_packet[lane*192+:192]);
      end
      assign selected=mux_value[4];
      assign create_en[record]=accept && !flush && (|select_lane);
      assign create_pc[record*32+:32]=selected[63:32];
      assign create_target[record*32+:32]=selected[159:128];
      assign create_npc[record*32+:32]=selected[95:64];
      assign create_type[record*3+:3]=selected[108:106];
      assign create_dst[record]=selected[185];
      assign create_pred[record]=selected[108:106]==3'd1 && selected[122];
      assign create_unknown[record]=selected[186];
      assign create_chk[record*25+:25]=selected[184:160];
    end
  endgenerate
''')

emit('ipdp', ports('''
input 32 ifdp_ipdp_vpc
input 128 ifdp_ipdp_inst_data0 ifdp_ipdp_inst_data1
input 3 ifdp_ipdp_tag_match0 ifdp_ipdp_tag_match1
input 2 ifdp_ipdp_way_pred
input 1 ifdp_ipdp_fault ifdp_ipdp_lbuf_on
input 4 ifdp_ipdp_cause ifdp_ipdp_bkpta ifdp_ipdp_bkptb ifdp_ipdp_no_spec
input 4 remaining_mask
input 1 bht_pred
input 25 bht_chk_idx
input 4 ifdp_ipdp_btb_hit
input 128 ifdp_ipdp_btb_target
input 8 ifdp_ipdp_btb_way
output 2 tag_hit data_hit
output 4 control_mask cond_mask taken_mask
output 768 slot_packet
output 128 slot_npc
'''), '''
  wire [127:0] data;
  genvar lane;
  assign tag_hit={(&ifdp_ipdp_tag_match1),(&ifdp_ipdp_tag_match0)};
  assign data_hit=tag_hit & ifdp_ipdp_way_pred;
  assign data=data_hit[0] ? ifdp_ipdp_inst_data0 : ifdp_ipdp_inst_data1;
  generate
    for(lane=0;lane<4;lane=lane+1) begin : g_word
      localparam [1:0] LANE=lane;
      wire [31:0] inst,pc,target,link,npc,early_target;
      wire condbr,jal,jalr,auipc,pc_oper,dst,push,pop,usable,bad;
      wire [2:0] cf_type;
      wire prediction_taken,btb_hit,fence;
      wire [127:0] packet;
      assign inst=ifdp_ipdp_fault ? 32'h00000013 : data[lane*32+:32];
      assign pc=ifdp_ipdp_fault ? ifdp_ipdp_vpc : {ifdp_ipdp_vpc[31:4],LANE,2'b00};
      rv32_ifu_bp_decode u_decode(.inst(inst),.pc(pc),.condbr(condbr),.jal(jal),
        .jalr(jalr),.auipc(auipc),.pc_oper(pc_oper),.dst_vld(dst),.cf_type(cf_type),
        .ras_push(push),.ras_pop(pop),.ras_target_usable(usable),
        .direct_target(target),.direct_misaligned(bad),.link_pc(link));
      assign btb_hit=ifdp_ipdp_btb_hit[lane] && ifdp_ipdp_btb_target[lane*32+:2]==2'b00;
      assign early_target=btb_hit ? ifdp_ipdp_btb_target[lane*32+:32] : target;
      assign prediction_taken=!ifdp_ipdp_fault &&
        ((condbr && bht_pred) || jal || (jalr && btb_hit));
      assign npc=prediction_taken && (jalr || !bad) ? early_target : link;
      assign fence=inst[6:0]==7'h0f && inst[14:12]==0;
      // Internal reserved bits carry source Way until PCFIFO strips them from
      // the external IDU packet. A same-line direct target can reuse this hint.
      assign packet={3'b0,(data_hit[0] ? 2'b01 : 2'b10),prediction_taken,13'b0,cf_type,pc_oper && !ifdp_ipdp_fault,
        ifdp_ipdp_bkptb[lane],ifdp_ipdp_bkpta[lane],fence,ifdp_ipdp_no_spec[lane],
        (ifdp_ipdp_fault ? ifdp_ipdp_cause : 4'b0),ifdp_ipdp_fault,npc,pc,inst};
      assign slot_packet[lane*192+:192]={ifdp_ipdp_lbuf_on,btb_hit,usable,pop,push,
        (jalr && !btb_hit),dst,bht_chk_idx,target,packet};
      assign slot_npc[lane*32+:32]=npc;
      assign cond_mask[lane]=remaining_mask[lane] && condbr && !ifdp_ipdp_fault;
      assign control_mask[lane]=remaining_mask[lane] && (condbr || jal || jalr || ifdp_ipdp_fault);
      assign taken_mask[lane]=remaining_mask[lane] && (prediction_taken || jalr || ifdp_ipdp_fault);
    end
  endgenerate
''')

emit('ipctrl', ports('''
input 1 forever_cpuclk cpurst_b cancel ifctrl_ipctrl_vld ifctrl_ifdp_pipedown
input 4 ifdp_ipdp_word_mask control_mask cond_mask taken_mask
input 2 tag_hit data_hit
input 1 ifdp_ipdp_fault ifdp_ipdp_cache_bypass ifdp_ipdp_fifo
input 32 ifdp_ipdp_vpc
input 768 slot_packet
input 1 ib_ready demand_ready
input 1 ifctrl_ipctrl_if_pcload ifdp_ipdp_l0_hit
input 2 ifdp_ipdp_l0_slot
input 3 ifdp_ipdp_l0_type
input 32 ifdp_ipdp_l0_target
input 16 ifdp_ipdp_l0_entry_mask
output 4 remaining_mask fragment_mask
output 3 fragment_count
output 768 fragment_packet
output 1 fragment_valid fragment_fire
output 1 ipctrl_ifctrl_stall
output 1 demand_valid
output 32 demand_pc
output 1 demand_way
output 1 reissue redirect
output 32 redirect_pc
output 2 reissue_way
output 1 bht_event bht_taken bht_more
output 1 l0_invalidate
output 16 l0_invalidate_mask
output 1 fault_accept way_event miss_event
'''), '''
  reg [3:0] processed_q;
  wire [3:0] processed_nxt;
  wire processed_en;
  wire [3:0] first_control, last_slot;
  wire [2:0] rank [0:4];
  wire wrong_way,miss,valid_data,terminal,done;
  wire [1:0] last_index;
  wire [191:0] last_packet;
  wire reaches_l0,l0_correct,path_change,short_block;
  genvar lane,bit_index;
  assign remaining_mask=ifdp_ipdp_word_mask & ~processed_q;
  assign wrong_way=!ifdp_ipdp_fault && !ifdp_ipdp_cache_bypass && (|tag_hit) && !(|data_hit);
  assign miss=!ifdp_ipdp_fault && (ifdp_ipdp_cache_bypass || !(|tag_hit));
  assign valid_data=ifctrl_ipctrl_vld && !cancel && !wrong_way && !miss;
  assign demand_valid=ifctrl_ipctrl_vld && !cancel && miss;
  assign demand_pc=ifdp_ipdp_vpc;
  assign demand_way=ifdp_ipdp_fifo;
  assign miss_event=demand_valid && demand_ready;
  assign way_event=ifctrl_ipctrl_vld && !cancel && wrong_way;
  assign reissue=way_event || miss_event;
  assign reissue_way=wrong_way ? tag_hit : 2'b11;
  assign rank[0]=0;
  generate
    for(lane=0;lane<4;lane=lane+1) begin : g_prefix
      localparam [2:0] LANE=lane;
      if(lane==0) begin : g_first
        assign first_control[lane]=control_mask[lane];
        assign fragment_mask[lane]=remaining_mask[lane];
      end else begin : g_later
        assign first_control[lane]=control_mask[lane] && !(|control_mask[lane-1:0]);
        assign fragment_mask[lane]=remaining_mask[lane] && !(|control_mask[lane-1:0]);
      end
      if(lane==3) begin : g_final
        assign last_slot[lane]=fragment_mask[lane];
      end else begin : g_before_final
        assign last_slot[lane]=fragment_mask[lane] && !(|fragment_mask[3:lane+1]);
      end
      assign rank[lane+1]=rank[lane]+{2'b0,fragment_mask[lane]};
      wire [191:0] mux_value [0:4];
      genvar source;
      assign mux_value[0]=192'b0;
      for(source=0;source<4;source=source+1) begin : g_compact
        assign mux_value[source+1]=mux_value[source] |
          ({192{fragment_mask[source] && rank[source]==LANE}} & slot_packet[source*192+:192]);
      end
      assign fragment_packet[lane*192+:192]=mux_value[4];
    end
  endgenerate
  assign fragment_count=rank[4];
  assign last_index={last_slot[2] || last_slot[3],last_slot[1] || last_slot[3]};
  assign last_packet=slot_packet[{30'b0,last_index}*32'd192+:192];
  assign terminal=|(fragment_mask & taken_mask);
  assign fragment_valid=valid_data && (|fragment_mask);
  assign fragment_fire=fragment_valid && ib_ready;
  assign done=reissue || (fragment_fire && (terminal || fragment_mask==remaining_mask));
  assign ipctrl_ifctrl_stall=ifctrl_ipctrl_vld && !done && !cancel;
  assign processed_en=cancel || ifctrl_ifdp_pipedown || fragment_fire || done;
  assign processed_nxt=(cancel || ifctrl_ifdp_pipedown || done) ? 4'b0 : processed_q | fragment_mask;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_processed
    if(!cpurst_b) processed_q<=4'b0;
    else if(processed_en) processed_q<=processed_nxt;
  end
  assign bht_event=fragment_fire && (|(fragment_mask & cond_mask));
  // Direction history describes the prediction, even when execution must later
  // report a misaligned actual target at the source instruction.
  assign bht_taken=last_packet[122];
  assign bht_more=valid_data && !terminal && (|(remaining_mask & ~fragment_mask));
  assign reaches_l0=ifctrl_ipctrl_if_pcload &&
    (terminal || fragment_mask[ifdp_ipdp_l0_slot] || fragment_mask==remaining_mask);
  assign l0_correct=ifdp_ipdp_l0_hit && last_index==ifdp_ipdp_l0_slot &&
    last_packet[108:106]==ifdp_ipdp_l0_type && last_packet[122] &&
    last_packet[95:64]==ifdp_ipdp_l0_target;
  assign short_block=!terminal && fragment_mask==remaining_mask && last_index!=3;
  assign path_change=terminal ? (!ifctrl_ipctrl_if_pcload || !l0_correct) : reaches_l0 || short_block;
  assign redirect=fragment_fire && !ifdp_ipdp_fault && path_change;
  assign redirect_pc=(terminal || short_block) ? last_packet[95:64] : {ifdp_ipdp_vpc[31:4]+28'd1,4'b0};
  assign l0_invalidate=fragment_fire && reaches_l0 && !l0_correct;
  assign l0_invalidate_mask=ifdp_ipdp_l0_entry_mask;
  assign fault_accept=fragment_fire && ifdp_ipdp_fault;
''')

emit('addrgen', ports('''
input 192 source_packet
input 1 ras_valid ind_valid
input 32 ras_target ind_target
output 192 result_packet
output 1 correction
output 32 corrected_pc
output 22 retained_ghr
'''), '''
  // The source is the registered IP/IB packet. Validate static targets here,
  // before any token allocation or irreversible IB acceptance.
  wire [2:0] kind;
  wire [31:0] pc,link,chosen,npc,recorded;
  wire direct,jalr,available,bad,taken,unknown;
  wire [127:0] instruction;
  assign kind=source_packet[108:106];
  assign pc=source_packet[63:32];
  assign link=pc+32'd4;
  assign direct=kind==1 || kind==2;
  assign jalr=kind==3;
  assign available=(source_packet[189] && ras_valid) || ind_valid || source_packet[190];
  assign chosen=(source_packet[189] && ras_valid) ? ras_target :
    ind_valid ? ind_target : source_packet[95:64];
  assign bad=jalr ? (|chosen[1:0]) : (|source_packet[129:128]);
  assign unknown=jalr && (!available || bad);
  assign taken=jalr ? !unknown : source_packet[122];
  assign npc=jalr ? (unknown ? link : chosen) :
    (direct && taken && !bad) ? source_packet[159:128] : link;
  assign recorded=jalr ? (unknown ? link : chosen) : source_packet[159:128];
  assign instruction={source_packet[127:123],taken,source_packet[121:96],npc,source_packet[63:0]};
  assign result_packet={source_packet[191:187],unknown,source_packet[185:160],recorded,instruction};
  assign correction=!source_packet[96] && npc!=source_packet[95:64];
  assign corrected_pc=npc;
  assign retained_ghr=kind==1 ? {source_packet[180:160],source_packet[122]} : source_packet[181:160];
''')

emit('ibdp', ports('''
input 1 forever_cpuclk cpurst_b load consume
input 3 consume_count
input 768 fragment_packet
input 1 ras_valid ind_valid
input 32 ras_target ind_target
output 768 raw_packet corrected_packet
output 4 correction
output 128 corrected_pc
output 88 retained_ghr
'''), '''
  reg [191:0] lane_q [0:3];
  wire [191:0] lane_nxt [0:3];
  wire lane_en;
  genvar lane;
  assign lane_en=load || consume;
  generate
    for(lane=0;lane<4;lane=lane+1) begin : g_lane
      wire [2:0] source;
      assign source=consume_count+lane;
      assign lane_nxt[lane]=load ? fragment_packet[lane*192+:192] :
        (source<4 ? lane_q[source] : 192'b0);
      always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_lane
        if(!cpurst_b) lane_q[lane]<=192'b0;
        else if(lane_en) lane_q[lane]<=lane_nxt[lane];
      end
      assign raw_packet[lane*192+:192]=lane_q[lane];
      rv32_ifu_addrgen u_addrgen(.source_packet(lane_q[lane]),.ras_valid(ras_valid),
        .ras_target(ras_target),.ind_valid(ind_valid),.ind_target(ind_target),
        .result_packet(corrected_packet[lane*192+:192]),.correction(correction[lane]),
        .corrected_pc(corrected_pc[lane*32+:32]),.retained_ghr(retained_ghr[lane*22+:22]));
    end
  endgenerate
''')

emit('ibctrl', ports('''
input 1 forever_cpuclk cpurst_b cancel
input 1 fragment_valid
input 3 fragment_count
output 1 ib_ready load
input 768 raw_packet corrected_packet
input 4 correction
input 128 corrected_pc
input 88 retained_ghr
input 1 recovery_stall ind_enable ind_result_vld ind_target_valid
input 32 ind_target
input 1 btb_update_ready
output 1 ind_query
output 1 saved_ind_valid
output 32 saved_ind_target
input 3 allowed_count
input 1 ibuf_ready
output 3 candidate_count consume_count
output 1 consume
output 1 redirect
output 32 redirect_pc
output 22 local_recover_ghr
output 1 ras_push ras_pop jump_accept return_accept ind_miss_event
output 32 push_pc jump_target
output 1 train_valid train_taken train_ras btb_used
output 32 train_pc train_target
output 3 train_type
output 2 train_way
output 8 ind_query_ghr
output 1 empty pcfifo_wait recovery_wait
'''), '''
  reg [2:0] count_q;
  wire [2:0] count_nxt;
  wire count_en;
  reg [1:0] wait_q;
  wire [1:0] wait_nxt;
  wire wait_en;
  reg [33:0] indirect_q;
  wire [33:0] indirect_nxt;
  wire indirect_en;
  wire [3:0] active,needs_recovery,is_jalr,accepted,selected_jump,selected_correction,selected_train,has_train;
  wire [1:0] jump_index,correction_index,train_index,query_index;
  wire [191:0] jump_packet,train_packet;
  wire query_needed,resolve_ready,done;
  genvar lane;
  assign empty=count_q==0;
  generate
    for(lane=0;lane<4;lane=lane+1) begin : g_lane
      assign active[lane]=lane<count_q;
      assign needs_recovery[lane]=active[lane] &&
        (raw_packet[lane*192+187] || raw_packet[lane*192+188] || raw_packet[lane*192+106+:3]==3);
      assign is_jalr[lane]=active[lane] && raw_packet[lane*192+106+:3]==3;
      assign has_train[lane]=active[lane] && raw_packet[lane*192+106+:3]!=0 && raw_packet[lane*192+106+:3]<4;
      assign accepted[lane]=consume && lane<consume_count;
      assign selected_jump[lane]=accepted[lane] &&
        (corrected_packet[lane*192+106+:3]==2 || corrected_packet[lane*192+106+:3]==3);
      assign selected_correction[lane]=accepted[lane] && correction[lane];
      assign selected_train[lane]=accepted[lane] && has_train[lane];
    end
  endgenerate
  assign recovery_wait=recovery_stall && (|needs_recovery);
  assign query_needed=ind_enable && (|is_jalr) && !indirect_q[33];
  assign ind_query=query_needed && !cancel && !recovery_wait;
  assign wait_en=cancel || load || ind_query;
  assign wait_nxt=(cancel || load) ? 2'b0 : wait_q==2 ? 2'd2 : wait_q+2'd1;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_wait
    if(!cpurst_b) wait_q<=2'b0;
    else if(wait_en) wait_q<=wait_nxt;
  end
  assign indirect_en=cancel || load || (ind_query && wait_q==2 && ind_result_vld);
  assign indirect_nxt=(cancel || load) ? 34'b0 : {1'b1,ind_target_valid,ind_target};
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_indirect
    if(!cpurst_b) indirect_q<=34'b0;
    else if(indirect_en) indirect_q<=indirect_nxt;
  end
  assign saved_ind_valid=indirect_q[33] && indirect_q[32];
  assign saved_ind_target=indirect_q[31:0];
  assign resolve_ready=!cancel && !recovery_wait && !query_needed && (!(|has_train) || btb_update_ready);
  assign candidate_count=resolve_ready ? count_q : 3'd0;
  assign consume=resolve_ready && ibuf_ready && (allowed_count!=0);
  assign consume_count=consume ? allowed_count : 3'd0;
  assign done=consume && consume_count==count_q;
  assign ib_ready=!cancel && (empty || (done && !redirect));
  assign load=fragment_valid && ib_ready;
  assign count_en=cancel || load || consume;
  assign count_nxt=cancel ? 3'd0 : load ? fragment_count : count_q-consume_count;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_count
    if(!cpurst_b) count_q<=3'b0;
    else if(count_en) count_q<=count_nxt;
  end
  assign redirect=|selected_correction;
  assign correction_index={selected_correction[2] || selected_correction[3],
                           selected_correction[1] || selected_correction[3]};
  assign redirect_pc=corrected_pc[{30'b0,correction_index}*32'd32+:32];
  assign local_recover_ghr=retained_ghr[{30'b0,correction_index}*32'd22+:22];
  assign jump_index={selected_jump[2] || selected_jump[3],selected_jump[1] || selected_jump[3]};
  assign jump_packet=corrected_packet[{30'b0,jump_index}*32'd192+:192];
  assign jump_accept=|selected_jump;
  assign ind_miss_event=jump_accept && jump_packet[108:106]==3 && !saved_ind_valid;
  assign ras_push=jump_accept && jump_packet[187];
  assign ras_pop=jump_accept && jump_packet[188];
  assign return_accept=ras_pop;
  assign push_pc=jump_packet[63:32]+32'd4;
  assign jump_target=jump_packet[95:64];
  assign train_valid=|selected_train;
  assign train_index={selected_train[2] || selected_train[3],selected_train[1] || selected_train[3]};
  assign train_packet=corrected_packet[{30'b0,train_index}*32'd192+:192];
  assign train_pc=train_packet[63:32];
  assign train_target=train_packet[159:128];
  assign train_type=train_packet[108:106];
  assign train_way=!train_packet[191] && train_packet[159:134]==train_packet[63:38] ? train_packet[124:123] : 2'b11;
  assign train_taken=train_packet[122];
  assign train_ras=train_packet[189];
  assign btb_used=train_valid && train_packet[190];
  assign query_index={is_jalr[2] || is_jalr[3],is_jalr[1] || is_jalr[3]};
  assign ind_query_ghr=raw_packet[{30'b0,query_index}*32'd192+160+:8];
  assign pcfifo_wait=candidate_count!=0 && allowed_count<candidate_count;
''')

def pipeline_wrapper():
    names=['ipdp','ipctrl','ibdp','ibctrl','pcfifo_if','ibuf']
    mapping={
        'ipctrl':{'cancel':'cancel_ip'},
        'ibctrl':{'cancel':'flush','ind_target':'ind_target','consume':'ib_accept'},
        'ibdp':{'consume':'ib_accept','ind_valid':'saved_ind_valid','ind_target':'saved_ind_target'},
        'pcfifo_if':{'accept':'ib_accept','candidate_packet':'corrected_packet'},
        'ibuf':{'in_count':'allowed_count','in_packet':'instruction_packet','in_ready':'ibuf_ready'},
    }
    exposed='''ipctrl_ifctrl_stall demand_valid demand_pc demand_way reissue reissue_way
redirect redirect_pc bht_event bht_taken bht_more l0_invalidate l0_invalidate_mask fault_accept
way_event miss_event ind_query ras_push ras_pop jump_accept return_accept ind_miss_event push_pc jump_target
local_recover_ghr empty pcfifo_wait recovery_wait create_en create_pc create_target create_npc
create_type create_dst create_pred create_unknown create_chk out_count out_packet occupancy
train_valid train_taken train_ras train_pc train_target train_type btb_used ind_query_ghr
train_way
ib_accept consume_count corrected_packet
'''.split()
    # IP and IB redirects have distinct cancellation domains.
    mapping['ipctrl'].update({'redirect':'ip_redirect','redirect_pc':'ip_redirect_pc'})
    mapping['ibctrl'].update({'redirect':'ib_redirect','redirect_pc':'ib_redirect_pc','empty':'ib_empty'})
    mapping['ibuf']['empty']='ibuf_empty'
    exposed=[n for n in exposed if n not in ['redirect','redirect_pc','empty']]
    exposed+=['ip_redirect','ip_redirect_pc','ib_redirect','ib_redirect_pc','ib_empty','ibuf_empty']
    signals={}
    inst=[]
    for name in names:
        con=[]
        for d,w,n in public_ports((ROOT/'rtl'/f'rv32_ifu_{name}.v').read_text()):
            m=mapping.get(name,{}).get(n,n)
            width=int(w.strip('[] ').split(':')[0])+1 if w else 1
            if m not in signals or d=='output':signals[m]=(d,width)
            con.append(f'.{n}({m})')
        inst.append('  rv32_ifu_'+name+' u_'+name+'('+',\n'.join(con)+');')
    ps=[(d,w,n) for n,(d,w) in signals.items() if d=='input' or n in exposed]
    wires='\n'.join('  wire '+(f'[{w-1}:0] ' if w>1 else '')+n+';'
                    for n,(d,w) in signals.items() if d=='output' and n not in exposed)
    emit('pipeline',ps,wires+'\n'+'\n'.join(inst))


pipeline_wrapper()
(ROOT/'rtl/pipeline_files.f').write_text('rtl/rv32_ifu_bp_decode.v\n'+'\n'.join(PRODUCTS)+'\n')
print('Generated',len(PRODUCTS),'pipeline modules')
