"""Independent demand refill and C910-style next-line prefetch/replay duties."""
from pathlib import Path
import re
from rtl_style import layout,public_ports
ROOT=Path(__file__).resolve().parents[1]
PRODUCTS=[]

def emit(name,spec,body):
    decl=re.findall(r'^  (?:reg|wire|genvar) [^;\n]+;\n',body,re.M)
    body=''.join(decl)+re.sub(r'^  (?:reg|wire|genvar) [^;\n]+;\n','',body,flags=re.M)
    ps=[(d,int(w),n) for line in spec.strip().splitlines()
        for d,w,names in [line.split(maxsplit=2)] for n in names.split()]
    s='''// SPDX-License-Identifier: Apache-2.0
// RV32I adaptation of C910 refill/IPB responsibilities; no Cache lookup FSM.
// Generated by scripts/build_memory.py. All PCs are physical byte addresses.
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
'''+f'module rv32_ifu_{name} (\n'
    s+=',\n'.join('  '+d+' wire '+(f'[{w-1}:0] ' if w>1 else '')+n for d,w,n in ps)+'\n);\n'+body+'\nendmodule\n'
    (ROOT/'rtl'/f'rv32_ifu_{name}.v').write_text(layout(s))
    PRODUCTS.append('rtl/rv32_ifu_'+name+'.v')

def regs(spec):
    """Distinct state fields use identical reset/enable update grammar."""
    s=''
    for name,width,reset,en,nxt in spec:
        w=f'[{width-1}:0] ' if width>1 else ''
        s+=f'''  reg {w}{name}_q;
  wire {w}{name}_nxt;
  wire {name}_en;
  assign {name}_en={en};
  assign {name}_nxt={nxt};
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_{name}
    if(!cpurst_b) {name}_q<={reset};
    else if({name}_en) {name}_q<={name}_nxt;
  end
'''
    return s

emit('l1_refill','''
input 1 forever_cpuclk cpurst_b cancel invalidate
input 1 demand_valid
output 1 demand_ready
input 32 demand_pc
input 1 demand_way demand_allocate
input 5 demand_attr
input 2 demand_priv
output 1 memory_request
input 1 memory_grant
output 32 memory_pc
output 1 memory_allocate
output 5 memory_attr
output 2 memory_priv
input 1 memory_valid memory_error memory_last
input 128 memory_data
output 1 memory_ready
output 1 refill_array_req
input 1 ifctrl_refill_grant
output 1 l1_refill_icache_if_wr l1_refill_icache_if_first l1_refill_icache_if_last l1_refill_icache_if_install
output 1 l1_refill_icache_if_fifo
output 32 l1_refill_icache_if_index
output 128 l1_refill_icache_if_inst_data
output 32 l1_refill_icache_if_pre_code
output 17 l1_refill_icache_if_ptag
output 1 l1_refill_ifctrl_active l1_refill_ifctrl_live l1_refill_ifctrl_vld
output 32 l1_refill_ifctrl_pc
input 1 ifctrl_l1_refill_ready
output 128 l1_refill_ifdp_inst_data
output 32 l1_refill_ifdp_precode
output 1 l1_refill_ifdp_acc_err
output 1 idle protocol_error request_accepted
''', '''
  localparam [1:0] IDLE=0,REQ=1,WAIT=2,DONE=3;
  wire start,receive,write_done,first,last,error,finish;
  wire [1:0] block;
  wire [31:0] incoming_precode;
  assign start=demand_valid && demand_ready;
  assign demand_ready=state_q==IDLE && !invalidate && !cancel;
  assign memory_request=state_q==REQ && !cancel && !invalidate;
  assign request_accepted=memory_request && memory_grant;
  assign memory_pc=desc_q[41:10];
  assign memory_allocate=desc_q[9];
  assign memory_attr=desc_q[8:4];
  assign memory_priv=desc_q[3:2];
  assign idle=state_q==IDLE;
  assign memory_ready=state_q==WAIT && !pending_q;
  assign receive=memory_valid && memory_ready;
  assign first=count_q==0;
  assign last=memory_last;
  assign error=memory_error || (memory_last != (memory_allocate ? count_q==3 : count_q==0));
  assign block=memory_pc[5:4]+count_q;
  assign refill_array_req=pending_q && memory_allocate && !killed_q && !invalidate;
  assign write_done=pending_q && (!memory_allocate || killed_q || invalidate || ifctrl_refill_grant);
  assign finish=state_q==DONE && !pending_q && !forward_valid_q;
  assign l1_refill_icache_if_wr=refill_array_req;
  assign l1_refill_icache_if_first=beat_q[162];
  assign l1_refill_icache_if_last=beat_q[163];
  assign l1_refill_icache_if_install=refill_array_req && beat_q[163] && !error_q && !beat_q[164];
  assign l1_refill_icache_if_index={memory_pc[31:6],beat_q[161:160],4'b0};
  assign l1_refill_icache_if_fifo=desc_q[1];
  assign l1_refill_icache_if_ptag=memory_pc[31:15];
  assign l1_refill_icache_if_inst_data=beat_q[127:0];
  assign l1_refill_icache_if_pre_code=beat_q[159:128];
  assign l1_refill_ifctrl_active=!idle;
  assign l1_refill_ifctrl_live=live_q && !cancel && !invalidate;
  assign l1_refill_ifctrl_vld=forward_valid_q && l1_refill_ifctrl_live;
  assign l1_refill_ifctrl_pc=memory_pc;
  assign l1_refill_ifdp_inst_data=forward_q[127:0];
  assign l1_refill_ifdp_precode=forward_q[159:128];
  assign l1_refill_ifdp_acc_err=forward_q[160];
  assign protocol_error=protocol_q;
  rv32_ifu_icache_precode u_precode(.data(memory_data),.precode(incoming_precode));
''' + regs([
    ('state',2,"IDLE","1'b1","start ? REQ : (state_q==REQ && (cancel || invalidate)) ? IDLE : request_accepted ? WAIT : (receive && last) ? DONE : finish ? IDLE : state_q"),
    ('desc',42,"42'b0","start","{demand_pc,demand_allocate,demand_attr,demand_priv,demand_way,1'b0}"),
    ('live',1,"1'b0","start || cancel || invalidate || finish","start"),
    ('killed',1,"1'b0","start || invalidate","!start"),
    ('count',2,"2'b0","start || receive","start ? 2'd0 : count_q+2'd1"),
    ('pending',1,"1'b0","start || receive || write_done","!start && receive"),
    ('beat',165,"165'b0","receive","{error,last,first,block,incoming_precode,memory_data}"),
    ('error',1,"1'b0","start || receive","!start && (error_q || error)"),
    ('forward_valid',1,"1'b0","start || cancel || invalidate || (receive && first) || ifctrl_l1_refill_ready",
      "!start && !cancel && !invalidate && ((receive && first && live_q) || (forward_valid_q && !ifctrl_l1_refill_ready))"),
    ('forward',161,"161'b0","receive && first","{error,incoming_precode,memory_data}"),
    ('protocol',1,"1'b0","receive","protocol_q || (memory_last != (memory_allocate ? count_q==3 : count_q==0))"),
]))

emit('ipb','''
input 1 forever_cpuclk cpurst_b enable stop invalidate
input 1 trigger
input 32 trigger_pc
output 32 region_pc
input 5 region_attr
output 1 ipb_array_req
input 1 ifctrl_ipb_grant
input 18 icache_if_ipb_tag_data0 icache_if_ipb_tag_data1
output 32 ipb_icache_if_index
output 1 ipb_icache_if_req ipb_icache_if_req_for_gateclk
output 1 memory_request
input 1 memory_grant
output 32 memory_pc
output 5 memory_attr
input 1 memory_valid memory_error memory_last
input 128 memory_data
output 1 memory_ready
input 1 demand_request
input 32 demand_pc
output 1 demand_match demand_grant
output 1 replay_valid replay_last
output 128 replay_data
input 1 replay_ready
output 1 idle launch demand_hit
''', '''
  localparam [2:0] IDLE=0,CACHE=1,CMP=2,REQ=3,FILL=4,VALID=5,REPLAY=6;
  wire [32:0] next_line;
  wire eligible,start,tag_hit,receive,take_replay,replay_end,match_line;
  reg [127:0] block_q [0:3];
  wire [127:0] block_nxt [0:3];
  wire [3:0] block_en;
  genvar block_index;
  assign next_line={1'b0,trigger_pc[31:6],6'b0}+33'd64;
  assign region_pc=next_line[31:0];
  assign eligible=enable && !stop && !invalidate && !next_line[32] &&
    next_line[31:12]==trigger_pc[31:12] && region_attr[4] && region_attr[3] && region_attr[0];
  assign start=trigger && state_q==IDLE && eligible;
  assign idle=state_q==IDLE || state_q==VALID;
  assign ipb_array_req=state_q==CACHE && !invalidate;
  assign ipb_icache_if_req=ipb_array_req;
  assign ipb_icache_if_req_for_gateclk=ipb_array_req;
  assign ipb_icache_if_index=pc_q;
  assign tag_hit=icache_if_ipb_tag_data0=={1'b1,pc_q[31:15]} ||
                 icache_if_ipb_tag_data1=={1'b1,pc_q[31:15]};
  assign memory_request=state_q==REQ && !invalidate && !stop;
  assign memory_pc=pc_q;
  assign memory_attr=attr_q;
  assign launch=memory_request && memory_grant;
  assign memory_ready=state_q==FILL;
  assign receive=memory_valid && memory_ready;
  assign match_line=demand_pc[31:6]==pc_q[31:6];
  assign demand_match=!invalidate && !killed_q && match_line &&
    (state_q==CACHE || state_q==CMP || state_q==REQ || state_q==FILL || state_q==VALID);
  assign demand_grant=demand_request && demand_match && state_q==VALID;
  assign demand_hit=demand_grant;
  assign replay_valid=state_q==REPLAY;
  assign replay_last=replay_count_q==3;
  assign replay_data=block_q[replay_offset_q];
  assign take_replay=replay_valid && replay_ready;
  assign replay_end=take_replay && replay_last;
  generate
    for(block_index=0;block_index<4;block_index=block_index+1) begin : g_block
      assign block_en[block_index]=receive && count_q==block_index;
      assign block_nxt[block_index]=memory_data;
      always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_block
        if(!cpurst_b) block_q[block_index]<=128'b0;
        else if(block_en[block_index]) block_q[block_index]<=block_nxt[block_index];
      end
    end
  endgenerate
''' + regs([
    ('state',3,'IDLE',"1'b1",'''(invalidate && state_q!=FILL && state_q!=REPLAY) ? IDLE :
      start ? CACHE : (state_q==CACHE && ifctrl_ipb_grant) ? CMP :
      state_q==CMP ? (tag_hit ? IDLE : REQ) : (state_q==REQ && stop) ? IDLE :
      launch ? FILL : (receive && memory_last) ?
        ((error_q || memory_error || killed_q || invalidate || count_q!=3) ? IDLE : VALID) :
      demand_grant ? REPLAY : replay_end ? IDLE : state_q'''),
    ('pc',32,"32'b0",'start','next_line[31:0]'),
    ('attr',5,"5'b0",'start','region_attr'),
    ('count',2,"2'b0",'start || receive',"start ? 2'b0 : count_q+2'd1"),
    ('error',1,"1'b0",'start || receive','!start && (error_q || memory_error)'),
    ('killed',1,"1'b0",'start || invalidate','!start'),
    ('replay_count',2,"2'b0",'demand_grant || take_replay',"demand_grant ? 2'b0 : replay_count_q+2'd1"),
    ('replay_offset',2,"2'b0",'demand_grant || take_replay',"demand_grant ? demand_pc[5:4] : replay_offset_q+2'd1"),
]))

emit('biu','''
input 1 forever_cpuclk cpurst_b
input 1 demand_request prefetch_request demand_allocate
input 32 demand_pc prefetch_pc
input 5 demand_attr prefetch_attr
input 2 demand_priv cp0_yy_priv_mode
input 1 cp0_ifu_insde
input 1 prefetch_match prefetch_replay_grant
output 1 demand_grant prefetch_grant
input 1 demand_ready prefetch_ready
output 1 demand_valid prefetch_valid
output 128 response_data
output 1 response_error response_last
output 1 ifu_biu_rd_req ifu_biu_rd_req_gate ifu_biu_rd_id
output 32 ifu_biu_rd_addr
output 2 ifu_biu_rd_len ifu_biu_rd_burst ifu_biu_rd_domain ifu_biu_rd_user
output 3 ifu_biu_rd_size ifu_biu_rd_prot
output 4 ifu_biu_rd_cache ifu_biu_rd_snoop
input 1 biu_ifu_rd_grnt biu_ifu_rd_data_vld biu_ifu_rd_id biu_ifu_rd_last
input 128 biu_ifu_rd_data
input 2 biu_ifu_rd_resp
output 1 ifu_biu_r_ready idle
''', '''
  reg [1:0] outstanding_q;
  wire [1:0] outstanding_nxt,outstanding_en;
  wire select_demand,select_prefetch;
  wire [4:0] attr;
  wire [1:0] priv;
  wire allocate,response_fire;
  genvar id;
  assign select_demand=demand_request && !prefetch_match && !outstanding_q[0];
  assign select_prefetch=prefetch_request && !outstanding_q[1] && !select_demand;
  assign ifu_biu_rd_req=cpurst_b && (select_demand || select_prefetch);
  assign ifu_biu_rd_req_gate=ifu_biu_rd_req;
  assign ifu_biu_rd_id=select_prefetch;
  assign ifu_biu_rd_addr=select_demand ? {demand_pc[31:4],4'b0} : prefetch_pc;
  assign allocate=select_prefetch || demand_allocate;
  assign attr=select_demand ? demand_attr : prefetch_attr;
  assign priv=select_demand ? demand_priv : cp0_yy_priv_mode;
  assign ifu_biu_rd_len=allocate ? 2'b11 : 2'b00;
  assign ifu_biu_rd_burst=allocate ? 2'b10 : 2'b01;
  assign ifu_biu_rd_size=3'b100;
  assign ifu_biu_rd_cache={attr[3],attr[3],1'b1,attr[2]};
  assign ifu_biu_rd_prot={1'b1,attr[1],priv!=0};
  assign ifu_biu_rd_domain=attr[3] ? {1'b0,!cp0_ifu_insde} : 2'b11;
  assign ifu_biu_rd_snoop=allocate && !cp0_ifu_insde ? 4'b0001 : 4'b0000;
  assign ifu_biu_rd_user={priv==3,1'b0};
  assign demand_grant=prefetch_replay_grant || (ifu_biu_rd_req && select_demand && biu_ifu_rd_grnt);
  assign prefetch_grant=ifu_biu_rd_req && select_prefetch && biu_ifu_rd_grnt;
  assign ifu_biu_r_ready=outstanding_q[biu_ifu_rd_id] && (biu_ifu_rd_id ? prefetch_ready : demand_ready);
  assign response_fire=biu_ifu_rd_data_vld && ifu_biu_r_ready;
  assign demand_valid=biu_ifu_rd_data_vld && !biu_ifu_rd_id && outstanding_q[0];
  assign prefetch_valid=biu_ifu_rd_data_vld && biu_ifu_rd_id && outstanding_q[1];
  assign response_data=biu_ifu_rd_data;
  assign response_error=biu_ifu_rd_resp[1];
  assign response_last=biu_ifu_rd_last;
  assign idle=!(|outstanding_q) && !ifu_biu_rd_req;
  generate
    for(id=0;id<2;id=id+1) begin : g_id
      wire launch,complete;
      assign launch=ifu_biu_rd_req && biu_ifu_rd_grnt && ifu_biu_rd_id==id;
      assign complete=response_fire && biu_ifu_rd_last && biu_ifu_rd_id==id;
      assign outstanding_en[id]=launch || complete;
      assign outstanding_nxt[id]=launch;
      always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_outstanding
        if(!cpurst_b) outstanding_q[id]<=1'b0;
        else if(outstanding_en[id]) outstanding_q[id]<=outstanding_nxt[id];
      end
    end
  endgenerate
''')

def wrapper():
    maps={
      'l1_refill':{n:'refill_'+n for n in ['memory_request','memory_grant','memory_pc',
        'memory_allocate','memory_attr','memory_priv','memory_valid','memory_error',
        'memory_last','memory_data','memory_ready','idle','request_accepted']},
      'ipb':{n:'prefetch_'+n for n in ['memory_request','memory_grant','memory_pc','memory_attr',
        'memory_valid','memory_error','memory_last','memory_data','memory_ready','idle','demand_match','demand_grant']},
      'biu':{'demand_request':'refill_memory_request','prefetch_request':'prefetch_memory_request',
        'demand_allocate':'refill_memory_allocate','demand_pc':'refill_memory_pc',
        'prefetch_pc':'prefetch_memory_pc','demand_attr':'refill_memory_attr',
        'prefetch_attr':'prefetch_memory_attr','demand_priv':'refill_memory_priv',
        'prefetch_match':'reuse_match','prefetch_replay_grant':'prefetch_demand_grant',
        'demand_grant':'refill_memory_grant','prefetch_grant':'prefetch_memory_grant',
        'demand_ready':'refill_memory_ready','prefetch_ready':'prefetch_memory_ready',
        'demand_valid':'bus_demand_valid','prefetch_valid':'prefetch_memory_valid','idle':'bus_idle'},
    }
    maps['ipb'].update({'demand_request':'reuse_request','demand_pc':'refill_memory_pc','trigger':'prefetch_trigger'})
    internal='''refill_memory_request refill_memory_grant refill_memory_pc refill_memory_allocate
refill_memory_attr refill_memory_priv refill_memory_valid refill_memory_error refill_memory_last
refill_memory_data refill_memory_ready refill_request_accepted
prefetch_memory_request prefetch_memory_grant prefetch_memory_pc prefetch_memory_attr
prefetch_memory_valid prefetch_memory_error prefetch_memory_last prefetch_memory_data prefetch_memory_ready
prefetch_demand_match prefetch_demand_grant replay_valid replay_last replay_data replay_ready
bus_demand_valid response_data response_error response_last reuse_match reuse_request prefetch_trigger trigger_pc
'''.split()
    signals={};inst=[]
    for name in maps:
      con=[]
      for d,w,n in public_ports((ROOT/'rtl'/f'rv32_ifu_{name}.v').read_text()):
        m=maps[name].get(n,n)
        if m not in signals or d=='output':signals[m]=(d,w)
        con.append(f'.{n}({m})')
      inst.append('rv32_ifu_'+name+' u_'+name+'('+',\n'.join(con)+');')
    spec='\n'.join(d+' '+str(int(w.strip('[] ').split(':')[0])+1 if w else 1)+' '+n
      for n,(d,w) in signals.items() if n not in internal)
    decl='\n'.join('  wire '+w+' '+n+';' for n,(d,w) in signals.items() if n in internal)
    body=decl+'''
  assign reuse_match=prefetch_demand_match && refill_memory_allocate;
  assign reuse_request=refill_memory_request && refill_memory_allocate;
  assign prefetch_trigger=refill_request_accepted && refill_memory_allocate;
  assign trigger_pc=refill_memory_pc;
  assign refill_memory_valid=bus_demand_valid || replay_valid;
  assign refill_memory_data=replay_valid ? replay_data : response_data;
  assign refill_memory_last=replay_valid ? replay_last : response_last;
  assign refill_memory_error=!replay_valid && response_error;
  assign replay_ready=refill_memory_ready;
  assign prefetch_memory_data=response_data;
  assign prefetch_memory_last=response_last;
  assign prefetch_memory_error=response_error;
'''+ '\n'.join(inst)
    emit('memory',spec,body)

wrapper()
(ROOT/'rtl/memory_files.f').write_text('rtl/rv32_ifu_icache_precode.v\n'+'\n'.join(PRODUCTS)+'\n')
print('Generated',len(PRODUCTS),'memory modules')
