"""Connect the sole IF arbiter grants to C910-derived Cache array controls."""
from pathlib import Path
from rtl_style import public_ports, layout

ROOT = Path(__file__).resolve().parents[1]
ports = public_ports((ROOT/'rtl/rv32_ifu_icache_if.v').read_text())
gated = {}
for _,_,n in ports:
    if n in ['ifctrl_icache_if_inv_on', 'ifctrl_icache_if_read_req_data0',
             'ifctrl_icache_if_read_req_data1', 'ifctrl_icache_if_read_req_tag',
             'ifctrl_icache_if_reset_req', 'ifctrl_icache_if_tag_req']:
        gated[n] = (0,n)
    elif n in ['l1_refill_icache_if_install','l1_refill_icache_if_first',
               'l1_refill_icache_if_last','l1_refill_icache_if_wr']:
        gated[n] = (1,n)
    elif n in ['ipb_icache_if_req','ipb_icache_if_req_for_gateclk']:
        gated[n] = (2,n)
    elif n.startswith('pcgen_icache_if_') and n not in [
            'pcgen_icache_if_index','pcgen_icache_if_way_pred',
            'pcgen_icache_if_seq_data_req','pcgen_icache_if_seq_data_req_short',
            'pcgen_icache_if_seq_tag_req']:
        gated[n] = (3,"1'b1")
s = '''// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/build_if_array.py. Grant gating and array wiring only.
// No fetch, miss, Way replay, or maintenance state machine exists here.
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
module rv32_ifu_if_array (
  input wire [3:0] ifctrl_array_grant,
  input wire [31:0] ifctrl_array_pc,
  input wire [1:0] ifctrl_array_way,
'''
s += ',\n'.join(f'  {d} wire {w} {n}' for d,w,n in ports if not n.startswith('pcgen_'))+'\n);\n'
s += f'  localparam CONTROL_COUNT = {len(gated)};\n'
s += '  localparam [CONTROL_COUNT*2-1:0] OWNER = {'+', '.join(f"2'd{v[0]}" for v in reversed(list(gated.values())))+'};\n'
s += '  genvar control;\n  wire [CONTROL_COUNT-1:0] requests;\n  wire [CONTROL_COUNT-1:0] grants;\n'
s += '  assign requests = {'+', '.join(v[1] for v in reversed(list(gated.values())))+'};\n'
s += '''  generate
    for (control = 0; control < CONTROL_COUNT; control = control + 1) begin : g_control
      assign grants[control] = requests[control] && ifctrl_array_grant[OWNER[control*2+:2]];
    end
  endgenerate
  rv32_ifu_icache_if u_icache_if (
'''
connections=[]
for _,_,n in ports:
    if n in gated: expr = f'grants[{list(gated).index(n)}]'
    elif n == 'pcgen_icache_if_index': expr = 'ifctrl_array_pc'
    elif n == 'pcgen_icache_if_way_pred': expr = 'ifctrl_array_way'
    elif n.startswith('pcgen_'): expr = "1'b0"
    else: expr=n
    connections.append(f'    .{n}({expr})')
s += ',\n'.join(connections)+'\n  );\nendmodule\n'
(ROOT/'rtl/rv32_ifu_if_array.v').write_text(layout(s))
files = ['rtl/rv32_ifu_clk_cell.v', 'rtl/rv32_ifu_spram.v',
         'rtl/rv32_ifu_icache_tag_array.v', 'rtl/rv32_ifu_icache_data_array0.v',
         'rtl/rv32_ifu_icache_predecd_array0.v', 'rtl/rv32_ifu_icache_if.v',
         'rtl/rv32_ifu_region.v', 'rtl/rv32_ifu_pcgen.v', 'rtl/rv32_ifu_btb.v',
         'rtl/rv32_ifu_if_array.v', 'rtl/rv32_ifu_ifctrl.v', 'rtl/rv32_ifu_ifdp.v']
(ROOT/'rtl/if_stage_files.f').write_text('\n'.join(files)+'\n')
print('Generated IF grant wiring; standalone icache_top/BIU scheduler excluded')
