// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/build_top.py. Workbook v1.1/no-MMU boundary.
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
// [ICACHE 参数化] 与 rv32_ifu_icache_if.v 同套 define/公式; 默认 = 1 KiB/16 B 行。
`ifdef ICACHE_BYTES
  `define IC_BYTES_VAL `ICACHE_BYTES
`else
  `define IC_BYTES_VAL 1024
`endif
`ifdef ICACHE_LINE_BYTES
  `define IC_LINE_VAL `ICACHE_LINE_BYTES
`else
  `define IC_LINE_VAL 16
`endif

module rv32_ifu_top #(
  parameter REGION_COUNT = 1,
  parameter [REGION_COUNT*32-1:0] REGION_BASE = 0,
  parameter [REGION_COUNT*33-1:0] REGION_LIMIT = 0,
  parameter [REGION_COUNT*5-1:0] REGION_ATTR = 0
) (
  input  wire         forever_cpuclk,
  input  wire         cpurst_b,
  input  wire         cp0_yy_clk_en,
  input  wire         cp0_ifu_icg_en,
  input  wire         pad_yy_icg_scan_en,
  input  wire [ 31:0] cp0_ifu_rvbr,
  output wire         ifu_cp0_init_done,
  output wire         ifu_yy_xx_no_op,
  input  wire         cp0_ifu_bht_en,
  input  wire         cp0_ifu_btb_en,
  input  wire         cp0_ifu_ind_btb_en,
  input  wire         cp0_ifu_l0btb_en,
  input  wire         cp0_ifu_ras_en,
  input  wire         cp0_ifu_lbuf_en,
  input  wire         cp0_ifu_icache_en,
  input  wire         cp0_ifu_icache_pref_en,
  input  wire         cp0_ifu_iwpe,
  input  wire         cp0_ifu_nsfe,
  input  wire         cp0_ifu_insde,
  input  wire         cp0_ifu_no_op_req,
  input  wire [  1:0] cp0_yy_priv_mode,
  input  wire         cp0_ifu_maint_vld,
  output wire         ifu_cp0_maint_ready,
  input  wire [  1:0] cp0_ifu_maint_op,
  input  wire [ 31:0] cp0_ifu_maint_pa,
  input  wire [  7:0] cp0_ifu_maint_pred_mask,
  input  wire [ 31:0] cp0_ifu_maint_resume_pc,
  output wire         ifu_cp0_maint_done,
  input  wire         cp0_ifu_icache_read_req,
  output wire         ifu_cp0_icache_read_ready,
  input  wire [ 10:0] cp0_ifu_icache_read_index,
  input  wire         cp0_ifu_icache_read_way,
  input  wire [  1:0] cp0_ifu_icache_read_kind,
  output wire         ifu_cp0_icache_read_data_vld,
  input  wire         cp0_ifu_icache_read_data_ready,
  output wire [127:0] ifu_cp0_icache_read_data,
  output wire         ifu_idu_ib_inst0_vld,
  output wire [127:0] ifu_idu_ib_inst0_data,
  output wire [ 24:0] ifu_idu_ib_inst0_chk,
  output wire         ifu_idu_ib_inst1_vld,
  output wire [127:0] ifu_idu_ib_inst1_data,
  output wire [ 24:0] ifu_idu_ib_inst1_chk,
  output wire         ifu_idu_ib_inst2_vld,
  output wire [127:0] ifu_idu_ib_inst2_data,
  output wire [ 24:0] ifu_idu_ib_inst2_chk,
  output wire         ifu_idu_ib_pipedown_gateclk,
  output wire         ifu_idu_flush,
  input  wire [  1:0] idu_ifu_accept_num,
  input  wire [  1:0] iu_ifu_pcfifo_credit,
  input  wire [ 12:0] iu_ifu_pcfifo_alloc0_token,
  input  wire [ 12:0] iu_ifu_pcfifo_alloc1_token,
  output wire         ifu_iu_pcfifo_create0_en,
  output wire         ifu_iu_pcfifo_create0_gateclk_en,
  output wire [ 31:0] ifu_iu_pcfifo_create0_cur_pc,
  output wire [ 31:0] ifu_iu_pcfifo_create0_tar_pc,
  output wire [ 31:0] ifu_iu_pcfifo_create0_pred_npc,
  output wire [  2:0] ifu_iu_pcfifo_create0_cf_type,
  output wire         ifu_iu_pcfifo_create0_dst_vld,
  output wire         ifu_iu_pcfifo_create0_bht_pred,
  output wire [ 24:0] ifu_iu_pcfifo_create0_chk_idx,
  output wire         ifu_iu_pcfifo_create0_jmp_mispred,
  output wire         ifu_iu_pcfifo_create1_en,
  output wire         ifu_iu_pcfifo_create1_gateclk_en,
  output wire [ 31:0] ifu_iu_pcfifo_create1_cur_pc,
  output wire [ 31:0] ifu_iu_pcfifo_create1_tar_pc,
  output wire [ 31:0] ifu_iu_pcfifo_create1_pred_npc,
  output wire [  2:0] ifu_iu_pcfifo_create1_cf_type,
  output wire         ifu_iu_pcfifo_create1_dst_vld,
  output wire         ifu_iu_pcfifo_create1_bht_pred,
  output wire [ 24:0] ifu_iu_pcfifo_create1_chk_idx,
  output wire         ifu_iu_pcfifo_create1_jmp_mispred,
  output wire         ifu_iu_pcfifo_cancel_vld,
  output wire [ 12:0] ifu_iu_pcfifo_cancel_first_token,
  input  wire         iu_ifu_bht_check_vld,
  input  wire [ 12:0] iu_ifu_check_token,
  input  wire [ 31:0] iu_ifu_cur_pc,
  input  wire         iu_ifu_bht_condbr_taken,
  input  wire         iu_ifu_bht_pred,
  input  wire [ 24:0] iu_ifu_chk_idx,
  input  wire         iu_ifu_chgflw_vld,
  input  wire [ 31:0] iu_ifu_chgflw_pc,
  input  wire         iu_ifu_mispred_stall,
  input  wire         rtu_ifu_flush,
  input  wire         rtu_ifu_chgflw_vld,
  input  wire [ 31:0] rtu_ifu_chgflw_pc,
  input  wire         rtu_ifu_dbgon,
  input  wire         rtu_ifu_retire0_vld,
  input  wire [ 31:0] rtu_ifu_retire0_cur_pc,
  input  wire         rtu_ifu_retire0_condbr,
  input  wire         rtu_ifu_retire0_condbr_taken,
  input  wire         rtu_ifu_retire0_jmp,
  input  wire [  7:0] rtu_ifu_retire0_chk_idx,
  input  wire         rtu_ifu_retire0_load,
  input  wire         rtu_ifu_retire0_store,
  input  wire         rtu_ifu_retire0_no_spec_hit,
  input  wire         rtu_ifu_retire0_no_spec_miss,
  input  wire         rtu_ifu_retire0_no_spec_mispred,
  input  wire         rtu_ifu_retire1_vld,
  input  wire [ 31:0] rtu_ifu_retire1_cur_pc,
  input  wire         rtu_ifu_retire1_condbr,
  input  wire         rtu_ifu_retire1_condbr_taken,
  input  wire         rtu_ifu_retire1_jmp,
  input  wire [  7:0] rtu_ifu_retire1_chk_idx,
  input  wire         rtu_ifu_retire1_load,
  input  wire         rtu_ifu_retire1_store,
  input  wire         rtu_ifu_retire1_no_spec_hit,
  input  wire         rtu_ifu_retire1_no_spec_miss,
  input  wire         rtu_ifu_retire1_no_spec_mispred,
  input  wire         rtu_ifu_retire2_vld,
  input  wire [ 31:0] rtu_ifu_retire2_cur_pc,
  input  wire         rtu_ifu_retire2_condbr,
  input  wire         rtu_ifu_retire2_condbr_taken,
  input  wire         rtu_ifu_retire2_jmp,
  input  wire [  7:0] rtu_ifu_retire2_chk_idx,
  input  wire         rtu_ifu_retire2_load,
  input  wire         rtu_ifu_retire2_store,
  input  wire         rtu_ifu_retire2_no_spec_hit,
  input  wire         rtu_ifu_retire2_no_spec_miss,
  input  wire         rtu_ifu_retire2_no_spec_mispred,
  input  wire         rtu_ifu_retire0_pcall,
  input  wire         rtu_ifu_retire0_preturn,
  input  wire [ 31:0] rtu_ifu_retire0_inc_pc,
  input  wire [ 31:0] rtu_ifu_retire0_next_pc,
  input  wire         rtu_ifu_retire0_mispred,
  input  wire         rtu_ifu_retire0_jmp_mispred,
  output wire         ifu_biu_rd_req,
  output wire         ifu_biu_rd_req_gate,
  output wire [ 31:0] ifu_biu_rd_addr,
  output wire         ifu_biu_rd_id,
  output wire [  1:0] ifu_biu_rd_len,
  output wire [  2:0] ifu_biu_rd_size,
  output wire [  1:0] ifu_biu_rd_burst,
  output wire [  3:0] ifu_biu_rd_cache,
  output wire [  2:0] ifu_biu_rd_prot,
  output wire [  1:0] ifu_biu_rd_domain,
  output wire [  3:0] ifu_biu_rd_snoop,
  output wire [  1:0] ifu_biu_rd_user,
  input  wire         biu_ifu_rd_grnt,
  input  wire         biu_ifu_rd_data_vld,
  input  wire [127:0] biu_ifu_rd_data,
  input  wire         biu_ifu_rd_id,
  input  wire         biu_ifu_rd_last,
  input  wire [  1:0] biu_ifu_rd_resp,
  output wire         ifu_biu_r_ready,
  input  wire         lsu_ifu_icache_inv_vld,
  output wire         ifu_lsu_icache_inv_ready,
  input  wire         lsu_ifu_icache_inv_all,
  input  wire [ 31:0] lsu_ifu_icache_inv_pa,
  input  wire [ 31:0] lsu_ifu_icache_inv_resume_pc,
  output wire         ifu_lsu_icache_inv_done,
  input  wire         had_rtu_xx_jdbreq,
  input  wire         had_ifu_pcload,
  input  wire [ 31:0] had_ifu_pc,
  input  wire         had_ifu_ir_vld,
  input  wire [ 31:0] had_ifu_ir,
  output wire         ifu_had_cmd_ready,
  input  wire [ 31:0] had_yy_xx_bkpta_base,
  input  wire [ 31:0] had_yy_xx_bkpta_mask,
  input  wire         had_ifu_bkpta_en,
  input  wire [ 31:0] had_yy_xx_bkptb_base,
  input  wire [ 31:0] had_yy_xx_bkptb_mask,
  input  wire         had_ifu_bkptb_en,
  output wire [ 31:0] ifu_had_fetch_pc,
  output wire         ifu_had_no_inst,
  output wire         ifu_had_reset_on,
  output wire         ifu_had_quiescent,
  input  wire         hpcp_ifu_cnt_en,
  output wire         ifu_hpcp_btb_inst,
  output wire         ifu_hpcp_btb_mispred,
  output wire         ifu_hpcp_frontend_stall,
  output wire         ifu_hpcp_icache_access,
  output wire         ifu_hpcp_icache_miss,
  output wire         ifu_hpcp_way_reissue,
  output wire         ifu_hpcp_ipb_launch,
  output wire         ifu_hpcp_ipb_demand_hit,
  output wire         ifu_hpcp_lbuf_active,
  output wire         ifu_hpcp_pcfifo_stall,
  output wire         ifu_hpcp_bht_update_drop,
  output wire         ifu_hpcp_ras_miss,
  output wire         ifu_hpcp_ind_btb_miss,
  output wire         ifu_hpcp_bju_mispred,
  output wire [  1:0] ifu_hpcp_id_accept_num
);
  // [ICACHE 参数化] tag 穿线宽度跟着几何走。写死 17/18 位时只有 TAG_BITS==17 的
  // 几何对得上, 其余几何的 tag 会在这里被静默截断 ⇒ ifdp 三片比较的 part2 恒假
  // ⇒ 永不命中(功能仍正确, 只是慢), 很容易被误读成"容量太小"。
  localparam IC_BYTES  = `IC_BYTES_VAL;
  localparam IC_LINE   = `IC_LINE_VAL;
  localparam IC_SETS   = IC_BYTES/(2*IC_LINE);
  localparam SET_BITS  = $clog2(IC_SETS);
  localparam LINE_BITS = $clog2(IC_LINE);
  localparam TAG_BITS  = 32 - SET_BITS - LINE_BITS;
  localparam TAG_WIDTH = 1 + TAG_BITS;

  reg          fault_stop_q;
  wire         debug_pcgen_pcload;
  wire [ 31:0] debug_pcgen_pc;
  wire         entry_load;
  wire [ 31:0] entry_pc;
  wire         vector_pcgen_reset_on;
  wire         reissue;
  wire [ 31:0] demand_pc;
  wire [  1:0] reissue_way;
  wire         ip_redirect;
  wire [ 31:0] ip_redirect_pc;
  wire         l0_invalidate;
  wire         ifctrl_pcgen_chgflw_vld;
  wire         ifctrl_pcgen_chgflw_no_stall_mask;
  wire [ 31:0] ifctrl_pcgen_pcload_pc;
  wire [  1:0] ifctrl_pcgen_way_pred;
  wire         ifctrl_pcgen_reissue_pcload;
  wire         ifctrl_pcgen_stall;
  wire         ifctrl_pcgen_stall_short;
  wire         maint_resume;
  wire [ 31:0] pcgen_ifctrl_pc;
  wire [ 31:0] pcgen_ifdp_pc;
  wire [ 31:0] pcgen_ifdp_inc_pc;
  wire [  1:0] pcgen_ifctrl_way_pred;
  wire [  1:0] pcgen_ifdp_way_pred;
  wire         pcgen_ifctrl_way_pred_stall;
  wire         pcgen_ifctrl_reissue;
  wire         pcgen_ifctrl_cancel;
  wire         pcgen_ifctrl_pipe_cancel;
  wire         pcgen_ipctrl_cancel;
  wire         pcgen_ipctrl_pipe_cancel;
  wire         pcgen_ibctrl_cancel;
  wire         pcgen_ibctrl_ibuf_flush;
  wire         pcgen_ibctrl_lbuf_flush;
  wire         pcgen_ibctrl_bju_chgflw;
  wire         pcgen_addrgen_cancel;
  wire         pcgen_l1_refill_chgflw;
  wire         pcgen_ipb_chgflw;
  wire [ 31:0] pcgen_icache_if_index;
  wire [  1:0] pcgen_icache_if_way_pred;
  wire         pcgen_icache_if_chgflw;
  wire         pcgen_icache_if_chgflw_short;
  wire         pcgen_icache_if_chgflw_bank0;
  wire         pcgen_icache_if_chgflw_bank1;
  wire         pcgen_icache_if_chgflw_bank2;
  wire         pcgen_icache_if_chgflw_bank3;
  wire         pcgen_icache_if_seq_data_req;
  wire         pcgen_icache_if_seq_data_req_short;
  wire         pcgen_icache_if_seq_tag_req;
  wire         pcgen_icache_if_gateclk_en;
  wire         pcgen_bht_chgflw;
  wire         pcgen_bht_chgflw_short;
  wire [  6:0] pcgen_bht_ifpc;
  wire [  9:0] pcgen_bht_pcindex;
  wire         pcgen_bht_seq_read;
  wire         pcgen_btb_chgflw;
  wire         pcgen_btb_chgflw_short;
  wire         pcgen_btb_chgflw_higher_than_addrgen;
  wire         pcgen_btb_chgflw_higher_than_ip;
  wire         pcgen_btb_chgflw_higher_than_if;
  wire [  9:0] pcgen_btb_index;
  wire         pcgen_btb_stall;
  wire         pcgen_btb_stall_short;
  wire         pcgen_l0_btb_chgflw_mask;
  wire         pcgen_l0_btb_chgflw_vld;
  wire [ 31:0] pcgen_l0_btb_chgflw_pc;
  wire [ 31:0] pcgen_l0_btb_if_pc;
  wire [ 16:0] pcgen_sfp_pc;
  wire         pcgen_debug_chgflw;
  wire [ 31:0] pcgen_debug_pcbus;
  wire         stop_fetch;
  wire         fetch_initialized;
  wire         maint_busy;
  wire         frontend_redirect;
  wire         fault_accept;
  wire [  4:0] region_ifctrl_attr;
  wire         ipctrl_ifctrl_stall;
  wire         btb_lookup_ready;
  wire         maintenance_array_req;
  wire         refill_array_req;
  wire         ipb_array_req;
  wire [  3:0] ifctrl_array_grant;
  wire         ifctrl_maintenance_grant;
  wire         ifctrl_refill_grant;
  wire         ifctrl_ipb_grant;
  wire         ifctrl_array_fetch;
  wire [ 31:0] ifctrl_array_pc;
  wire [  1:0] ifctrl_array_way;
  wire         refill_active_block;
  wire         l1_refill_ifctrl_live;
  wire         l1_refill_ifctrl_vld;
  wire [ 31:0] l1_refill_ifctrl_pc;
  wire         ifctrl_l1_refill_ready;
  wire         ifctrl_l1_refill_cancel;
  wire         ifdp_ifctrl_fault;
  wire         ifdp_ifctrl_l0_vld;
  wire [ 31:0] ifdp_ifctrl_l0_target;
  wire [  1:0] ifdp_ifctrl_l0_way;
  wire         ifctrl_ifdp_issue;
  wire [ 31:0] ifctrl_ifdp_issue_pc;
  wire [  1:0] ifctrl_ifdp_issue_way;
  wire [  1:0] ifctrl_ifdp_issue_kind;
  wire         ifctrl_ifdp_hold;
  wire         ifctrl_ifdp_held;
  wire         ifctrl_ifdp_pipedown;
  wire         ifctrl_ifdp_l0_accept;
  wire         ifctrl_ipctrl_vld;
  wire         ifctrl_ipctrl_if_pcload;
  wire         ifctrl_btb_lookup_vld;
  wire [ 31:0] ifctrl_btb_lookup_pc;
  wire         ifctrl_bht_read;
  wire [  9:0] ifctrl_bht_pcindex;
  wire         ifctrl_bht_pipedown;
  wire         ifctrl_bht_stall;
  wire         ifctrl_l0_btb_lookup_vld;
  wire         ifctrl_l0_btb_accept;
  wire         ifctrl_debug_if_vld;
  wire         ifctrl_debug_if_stall;
  wire         ifctrl_idle;
  wire         if_frontend_stall;
  wire [  4:0] region_ifdp_attr;
  wire         l1_refill_ifdp_acc_err;
  wire [127:0] l1_refill_ifdp_inst_data;
  wire [ 31:0] l1_refill_ifdp_precode;
  wire         btb_if_vld;
  wire [ 31:0] btb_if_pc;
  wire [  3:0] btb_if_hit;
  wire [127:0] btb_if_target;
  wire [  7:0] btb_if_way_hint;
  wire         l0_hit;
  wire         bp_recovery_stall;
  wire [  3:0] l0_hit_index;
  wire [  1:0] l0_hit_slot;
  wire [  1:0] l0_way_hint;
  wire [  2:0] l0_hit_type;
  wire [ 31:0] l0_target;
  wire [ 31:0] ifdp_l0_btb_pc;
  wire [  3:0] sfp_no_spec;
  wire [ 31:0] ifdp_bht_pc;
  wire [ 31:0] ifdp_ipdp_vpc;
  wire [  4:0] ifdp_ipdp_attr;
  wire [  1:0] ifdp_ipdp_priv_mode;
  wire [  1:0] ifdp_ipdp_way_pred;
  wire         ifdp_ipdp_refill_on;
  wire         ifdp_ipdp_cache_bypass;
  wire         ifdp_ipdp_fifo;
  wire         ifdp_ipdp_fault;
  wire [  3:0] ifdp_ipdp_cause;
  wire [  3:0] ifdp_ipdp_word_mask;
  wire [  3:0] ifdp_ipdp_bkpta;
  wire [  3:0] ifdp_ipdp_bkptb;
  wire [127:0] ifdp_ipdp_inst_data0;
  wire [127:0] ifdp_ipdp_inst_data1;
  wire [ 31:0] ifdp_ipdp_precode0;
  wire [ 31:0] ifdp_ipdp_precode1;
  wire [  2:0] ifdp_ipdp_tag_match0;
  wire [  2:0] ifdp_ipdp_tag_match1;
  wire         ifdp_ipdp_btb_vld;
  wire [  3:0] ifdp_ipdp_btb_hit;
  wire [127:0] ifdp_ipdp_btb_target;
  wire [  7:0] ifdp_ipdp_btb_way;
  wire         ifdp_ipdp_l0_hit;
  wire [  3:0] ifdp_ipdp_l0_index;
  wire [  1:0] ifdp_ipdp_l0_slot;
  wire [  2:0] ifdp_ipdp_l0_type;
  wire [ 31:0] ifdp_ipdp_l0_target;
  wire [  1:0] ifdp_ipdp_l0_way;
  wire [  3:0] ifdp_ipdp_no_spec;
  wire [ 31:0] ifdp_ipdp_seq_pc;
  wire [127:0] ifdp_ipdp_word_pc;
  wire [ 15:0] ifdp_ipdp_l0_entry_mask;
  wire [  3:0] ifdp_ipdp_l0_btb_target_match;
  wire         l1_refill_icache_if_install;
  wire [ 31:0] ifctrl_icache_if_index;
  wire         ifctrl_icache_if_inv_fifo;
  wire         ifctrl_icache_if_inv_on;
  wire         ifctrl_icache_if_read_req_data0;
  wire         ifctrl_icache_if_read_req_data1;
  wire [ 31:0] ifctrl_icache_if_read_req_index;
  wire         ifctrl_icache_if_read_req_tag;
  wire         ifctrl_icache_if_reset_req;
  wire         ifctrl_icache_if_tag_req;
  wire [  2:0] ifctrl_icache_if_tag_wen;
  wire         miss_event;
  wire [ 31:0] ipb_icache_if_index;
  wire         ipb_icache_if_req;
  wire         ipb_icache_if_req_for_gateclk;
  wire         l1_refill_icache_if_fifo;
  wire         l1_refill_icache_if_first;
  wire [ 31:0] l1_refill_icache_if_index;
  wire [127:0] l1_refill_icache_if_inst_data;
  wire         l1_refill_icache_if_last;
  wire [ 31:0] l1_refill_icache_if_pre_code;
  wire [TAG_BITS-1:0] l1_refill_icache_if_ptag;
  wire         l1_refill_icache_if_wr;
  wire [127:0] icache_if_ifctrl_inst_data0;
  wire [127:0] icache_if_ifctrl_inst_data1;
  wire [TAG_WIDTH-1:0] icache_if_ifctrl_tag_data0;
  wire [TAG_WIDTH-1:0] icache_if_ifctrl_tag_data1;
  wire         raw_cache_fifo;
  wire [127:0] raw_cache_inst_data0;
  wire [127:0] raw_cache_inst_data1;
  wire [ 31:0] raw_cache_precode0;
  wire [ 31:0] raw_cache_precode1;
  wire [TAG_WIDTH-1:0] raw_cache_tag_data0;
  wire [TAG_WIDTH-1:0] raw_cache_tag_data1;
  wire [TAG_WIDTH-1:0] icache_if_ipb_tag_data0;
  wire [TAG_WIDTH-1:0] icache_if_ipb_tag_data1;
  wire [ 31:0] pipe_ifdp_ipdp_vpc;
  wire [127:0] pipe_ifdp_ipdp_inst_data0;
  wire [127:0] pipe_ifdp_ipdp_inst_data1;
  wire [  2:0] pipe_ifdp_ipdp_tag_match0;
  wire [  2:0] pipe_ifdp_ipdp_tag_match1;
  wire [  1:0] pipe_ifdp_ipdp_way_pred;
  wire         pipe_ifdp_ipdp_fault;
  wire [  3:0] pipe_ifdp_ipdp_cause;
  wire [  3:0] pipe_ifdp_ipdp_bkpta;
  wire [  3:0] pipe_ifdp_ipdp_bkptb;
  wire [  3:0] pipe_ifdp_ipdp_no_spec;
  wire         pipe_bht_pred;
  wire [ 24:0] bht_chk_idx;
  wire [  3:0] pipe_ifdp_ipdp_btb_hit;
  wire [127:0] pipe_ifdp_ipdp_btb_target;
  wire [  7:0] pipe_ifdp_ipdp_btb_way;
  wire         cancel_ip;
  wire         pipe_ip_valid;
  wire         pipe_ip_load;
  wire [  3:0] pipe_ifdp_ipdp_word_mask;
  wire         pipe_ifdp_ipdp_cache_bypass;
  wire         pipe_ifdp_ipdp_fifo;
  wire         pipe_demand_ready;
  wire         pipe_ifdp_ipdp_l0_hit;
  wire [  1:0] pipe_ifdp_ipdp_l0_slot;
  wire [  2:0] pipe_ifdp_ipdp_l0_type;
  wire [ 31:0] pipe_ifdp_ipdp_l0_target;
  wire [ 15:0] pipe_ifdp_ipdp_l0_entry_mask;
  wire         demand_valid;
  wire         demand_way;
  wire         bht_event;
  wire         bht_taken;
  wire         bht_more;
  wire [ 15:0] l0_invalidate_mask;
  wire         way_event;
  wire         ib_accept;
  wire [  2:0] consume_count;
  wire         ras_top_valid;
  wire [ 31:0] ras_l0_btb_pc;
  wire [767:0] corrected_packet;
  wire         global_flush;
  wire         ind_result_vld;
  wire         ind_target_valid;
  wire [ 31:0] ind_target;
  wire         training_ready;
  wire         ind_query;
  wire         ib_redirect;
  wire [ 31:0] ib_redirect_pc;
  wire [ 21:0] ib_recover_ghr;
  wire         ras_push;
  wire         ras_pop;
  wire         jump_accept;
  wire         return_accept;
  wire         ind_miss_event;
  wire [ 31:0] push_pc;
  wire [ 31:0] jump_target;
  wire         train_valid;
  wire         train_taken;
  wire         train_cnt_lo;
  wire         train_ras;
  wire         btb_used;
  wire [ 31:0] train_pc;
  wire [ 31:0] train_target;
  wire [  2:0] train_type;
  wire [  1:0] train_way;
  wire [  7:0] ind_query_ghr;
  wire         ib_empty;
  wire         pcfifo_wait;
  wire         recovery_wait;
  wire [  1:0] create_en;
  wire [ 63:0] create_pc;
  wire [ 63:0] create_target;
  wire [ 63:0] create_npc;
  wire [  5:0] create_type;
  wire [  1:0] create_dst;
  wire [  1:0] create_pred;
  wire [  1:0] create_unknown;
  wire [ 49:0] create_chk;
  wire [  1:0] out_count;
  wire [383:0] out_packet;
  wire [ 74:0] out_chk;
  wire [  5:0] occupancy;
  wire         ibuf_empty;
  wire         memory_cancel;
  wire         maint_invalidate;
  wire         memory_demand_valid;
  wire         memory_demand_ready;
  wire         demand_allocate;
  wire         refill_active_raw;
  wire         refill_idle;
  wire         protocol_error;
  wire [ 31:0] prefetch_region_pc;
  wire [  4:0] prefetch_region_attr;
  wire         prefetch_idle;
  wire         ipb_launch;
  wire         ipb_demand_hit;
  wire         bus_idle;
  wire         backend_redirect;
  wire [ 31:0] backend_pc;
  wire         memory_idle;
  wire         bp_init_done;
  wire         bp_maint_ready;
  wire         bp_maint_done;
  wire         bp_maint_vld;
  wire [  4:0] bp_maint_mask;
  wire         cache_init_done;
  wire         maint_flush;
  wire [ 31:0] maint_resume_pc;
  wire         clear_sfp;
  wire         software_idle;
  wire         vector_pcgen_pcload;
  wire [ 31:0] vector_pcgen_pc;
  wire         inject_valid;
  wire         inject_query;
  wire         inject_pipedown;
  wire         debug_busy;
  wire         debug_restore;
  wire [ 31:0] inject_pc;
  wire [ 31:0] inject_inst;
  wire         debug_inject_accept;
  wire [ 31:0] bp_if_pc;
  wire [ 31:0] bp_query_pc;
  wire         bht_train_drop;
  wire [ 31:0] bht_train_drop_count;
  wire         bp_pipedown;
  wire         bp_read_stall;
  wire         bp_read;
  wire         predictor_commit_restore;
  wire [ 31:0] bht_ipdp_pre_array_data_ntake;
  wire [ 31:0] bht_ipdp_pre_array_data_taken;
  wire [ 15:0] bht_ipdp_pre_offset_onehot;
  wire [  1:0] bht_ipdp_sel_array_result;
  wire [ 21:0] bht_ipdp_vghr;
  wire [ 31:0] bht_lbuf_pre_ntaken_result;
  wire [ 31:0] bht_lbuf_pre_taken_result;
  wire [ 21:0] bht_lbuf_vghr;
  wire         ras_ipdp_data_vld;
  wire [ 31:0] ras_ipdp_pc;
  wire [ 31:0] ras_l0_btb_push_pc;
  wire         ras_l0_btb_ras_push;
  wire [ 34:0] ind_btb_ibctrl_dout;
  wire [  1:0] ind_btb_ibctrl_priv_mode;
  wire         btb_result_vld;
  wire [  3:0] btb_hit;
  wire [127:0] btb_target;
  wire [  7:0] btb_way_hint;
  wire         btb_update_ready;
  wire         bht_pred;
  wire [  3:0] sfp_mask;
  wire [  2:0] sfp_retire_valid;
  wire [  2:0] sfp_retire_load;
  wire [  2:0] sfp_retire_store;
  wire [  2:0] sfp_retire_hit;
  wire [  2:0] sfp_retire_miss;
  wire [  2:0] sfp_retire_mispred;
  wire [ 95:0] sfp_retire_pc;
  wire         fault_stop_nxt;
  wire         fault_stop_en;
  assign backend_redirect = rtu_ifu_chgflw_vld || iu_ifu_chgflw_vld;
  assign backend_pc = rtu_ifu_chgflw_vld ? rtu_ifu_chgflw_pc : iu_ifu_chgflw_pc;
  assign entry_load = vector_pcgen_pcload || maint_resume;
  assign entry_pc = maint_resume ? maint_resume_pc : vector_pcgen_pc;
  assign global_flush = backend_redirect || maint_flush || pcgen_ibctrl_ibuf_flush;
  assign predictor_commit_restore = rtu_ifu_flush || debug_restore;
  assign frontend_redirect = global_flush || maint_resume || ib_redirect || ip_redirect || reissue;
  assign cancel_ip = global_flush || ib_redirect;
  assign fetch_initialized = ifu_cp0_init_done && !vector_pcgen_reset_on;
  assign stop_fetch = cp0_ifu_no_op_req || fault_stop_q;
  assign refill_active_block = refill_active_raw || miss_event;
  assign memory_cancel = global_flush || maint_resume || ib_redirect || ip_redirect || way_event;
  assign memory_demand_valid = demand_valid && !cp0_ifu_no_op_req;
  assign pipe_demand_ready = memory_demand_ready && !cp0_ifu_no_op_req;
  assign demand_allocate = cp0_ifu_icache_en && ifdp_ipdp_attr[3];
  assign memory_idle = refill_idle && prefetch_idle && bus_idle;
  assign ifu_cp0_init_done = cache_init_done && bp_init_done;
  assign ifu_idu_flush = global_flush;
  assign ifu_yy_xx_no_op = ifu_cp0_init_done && memory_idle && !maint_busy && software_idle;
  assign ifu_had_no_inst = out_count == 0;
  assign ifu_had_reset_on = vector_pcgen_reset_on;
  assign ifu_had_quiescent = ifu_yy_xx_no_op && ifctrl_idle && ib_empty && ibuf_empty &&
    !debug_busy;
  assign pipe_ip_valid = inject_valid || ifctrl_ipctrl_vld;
  assign pipe_ip_load = ifctrl_ifdp_pipedown || inject_pipedown;
  assign pipe_bht_pred = bht_pred;
  assign debug_inject_accept = inject_valid && !ipctrl_ifctrl_stall;
  assign bp_pipedown = ifctrl_ifdp_pipedown || (bht_event && bht_more) || inject_pipedown;
  assign bp_read = ifctrl_bht_read || inject_query;
  assign bp_read_stall = !bp_read;
  assign bp_if_pc = rtu_ifu_dbgon ? inject_pc : ifdp_bht_pc;
  assign bp_query_pc = rtu_ifu_dbgon ? inject_pc : ifctrl_ifdp_issue_pc;
  assign ifu_iu_pcfifo_cancel_vld = 1'b0;
  assign ifu_iu_pcfifo_cancel_first_token = 13'b0;
  assign ifu_idu_ib_pipedown_gateclk = out_count != 0;
  assign sfp_mask = 4'b1111 << ifdp_l0_btb_pc[3:2];
  assign fault_stop_nxt = !global_flush && !ib_redirect && (fault_stop_q || fault_accept);
  assign fault_stop_en = 1'b1;
  assign training_ready = !cp0_ifu_btb_en || btb_update_ready;

  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_fault_stop
    if (!cpurst_b) fault_stop_q <= 1'b0;
    else if (fault_stop_en) fault_stop_q <= fault_stop_nxt;
  end
  assign pipe_ifdp_ipdp_vpc = inject_valid ? inject_pc : ifdp_ipdp_vpc;
  assign pipe_ifdp_ipdp_inst_data0 = inject_valid ?
    ({96'b0, inject_inst} << ({inject_pc[3:2], 5'b0})) : ifdp_ipdp_inst_data0;
  assign pipe_ifdp_ipdp_inst_data1 = inject_valid ? 128'b0 : ifdp_ipdp_inst_data1;
  assign pipe_ifdp_ipdp_tag_match0 = inject_valid ? 3'b111 : ifdp_ipdp_tag_match0;
  assign pipe_ifdp_ipdp_tag_match1 = inject_valid ? 3'b0 : ifdp_ipdp_tag_match1;
  assign pipe_ifdp_ipdp_way_pred = inject_valid ? 2'b01 : ifdp_ipdp_way_pred;
  assign pipe_ifdp_ipdp_fault = inject_valid ? (|inject_pc[1:0]) : ifdp_ipdp_fault;
  assign pipe_ifdp_ipdp_cause = inject_valid ? 4'b0 : ifdp_ipdp_cause;
  assign pipe_ifdp_ipdp_bkpta = inject_valid ? 0 : ifdp_ipdp_bkpta;
  assign pipe_ifdp_ipdp_bkptb = inject_valid ? 0 : ifdp_ipdp_bkptb;
  assign pipe_ifdp_ipdp_no_spec = inject_valid ? 0 : ifdp_ipdp_no_spec;
  assign pipe_ifdp_ipdp_btb_hit = inject_valid ? 0 : ifdp_ipdp_btb_hit;
  assign pipe_ifdp_ipdp_btb_target = inject_valid ? 0 : ifdp_ipdp_btb_target;
  assign pipe_ifdp_ipdp_btb_way = inject_valid ? 0 : ifdp_ipdp_btb_way;
  assign pipe_ifdp_ipdp_word_mask = inject_valid ? 4'b0001 << inject_pc[3:2] : ifdp_ipdp_word_mask;
  assign pipe_ifdp_ipdp_cache_bypass = inject_valid ? 0 : ifdp_ipdp_cache_bypass;
  assign pipe_ifdp_ipdp_fifo = inject_valid ? 0 : ifdp_ipdp_fifo;
  assign pipe_ifdp_ipdp_l0_hit = inject_valid ? 0 : ifdp_ipdp_l0_hit;
  assign pipe_ifdp_ipdp_l0_slot = inject_valid ? 0 : ifdp_ipdp_l0_slot;
  assign pipe_ifdp_ipdp_l0_type = inject_valid ? 0 : ifdp_ipdp_l0_type;
  assign pipe_ifdp_ipdp_l0_target = inject_valid ? 0 : ifdp_ipdp_l0_target;
  assign pipe_ifdp_ipdp_l0_entry_mask = inject_valid ? 0 : ifdp_ipdp_l0_entry_mask;
  assign sfp_retire_valid = {rtu_ifu_retire2_vld, rtu_ifu_retire1_vld, rtu_ifu_retire0_vld};
  assign sfp_retire_load = {rtu_ifu_retire2_load, rtu_ifu_retire1_load, rtu_ifu_retire0_load};
  assign sfp_retire_store = {rtu_ifu_retire2_store, rtu_ifu_retire1_store, rtu_ifu_retire0_store};
  assign sfp_retire_hit = {
    rtu_ifu_retire2_no_spec_hit, rtu_ifu_retire1_no_spec_hit, rtu_ifu_retire0_no_spec_hit
  };
  assign sfp_retire_miss = {
    rtu_ifu_retire2_no_spec_miss, rtu_ifu_retire1_no_spec_miss, rtu_ifu_retire0_no_spec_miss
  };
  assign sfp_retire_mispred = {
    rtu_ifu_retire2_no_spec_mispred,
    rtu_ifu_retire1_no_spec_mispred,
    rtu_ifu_retire0_no_spec_mispred
  };
  assign sfp_retire_pc = {rtu_ifu_retire2_cur_pc, rtu_ifu_retire1_cur_pc, rtu_ifu_retire0_cur_pc};
  assign ifu_idu_ib_inst0_vld = out_count > 0;
  assign ifu_idu_ib_inst0_data = out_packet[0+:128];
  assign ifu_idu_ib_inst0_chk = out_chk[0+:25];
  assign ifu_idu_ib_inst1_vld = out_count > 1;
  assign ifu_idu_ib_inst1_data = out_packet[128+:128];
  assign ifu_idu_ib_inst1_chk = out_chk[25+:25];
  assign ifu_idu_ib_inst2_vld = out_count > 2;
  assign ifu_idu_ib_inst2_data = out_packet[256+:128];
  assign ifu_idu_ib_inst2_chk = out_chk[50+:25];
  assign ifu_iu_pcfifo_create0_en = create_en[0];
  assign ifu_iu_pcfifo_create0_gateclk_en = create_en[0];
  assign ifu_iu_pcfifo_create0_cur_pc = create_pc[0+:32];
  assign ifu_iu_pcfifo_create0_tar_pc = create_target[0+:32];
  assign ifu_iu_pcfifo_create0_pred_npc = create_npc[0+:32];
  assign ifu_iu_pcfifo_create0_cf_type = create_type[0+:3];
  assign ifu_iu_pcfifo_create0_dst_vld = create_dst[0];
  assign ifu_iu_pcfifo_create0_bht_pred = create_pred[0];
  assign ifu_iu_pcfifo_create0_chk_idx = create_chk[0+:25];
  assign ifu_iu_pcfifo_create0_jmp_mispred = create_unknown[0];
  assign ifu_iu_pcfifo_create1_en = create_en[1];
  assign ifu_iu_pcfifo_create1_gateclk_en = create_en[1];
  assign ifu_iu_pcfifo_create1_cur_pc = create_pc[32+:32];
  assign ifu_iu_pcfifo_create1_tar_pc = create_target[32+:32];
  assign ifu_iu_pcfifo_create1_pred_npc = create_npc[32+:32];
  assign ifu_iu_pcfifo_create1_cf_type = create_type[3+:3];
  assign ifu_iu_pcfifo_create1_dst_vld = create_dst[1];
  assign ifu_iu_pcfifo_create1_bht_pred = create_pred[1];
  assign ifu_iu_pcfifo_create1_chk_idx = create_chk[25+:25];
  assign ifu_iu_pcfifo_create1_jmp_mispred = create_unknown[1];
  assign ifu_hpcp_btb_inst = hpcp_ifu_cnt_en && (btb_used);
  assign ifu_hpcp_btb_mispred = hpcp_ifu_cnt_en && (ib_redirect || l0_invalidate);
  assign ifu_hpcp_frontend_stall = hpcp_ifu_cnt_en &&
    (if_frontend_stall || pcfifo_wait || recovery_wait);
  assign ifu_hpcp_way_reissue = hpcp_ifu_cnt_en && (way_event);
  assign ifu_hpcp_ipb_launch = hpcp_ifu_cnt_en && (ipb_launch);
  assign ifu_hpcp_ipb_demand_hit = hpcp_ifu_cnt_en && (ipb_demand_hit);
  assign ifu_hpcp_lbuf_active = 1'b0;
  assign ifu_hpcp_pcfifo_stall = hpcp_ifu_cnt_en && (pcfifo_wait);
  assign ifu_hpcp_bht_update_drop = hpcp_ifu_cnt_en && (bht_train_drop);
  assign ifu_hpcp_ras_miss = hpcp_ifu_cnt_en && (return_accept && !ras_top_valid);
  assign ifu_hpcp_ind_btb_miss = hpcp_ifu_cnt_en && (ind_miss_event);
  assign ifu_hpcp_bju_mispred = hpcp_ifu_cnt_en && (iu_ifu_chgflw_vld && !rtu_ifu_chgflw_vld);
  assign ifu_hpcp_id_accept_num = (hpcp_ifu_cnt_en && !global_flush) ? idu_ifu_accept_num : 2'b0;
  rv32_ifu_pcgen u_pcgen (
    .forever_cpuclk                      (forever_cpuclk),
    .cpurst_b                            (cpurst_b),
    .cp0_yy_clk_en                       (cp0_yy_clk_en),
    .cp0_ifu_iwpe                        (cp0_ifu_iwpe),
    .debug_pcgen_pcload                  (debug_pcgen_pcload),
    .debug_pcgen_pc                      (debug_pcgen_pc),
    .rtu_ifu_dbgon                       (rtu_ifu_dbgon),
    .vector_pcgen_pcload                 (entry_load),
    .vector_pcgen_pc                     (entry_pc),
    .vector_pcgen_reset_on               (vector_pcgen_reset_on),
    .rtu_ifu_chgflw_vld                  (rtu_ifu_chgflw_vld),
    .rtu_ifu_chgflw_pc                   (rtu_ifu_chgflw_pc),
    .rtu_ifu_flush                       (rtu_ifu_flush),
    .iu_ifu_chgflw_vld                   (iu_ifu_chgflw_vld),
    .iu_ifu_chgflw_pc                    (iu_ifu_chgflw_pc),
    .addrgen_pcgen_pcload                (1'b0),
    .addrgen_pcgen_pc                    (32'b0),
    .ibctrl_pcgen_pcload                 (ib_redirect),
    .ibctrl_pcgen_pcload_vld             (ib_redirect),
    .ibctrl_pcgen_pc                     (ib_redirect_pc),
    .ibctrl_pcgen_way_pred               (2'b11),
    .ibctrl_pcgen_ip_stall               (1'b0),
    .ipctrl_pcgen_reissue_pcload         (reissue),
    .ipctrl_pcgen_reissue_pc             (demand_pc),
    .ipctrl_pcgen_reissue_way_pred       (reissue_way),
    .ipctrl_pcgen_chgflw_pcload          (ip_redirect),
    .ipctrl_pcgen_chgflw_pc              (ip_redirect_pc),
    .ipctrl_pcgen_chgflw_way_pred        (2'b11),
    .ipctrl_pcgen_branch_taken           (ip_redirect),
    .ipctrl_pcgen_branch_mistaken        (l0_invalidate),
    .ipctrl_pcgen_taken_pc               (ip_redirect_pc),
    .ipctrl_pcgen_chk_err_reissue        (reissue),
    .ipctrl_pcgen_if_stall               (1'b0),
    .ipctrl_pcgen_inner_way0             (1'b0),
    .ipctrl_pcgen_inner_way1             (1'b0),
    .ipctrl_pcgen_inner_way_pred         (2'b11),
    .ifctrl_pcgen_chgflw_vld             (ifctrl_pcgen_chgflw_vld),
    .ifctrl_pcgen_chgflw_no_stall_mask   (ifctrl_pcgen_chgflw_no_stall_mask),
    .ifctrl_pcgen_pcload_pc              (ifctrl_pcgen_pcload_pc),
    .ifctrl_pcgen_way_pred               (ifctrl_pcgen_way_pred),
    .ifctrl_pcgen_reissue_pcload         (ifctrl_pcgen_reissue_pcload),
    .ifctrl_pcgen_stall                  (ifctrl_pcgen_stall),
    .ifctrl_pcgen_stall_short            (ifctrl_pcgen_stall_short),
    .ifctrl_pcgen_ins_icache_inv_done    (maint_resume),
    .lbuf_pcgen_active                   (1'b0),
    .lbuf_pcgen_vld_mask                 (1'b0),
    .pcgen_ifctrl_pc                     (pcgen_ifctrl_pc),
    .pcgen_ifdp_pc                       (pcgen_ifdp_pc),
    .pcgen_ifdp_inc_pc                   (pcgen_ifdp_inc_pc),
    .pcgen_ifctrl_way_pred               (pcgen_ifctrl_way_pred),
    .pcgen_ifdp_way_pred                 (pcgen_ifdp_way_pred),
    .pcgen_ifctrl_way_pred_stall         (pcgen_ifctrl_way_pred_stall),
    .pcgen_ifctrl_reissue                (pcgen_ifctrl_reissue),
    .pcgen_ifctrl_cancel                 (pcgen_ifctrl_cancel),
    .pcgen_ifctrl_pipe_cancel            (pcgen_ifctrl_pipe_cancel),
    .pcgen_ipctrl_cancel                 (pcgen_ipctrl_cancel),
    .pcgen_ipctrl_pipe_cancel            (pcgen_ipctrl_pipe_cancel),
    .pcgen_ibctrl_cancel                 (pcgen_ibctrl_cancel),
    .pcgen_ibctrl_ibuf_flush             (pcgen_ibctrl_ibuf_flush),
    .pcgen_ibctrl_lbuf_flush             (pcgen_ibctrl_lbuf_flush),
    .pcgen_ibctrl_bju_chgflw             (pcgen_ibctrl_bju_chgflw),
    .pcgen_addrgen_cancel                (pcgen_addrgen_cancel),
    .pcgen_l1_refill_chgflw              (pcgen_l1_refill_chgflw),
    .pcgen_ipb_chgflw                    (pcgen_ipb_chgflw),
    .pcgen_icache_if_index               (pcgen_icache_if_index),
    .pcgen_icache_if_way_pred            (pcgen_icache_if_way_pred),
    .pcgen_icache_if_chgflw              (pcgen_icache_if_chgflw),
    .pcgen_icache_if_chgflw_short        (pcgen_icache_if_chgflw_short),
    .pcgen_icache_if_chgflw_bank0        (pcgen_icache_if_chgflw_bank0),
    .pcgen_icache_if_chgflw_bank1        (pcgen_icache_if_chgflw_bank1),
    .pcgen_icache_if_chgflw_bank2        (pcgen_icache_if_chgflw_bank2),
    .pcgen_icache_if_chgflw_bank3        (pcgen_icache_if_chgflw_bank3),
    .pcgen_icache_if_seq_data_req        (pcgen_icache_if_seq_data_req),
    .pcgen_icache_if_seq_data_req_short  (pcgen_icache_if_seq_data_req_short),
    .pcgen_icache_if_seq_tag_req         (pcgen_icache_if_seq_tag_req),
    .pcgen_icache_if_gateclk_en          (pcgen_icache_if_gateclk_en),
    .pcgen_bht_chgflw                    (pcgen_bht_chgflw),
    .pcgen_bht_chgflw_short              (pcgen_bht_chgflw_short),
    .pcgen_bht_ifpc                      (pcgen_bht_ifpc),
    .pcgen_bht_pcindex                   (pcgen_bht_pcindex),
    .pcgen_bht_seq_read                  (pcgen_bht_seq_read),
    .pcgen_btb_chgflw                    (pcgen_btb_chgflw),
    .pcgen_btb_chgflw_short              (pcgen_btb_chgflw_short),
    .pcgen_btb_chgflw_higher_than_addrgen(pcgen_btb_chgflw_higher_than_addrgen),
    .pcgen_btb_chgflw_higher_than_ip     (pcgen_btb_chgflw_higher_than_ip),
    .pcgen_btb_chgflw_higher_than_if     (pcgen_btb_chgflw_higher_than_if),
    .pcgen_btb_index                     (pcgen_btb_index),
    .pcgen_btb_stall                     (pcgen_btb_stall),
    .pcgen_btb_stall_short               (pcgen_btb_stall_short),
    .pcgen_l0_btb_chgflw_mask            (pcgen_l0_btb_chgflw_mask),
    .pcgen_l0_btb_chgflw_vld             (pcgen_l0_btb_chgflw_vld),
    .pcgen_l0_btb_chgflw_pc              (pcgen_l0_btb_chgflw_pc),
    .pcgen_l0_btb_if_pc                  (pcgen_l0_btb_if_pc),
    .pcgen_sfp_pc                        (pcgen_sfp_pc),
    .pcgen_debug_chgflw                  (pcgen_debug_chgflw),
    .pcgen_debug_pcbus                   (pcgen_debug_pcbus),
    .ifu_had_fetch_pc                    (ifu_had_fetch_pc)
  );
  rv32_ifu_ifctrl u_ifctrl (
    .forever_cpuclk                   (forever_cpuclk),
    .cpurst_b                         (cpurst_b),
    .cp0_yy_clk_en                    (cp0_yy_clk_en),
    .cp0_ifu_no_op_req                (stop_fetch),
    .cp0_ifu_icache_en                (cp0_ifu_icache_en),
    .cp0_ifu_btb_en                   (cp0_ifu_btb_en),
    .hpcp_ifu_cnt_en                  (hpcp_ifu_cnt_en),
    .rtu_ifu_dbgon                    (rtu_ifu_dbgon),
    .frontend_init_done               (fetch_initialized),
    .maintenance_busy                 (maint_busy),
    .frontend_redirect                (frontend_redirect),
    .pcgen_ifctrl_pipe_cancel         (pcgen_ifctrl_pipe_cancel),
    .pcgen_ifctrl_reissue             (pcgen_ifctrl_reissue),
    .control_ifctrl_reissue           (fault_accept),
    .pcgen_ifctrl_pc                  (pcgen_ifctrl_pc),
    .pcgen_icache_if_index            (pcgen_icache_if_index),
    .pcgen_icache_if_way_pred         (pcgen_icache_if_way_pred),
    .region_ifctrl_attr               (region_ifctrl_attr),
    .ipctrl_ifctrl_stall              (ipctrl_ifctrl_stall),
    .ipctrl_ifctrl_bht_stall          (1'b0),
    .btb_ifctrl_ready                 (btb_lookup_ready),
    .maintenance_array_req            (maintenance_array_req),
    .refill_array_req                 (refill_array_req),
    .ipb_array_req                    (ipb_array_req),
    .ifctrl_array_grant               (ifctrl_array_grant),
    .ifctrl_maintenance_grant         (ifctrl_maintenance_grant),
    .ifctrl_refill_grant              (ifctrl_refill_grant),
    .ifctrl_ipb_grant                 (ifctrl_ipb_grant),
    .ifctrl_array_fetch               (ifctrl_array_fetch),
    .ifctrl_array_pc                  (ifctrl_array_pc),
    .ifctrl_array_way                 (ifctrl_array_way),
    .l1_refill_ifctrl_active          (refill_active_block),
    .l1_refill_ifctrl_live            (l1_refill_ifctrl_live),
    .l1_refill_ifctrl_vld             (l1_refill_ifctrl_vld),
    .l1_refill_ifctrl_pc              (l1_refill_ifctrl_pc),
    .ifctrl_l1_refill_ready           (ifctrl_l1_refill_ready),
    .ifctrl_l1_refill_cancel          (ifctrl_l1_refill_cancel),
    .ifdp_ifctrl_fault                (ifdp_ifctrl_fault),
    .ifdp_ifctrl_l0_vld               (ifdp_ifctrl_l0_vld),
    .ifdp_ifctrl_l0_target            (ifdp_ifctrl_l0_target),
    .ifdp_ifctrl_l0_way               (ifdp_ifctrl_l0_way),
    .ifctrl_ifdp_issue                (ifctrl_ifdp_issue),
    .ifctrl_ifdp_issue_pc             (ifctrl_ifdp_issue_pc),
    .ifctrl_ifdp_issue_way            (ifctrl_ifdp_issue_way),
    .ifctrl_ifdp_issue_kind           (ifctrl_ifdp_issue_kind),
    .ifctrl_ifdp_hold                 (ifctrl_ifdp_hold),
    .ifctrl_ifdp_held                 (ifctrl_ifdp_held),
    .ifctrl_ifdp_pipedown             (ifctrl_ifdp_pipedown),
    .ifctrl_ifdp_l0_accept            (ifctrl_ifdp_l0_accept),
    .ifctrl_ipctrl_vld                (ifctrl_ipctrl_vld),
    .ifctrl_ipctrl_if_pcload          (ifctrl_ipctrl_if_pcload),
    .ifctrl_pcgen_stall               (ifctrl_pcgen_stall),
    .ifctrl_pcgen_stall_short         (ifctrl_pcgen_stall_short),
    .ifctrl_pcgen_reissue_pcload      (ifctrl_pcgen_reissue_pcload),
    .ifctrl_pcgen_chgflw_vld          (ifctrl_pcgen_chgflw_vld),
    .ifctrl_pcgen_chgflw_no_stall_mask(ifctrl_pcgen_chgflw_no_stall_mask),
    .ifctrl_pcgen_pcload_pc           (ifctrl_pcgen_pcload_pc),
    .ifctrl_pcgen_way_pred            (ifctrl_pcgen_way_pred),
    .ifctrl_btb_lookup_vld            (ifctrl_btb_lookup_vld),
    .ifctrl_btb_lookup_pc             (ifctrl_btb_lookup_pc),
    .ifctrl_bht_read                  (ifctrl_bht_read),
    .ifctrl_bht_pcindex               (ifctrl_bht_pcindex),
    .ifctrl_bht_pipedown              (ifctrl_bht_pipedown),
    .ifctrl_bht_stall                 (ifctrl_bht_stall),
    .ifctrl_l0_btb_lookup_vld         (ifctrl_l0_btb_lookup_vld),
    .ifctrl_l0_btb_accept             (ifctrl_l0_btb_accept),
    .ifctrl_debug_if_vld              (ifctrl_debug_if_vld),
    .ifctrl_debug_if_stall            (ifctrl_debug_if_stall),
    .ifctrl_idle                      (ifctrl_idle),
    .ifu_hpcp_frontend_stall          (if_frontend_stall)
  );
  rv32_ifu_ifdp u_ifdp (
    .forever_cpuclk               (forever_cpuclk),
    .cpurst_b                     (cpurst_b),
    .cp0_ifu_icache_en            (cp0_ifu_icache_en),
    .cp0_yy_priv_mode             (cp0_yy_priv_mode),
    .region_ifdp_attr             (region_ifdp_attr),
    .ifctrl_ifdp_issue            (ifctrl_ifdp_issue),
    .ifctrl_ifdp_hold             (ifctrl_ifdp_hold),
    .ifctrl_ifdp_held             (ifctrl_ifdp_held),
    .ifctrl_ifdp_pipedown         (ifctrl_ifdp_pipedown),
    .ifctrl_ifdp_issue_pc         (ifctrl_ifdp_issue_pc),
    .ifctrl_ifdp_issue_way        (ifctrl_ifdp_issue_way),
    .ifctrl_ifdp_issue_kind       (ifctrl_ifdp_issue_kind),
    .icache_if_ifdp_inst_data0    (raw_cache_inst_data0),
    .icache_if_ifdp_inst_data1    (raw_cache_inst_data1),
    .icache_if_ifdp_precode0      (raw_cache_precode0),
    .icache_if_ifdp_precode1      (raw_cache_precode1),
    .icache_if_ifdp_tag_data0     (raw_cache_tag_data0),
    .icache_if_ifdp_tag_data1     (raw_cache_tag_data1),
    .icache_if_ifdp_fifo          (raw_cache_fifo),
    .l1_refill_ifdp_acc_err       (l1_refill_ifdp_acc_err),
    .l1_refill_ifdp_inst_data     (l1_refill_ifdp_inst_data),
    .l1_refill_ifdp_precode       (l1_refill_ifdp_precode),
    .btb_ifdp_vld                 (btb_if_vld),
    .btb_ifdp_pc                  (btb_if_pc),
    .btb_ifdp_hit                 (btb_if_hit),
    .btb_ifdp_target              (btb_if_target),
    .btb_ifdp_way                 (btb_if_way_hint),
    .l0_btb_ifdp_hit              (l0_hit),
    .bp_recovery_stall            (bp_recovery_stall),
    .l0_btb_ifdp_index            (l0_hit_index),
    .l0_btb_ifdp_slot             (l0_hit_slot),
    .l0_btb_ifdp_way              (l0_way_hint),
    .l0_btb_ifdp_type             (l0_hit_type),
    .l0_btb_ifdp_target           (l0_target),
    .had_ifu_bkpta_en             (had_ifu_bkpta_en),
    .had_ifu_bkptb_en             (had_ifu_bkptb_en),
    .had_yy_xx_bkpta_base         (had_yy_xx_bkpta_base),
    .had_yy_xx_bkptb_base         (had_yy_xx_bkptb_base),
    .had_yy_xx_bkpta_mask         (had_yy_xx_bkpta_mask),
    .had_yy_xx_bkptb_mask         (had_yy_xx_bkptb_mask),
    .sfp_ifdp_vld                 (1'b1),
    .sfp_ifdp_pc                  (ifdp_l0_btb_pc),
    .sfp_ifdp_no_spec             (sfp_no_spec),
    .ifdp_ifctrl_fault            (ifdp_ifctrl_fault),
    .ifdp_ifctrl_l0_vld           (ifdp_ifctrl_l0_vld),
    .ifdp_ifctrl_l0_target        (ifdp_ifctrl_l0_target),
    .ifdp_l0_btb_pc               (ifdp_l0_btb_pc),
    .ifdp_bht_pc                  (ifdp_bht_pc),
    .ifdp_ifctrl_l0_way           (ifdp_ifctrl_l0_way),
    .ifdp_ipdp_vpc                (ifdp_ipdp_vpc),
    .ifdp_ipdp_attr               (ifdp_ipdp_attr),
    .ifdp_ipdp_priv_mode          (ifdp_ipdp_priv_mode),
    .ifdp_ipdp_way_pred           (ifdp_ipdp_way_pred),
    .ifdp_ipdp_refill_on          (ifdp_ipdp_refill_on),
    .ifdp_ipdp_cache_bypass       (ifdp_ipdp_cache_bypass),
    .ifdp_ipdp_fifo               (ifdp_ipdp_fifo),
    .ifdp_ipdp_fault              (ifdp_ipdp_fault),
    .ifdp_ipdp_cause              (ifdp_ipdp_cause),
    .ifdp_ipdp_word_mask          (ifdp_ipdp_word_mask),
    .ifdp_ipdp_bkpta              (ifdp_ipdp_bkpta),
    .ifdp_ipdp_bkptb              (ifdp_ipdp_bkptb),
    .ifdp_ipdp_inst_data0         (ifdp_ipdp_inst_data0),
    .ifdp_ipdp_inst_data1         (ifdp_ipdp_inst_data1),
    .ifdp_ipdp_precode0           (ifdp_ipdp_precode0),
    .ifdp_ipdp_precode1           (ifdp_ipdp_precode1),
    .ifdp_ipdp_tag_match0         (ifdp_ipdp_tag_match0),
    .ifdp_ipdp_tag_match1         (ifdp_ipdp_tag_match1),
    .ifdp_ipdp_btb_vld            (ifdp_ipdp_btb_vld),
    .ifdp_ipdp_btb_hit            (ifdp_ipdp_btb_hit),
    .ifdp_ipdp_btb_target         (ifdp_ipdp_btb_target),
    .ifdp_ipdp_btb_way            (ifdp_ipdp_btb_way),
    .ifdp_ipdp_l0_hit             (ifdp_ipdp_l0_hit),
    .ifdp_ipdp_l0_index           (ifdp_ipdp_l0_index),
    .ifdp_ipdp_l0_slot            (ifdp_ipdp_l0_slot),
    .ifdp_ipdp_l0_type            (ifdp_ipdp_l0_type),
    .ifdp_ipdp_l0_target          (ifdp_ipdp_l0_target),
    .ifdp_ipdp_l0_way             (ifdp_ipdp_l0_way),
    .ifdp_ipdp_no_spec            (ifdp_ipdp_no_spec),
    .ifdp_ipdp_seq_pc             (ifdp_ipdp_seq_pc),
    .ifdp_ipdp_word_pc            (ifdp_ipdp_word_pc),
    .ifdp_ipdp_l0_entry_mask      (ifdp_ipdp_l0_entry_mask),
    .ifdp_ipdp_l0_btb_target_match(ifdp_ipdp_l0_btb_target_match)
  );
  rv32_ifu_if_array #(
    .IC_BYTES (IC_BYTES),
    .IC_LINE  (IC_LINE)
  ) u_if_array (
    .ifctrl_array_grant             (ifctrl_array_grant),
    .ifctrl_array_pc                (ifctrl_array_pc),
    .ifctrl_array_way               (ifctrl_array_way),
    .l1_refill_icache_if_install    (l1_refill_icache_if_install),
    .cp0_ifu_icache_en              (cp0_ifu_icache_en),
    .cp0_ifu_icg_en                 (cp0_ifu_icg_en),
    .cp0_yy_clk_en                  (cp0_yy_clk_en),
    .cpurst_b                       (cpurst_b),
    .forever_cpuclk                 (forever_cpuclk),
    .hpcp_ifu_cnt_en                (hpcp_ifu_cnt_en),
    .ifctrl_icache_if_index         (ifctrl_icache_if_index),
    .ifctrl_icache_if_inv_fifo      (ifctrl_icache_if_inv_fifo),
    .ifctrl_icache_if_inv_on        (ifctrl_icache_if_inv_on),
    .ifctrl_icache_if_read_req_data0(ifctrl_icache_if_read_req_data0),
    .ifctrl_icache_if_read_req_data1(ifctrl_icache_if_read_req_data1),
    .ifctrl_icache_if_read_req_index(ifctrl_icache_if_read_req_index),
    .ifctrl_icache_if_read_req_tag  (ifctrl_icache_if_read_req_tag),
    .ifctrl_icache_if_reset_req     (ifctrl_icache_if_reset_req),
    .ifctrl_icache_if_tag_req       (ifctrl_icache_if_tag_req),
    .ifctrl_icache_if_tag_wen       (ifctrl_icache_if_tag_wen),
    .ifu_hpcp_icache_miss_pre       (miss_event),
    .ipb_icache_if_index            (ipb_icache_if_index),
    .ipb_icache_if_req              (ipb_icache_if_req),
    .ipb_icache_if_req_for_gateclk  (ipb_icache_if_req_for_gateclk),
    .l1_refill_icache_if_fifo       (l1_refill_icache_if_fifo),
    .l1_refill_icache_if_first      (l1_refill_icache_if_first),
    .l1_refill_icache_if_index      (l1_refill_icache_if_index),
    .l1_refill_icache_if_inst_data  (l1_refill_icache_if_inst_data),
    .l1_refill_icache_if_last       (l1_refill_icache_if_last),
    .l1_refill_icache_if_pre_code   (l1_refill_icache_if_pre_code),
    .l1_refill_icache_if_ptag       (l1_refill_icache_if_ptag),
    .l1_refill_icache_if_wr         (l1_refill_icache_if_wr),
    .pad_yy_icg_scan_en             (pad_yy_icg_scan_en),
    .icache_if_ifctrl_inst_data0    (icache_if_ifctrl_inst_data0),
    .icache_if_ifctrl_inst_data1    (icache_if_ifctrl_inst_data1),
    .icache_if_ifctrl_tag_data0     (icache_if_ifctrl_tag_data0),
    .icache_if_ifctrl_tag_data1     (icache_if_ifctrl_tag_data1),
    .icache_if_ifdp_fifo            (raw_cache_fifo),
    .icache_if_ifdp_inst_data0      (raw_cache_inst_data0),
    .icache_if_ifdp_inst_data1      (raw_cache_inst_data1),
    .icache_if_ifdp_precode0        (raw_cache_precode0),
    .icache_if_ifdp_precode1        (raw_cache_precode1),
    .icache_if_ifdp_tag_data0       (raw_cache_tag_data0),
    .icache_if_ifdp_tag_data1       (raw_cache_tag_data1),
    .icache_if_ipb_tag_data0        (icache_if_ipb_tag_data0),
    .icache_if_ipb_tag_data1        (icache_if_ipb_tag_data1),
    .ifu_hpcp_icache_access         (ifu_hpcp_icache_access),
    .ifu_hpcp_icache_miss           (ifu_hpcp_icache_miss)
  );
  rv32_ifu_pipeline u_pipeline (
    .ifdp_ipdp_vpc             (pipe_ifdp_ipdp_vpc),
    .ifdp_ipdp_inst_data0      (pipe_ifdp_ipdp_inst_data0),
    .ifdp_ipdp_inst_data1      (pipe_ifdp_ipdp_inst_data1),
    .ifdp_ipdp_tag_match0      (pipe_ifdp_ipdp_tag_match0),
    .ifdp_ipdp_tag_match1      (pipe_ifdp_ipdp_tag_match1),
    .ifdp_ipdp_way_pred        (pipe_ifdp_ipdp_way_pred),
    .ifdp_ipdp_fault           (pipe_ifdp_ipdp_fault),
    .ifdp_ipdp_cause           (pipe_ifdp_ipdp_cause),
    .ifdp_ipdp_bkpta           (pipe_ifdp_ipdp_bkpta),
    .ifdp_ipdp_bkptb           (pipe_ifdp_ipdp_bkptb),
    .ifdp_ipdp_no_spec         (pipe_ifdp_ipdp_no_spec),
    .bht_pred                  (pipe_bht_pred),
    .bht_chk_idx               (bht_chk_idx),
    .ifdp_ipdp_btb_hit         (pipe_ifdp_ipdp_btb_hit),
    .ifdp_ipdp_btb_target      (pipe_ifdp_ipdp_btb_target),
    .ifdp_ipdp_btb_way         (pipe_ifdp_ipdp_btb_way),
    .forever_cpuclk            (forever_cpuclk),
    .cpurst_b                  (cpurst_b),
    .cancel_ip                 (cancel_ip),
    .ifctrl_ipctrl_vld         (pipe_ip_valid),
    .ifctrl_ifdp_pipedown      (pipe_ip_load),
    .ifdp_ipdp_word_mask       (pipe_ifdp_ipdp_word_mask),
    .ifdp_ipdp_cache_bypass    (pipe_ifdp_ipdp_cache_bypass),
    .ifdp_ipdp_fifo            (pipe_ifdp_ipdp_fifo),
    .demand_ready              (pipe_demand_ready),
    .ifctrl_ipctrl_if_pcload   (ifctrl_ipctrl_if_pcload),
    .ifdp_ipdp_l0_hit          (pipe_ifdp_ipdp_l0_hit),
    .ifdp_ipdp_l0_slot         (pipe_ifdp_ipdp_l0_slot),
    .ifdp_ipdp_l0_type         (pipe_ifdp_ipdp_l0_type),
    .ifdp_ipdp_l0_target       (pipe_ifdp_ipdp_l0_target),
    .ifdp_ipdp_l0_entry_mask   (pipe_ifdp_ipdp_l0_entry_mask),
    .ipctrl_ifctrl_stall       (ipctrl_ifctrl_stall),
    .demand_valid              (demand_valid),
    .demand_pc                 (demand_pc),
    .demand_way                (demand_way),
    .reissue                   (reissue),
    .ip_redirect               (ip_redirect),
    .ip_redirect_pc            (ip_redirect_pc),
    .reissue_way               (reissue_way),
    .bht_event                 (bht_event),
    .bht_taken                 (bht_taken),
    .bht_more                  (bht_more),
    .l0_invalidate             (l0_invalidate),
    .l0_invalidate_mask        (l0_invalidate_mask),
    .fault_accept              (fault_accept),
    .way_event                 (way_event),
    .miss_event                (miss_event),
    .ib_accept                 (ib_accept),
    .consume_count             (consume_count),
    .ras_valid                 (ras_top_valid),
    .ras_target                (ras_l0_btb_pc),
    .corrected_packet          (corrected_packet),
    .flush                     (global_flush),
    .recovery_stall            (bp_recovery_stall),
    .ind_enable                (cp0_ifu_ind_btb_en),
    .ind_result_vld            (ind_result_vld),
    .ind_target_valid          (ind_target_valid),
    .ind_target                (ind_target),
    .btb_update_ready          (training_ready),
    .ind_query                 (ind_query),
    .ib_redirect               (ib_redirect),
    .ib_redirect_pc            (ib_redirect_pc),
    .local_recover_ghr         (ib_recover_ghr),
    .ras_push                  (ras_push),
    .ras_pop                   (ras_pop),
    .jump_accept               (jump_accept),
    .return_accept             (return_accept),
    .ind_miss_event            (ind_miss_event),
    .push_pc                   (push_pc),
    .jump_target               (jump_target),
    .train_valid               (train_valid),
    .train_taken               (train_taken),
    .train_cnt_lo              (train_cnt_lo),
    .train_ras                 (train_ras),
    .btb_used                  (btb_used),
    .train_pc                  (train_pc),
    .train_target              (train_target),
    .train_type                (train_type),
    .train_way                 (train_way),
    .ind_query_ghr             (ind_query_ghr),
    .ib_empty                  (ib_empty),
    .pcfifo_wait               (pcfifo_wait),
    .recovery_wait             (recovery_wait),
    .iu_ifu_pcfifo_credit      (iu_ifu_pcfifo_credit),
    .iu_ifu_pcfifo_alloc0_token(iu_ifu_pcfifo_alloc0_token),
    .iu_ifu_pcfifo_alloc1_token(iu_ifu_pcfifo_alloc1_token),
    .create_en                 (create_en),
    .create_pc                 (create_pc),
    .create_target             (create_target),
    .create_npc                (create_npc),
    .create_type               (create_type),
    .create_dst                (create_dst),
    .create_pred               (create_pred),
    .create_unknown            (create_unknown),
    .create_chk                (create_chk),
    .idu_ifu_accept_num        (idu_ifu_accept_num),
    .out_count                 (out_count),
    .out_packet                (out_packet),
    .out_chk                   (out_chk),
    .occupancy                 (occupancy),
    .ibuf_empty                (ibuf_empty)
  );
  rv32_ifu_memory #(
    .IC_BYTES (IC_BYTES),
    .IC_LINE  (IC_LINE)
  ) u_memory (
    .forever_cpuclk               (forever_cpuclk),
    .cpurst_b                     (cpurst_b),
    .cancel                       (memory_cancel),
    .invalidate                   (maint_invalidate),
    .demand_valid                 (memory_demand_valid),
    .demand_ready                 (memory_demand_ready),
    .demand_pc                    (demand_pc),
    .demand_way                   (demand_way),
    .demand_allocate              (demand_allocate),
    .demand_attr                  (ifdp_ipdp_attr),
    .demand_priv                  (ifdp_ipdp_priv_mode),
    .refill_array_req             (refill_array_req),
    .ifctrl_refill_grant          (ifctrl_refill_grant),
    .l1_refill_icache_if_wr       (l1_refill_icache_if_wr),
    .l1_refill_icache_if_first    (l1_refill_icache_if_first),
    .l1_refill_icache_if_last     (l1_refill_icache_if_last),
    .l1_refill_icache_if_install  (l1_refill_icache_if_install),
    .l1_refill_icache_if_fifo     (l1_refill_icache_if_fifo),
    .l1_refill_icache_if_index    (l1_refill_icache_if_index),
    .l1_refill_icache_if_inst_data(l1_refill_icache_if_inst_data),
    .l1_refill_icache_if_pre_code (l1_refill_icache_if_pre_code),
    .l1_refill_icache_if_ptag     (l1_refill_icache_if_ptag),
    .l1_refill_ifctrl_active      (refill_active_raw),
    .l1_refill_ifctrl_live        (l1_refill_ifctrl_live),
    .l1_refill_ifctrl_vld         (l1_refill_ifctrl_vld),
    .l1_refill_ifctrl_pc          (l1_refill_ifctrl_pc),
    .ifctrl_l1_refill_ready       (ifctrl_l1_refill_ready),
    .l1_refill_ifdp_inst_data     (l1_refill_ifdp_inst_data),
    .l1_refill_ifdp_precode       (l1_refill_ifdp_precode),
    .l1_refill_ifdp_acc_err       (l1_refill_ifdp_acc_err),
    .refill_idle                  (refill_idle),
    .protocol_error               (protocol_error),
    .enable                       (cp0_ifu_icache_pref_en),
    .stop                         (stop_fetch),
    .region_pc                    (prefetch_region_pc),
    .region_attr                  (prefetch_region_attr),
    .ipb_array_req                (ipb_array_req),
    .ifctrl_ipb_grant             (ifctrl_ipb_grant),
    .icache_if_ipb_tag_data0      (icache_if_ipb_tag_data0),
    .icache_if_ipb_tag_data1      (icache_if_ipb_tag_data1),
    .ipb_icache_if_index          (ipb_icache_if_index),
    .ipb_icache_if_req            (ipb_icache_if_req),
    .ipb_icache_if_req_for_gateclk(ipb_icache_if_req_for_gateclk),
    .prefetch_idle                (prefetch_idle),
    .launch                       (ipb_launch),
    .demand_hit                   (ipb_demand_hit),
    .cp0_yy_priv_mode             (cp0_yy_priv_mode),
    .cp0_ifu_insde                (cp0_ifu_insde),
    .ifu_biu_rd_req               (ifu_biu_rd_req),
    .ifu_biu_rd_req_gate          (ifu_biu_rd_req_gate),
    .ifu_biu_rd_id                (ifu_biu_rd_id),
    .ifu_biu_rd_addr              (ifu_biu_rd_addr),
    .ifu_biu_rd_len               (ifu_biu_rd_len),
    .ifu_biu_rd_burst             (ifu_biu_rd_burst),
    .ifu_biu_rd_domain            (ifu_biu_rd_domain),
    .ifu_biu_rd_user              (ifu_biu_rd_user),
    .ifu_biu_rd_size              (ifu_biu_rd_size),
    .ifu_biu_rd_prot              (ifu_biu_rd_prot),
    .ifu_biu_rd_cache             (ifu_biu_rd_cache),
    .ifu_biu_rd_snoop             (ifu_biu_rd_snoop),
    .biu_ifu_rd_grnt              (biu_ifu_rd_grnt),
    .biu_ifu_rd_data_vld          (biu_ifu_rd_data_vld),
    .biu_ifu_rd_id                (biu_ifu_rd_id),
    .biu_ifu_rd_last              (biu_ifu_rd_last),
    .biu_ifu_rd_data              (biu_ifu_rd_data),
    .biu_ifu_rd_resp              (biu_ifu_rd_resp),
    .ifu_biu_r_ready              (ifu_biu_r_ready),
    .bus_idle                     (bus_idle)
  );
  rv32_ifu_maintenance #(
    .IC_BYTES (IC_BYTES),
    .IC_LINE  (IC_LINE)
  ) u_maintenance (
    .forever_cpuclk                 (forever_cpuclk),
    .cpurst_b                       (cpurst_b),
    .recovery                       (backend_redirect),
    .recovery_pc                    (backend_pc),
    .memory_idle                    (memory_idle),
    .refill_array_req               (refill_array_req),
    .bp_init_done                   (bp_init_done),
    .bp_maint_ready                 (bp_maint_ready),
    .bp_maint_done                  (bp_maint_done),
    .bp_maint_vld                   (bp_maint_vld),
    .bp_maint_mask                  (bp_maint_mask),
    .cp0_ifu_maint_vld              (cp0_ifu_maint_vld),
    .ifu_cp0_maint_ready            (ifu_cp0_maint_ready),
    .cp0_ifu_maint_op               (cp0_ifu_maint_op),
    .cp0_ifu_maint_pa               (cp0_ifu_maint_pa),
    .cp0_ifu_maint_resume_pc        (cp0_ifu_maint_resume_pc),
    .cp0_ifu_maint_pred_mask        (cp0_ifu_maint_pred_mask),
    .ifu_cp0_maint_done             (ifu_cp0_maint_done),
    .lsu_ifu_icache_inv_vld         (lsu_ifu_icache_inv_vld),
    .lsu_ifu_icache_inv_all         (lsu_ifu_icache_inv_all),
    .lsu_ifu_icache_inv_pa          (lsu_ifu_icache_inv_pa),
    .lsu_ifu_icache_inv_resume_pc   (lsu_ifu_icache_inv_resume_pc),
    .ifu_lsu_icache_inv_ready       (ifu_lsu_icache_inv_ready),
    .ifu_lsu_icache_inv_done        (ifu_lsu_icache_inv_done),
    .init_done                      (cache_init_done),
    .busy                           (maint_busy),
    .invalidate                     (maint_invalidate),
    .flush                          (maint_flush),
    .resume                         (maint_resume),
    .resume_pc                      (maint_resume_pc),
    .clear_sfp                      (clear_sfp),
    .maintenance_array_req          (maintenance_array_req),
    .ifctrl_maintenance_grant       (ifctrl_maintenance_grant),
    .ifctrl_icache_if_index         (ifctrl_icache_if_index),
    .ifctrl_icache_if_inv_fifo      (ifctrl_icache_if_inv_fifo),
    .ifctrl_icache_if_inv_on        (ifctrl_icache_if_inv_on),
    .ifctrl_icache_if_reset_req     (ifctrl_icache_if_reset_req),
    .ifctrl_icache_if_tag_req       (ifctrl_icache_if_tag_req),
    .ifctrl_icache_if_tag_wen       (ifctrl_icache_if_tag_wen),
    .ifctrl_icache_if_read_req_data0(ifctrl_icache_if_read_req_data0),
    .ifctrl_icache_if_read_req_data1(ifctrl_icache_if_read_req_data1),
    .ifctrl_icache_if_read_req_tag  (ifctrl_icache_if_read_req_tag),
    .ifctrl_icache_if_read_req_index(ifctrl_icache_if_read_req_index),
    .icache_if_ifctrl_inst_data0    (icache_if_ifctrl_inst_data0),
    .icache_if_ifctrl_inst_data1    (icache_if_ifctrl_inst_data1),
    .icache_if_ifctrl_tag_data0     (icache_if_ifctrl_tag_data0),
    .icache_if_ifctrl_tag_data1     (icache_if_ifctrl_tag_data1),
    .icache_if_ifdp_precode0        (raw_cache_precode0),
    .icache_if_ifdp_precode1        (raw_cache_precode1),
    .icache_if_ifdp_fifo            (raw_cache_fifo),
    .cp0_ifu_icache_read_req        (cp0_ifu_icache_read_req),
    .ifu_cp0_icache_read_ready      (ifu_cp0_icache_read_ready),
    .cp0_ifu_icache_read_index      (cp0_ifu_icache_read_index),
    .cp0_ifu_icache_read_way        (cp0_ifu_icache_read_way),
    .cp0_ifu_icache_read_kind       (cp0_ifu_icache_read_kind),
    .cp0_ifu_icache_read_data_ready (cp0_ifu_icache_read_data_ready),
    .ifu_cp0_icache_read_data_vld   (ifu_cp0_icache_read_data_vld),
    .ifu_cp0_icache_read_data       (ifu_cp0_icache_read_data),
    .software_idle                  (software_idle)
  );
  rv32_ifu_vector u_vector (
    .forever_cpuclk       (forever_cpuclk),
    .cpurst_b             (cpurst_b),
    .init_done            (ifu_cp0_init_done),
    .cp0_ifu_rvbr         (cp0_ifu_rvbr),
    .vector_pcgen_reset_on(vector_pcgen_reset_on),
    .vector_pcgen_pcload  (vector_pcgen_pcload),
    .vector_pcgen_pc      (vector_pcgen_pc)
  );
  rv32_ifu_debug u_debug (
    .forever_cpuclk    (forever_cpuclk),
    .cpurst_b          (cpurst_b),
    .rtu_ifu_dbgon     (rtu_ifu_dbgon),
    .quiescent         (ifu_had_quiescent),
    .global_cancel     (backend_redirect),
    .had_ifu_pcload    (had_ifu_pcload),
    .had_ifu_ir_vld    (had_ifu_ir_vld),
    .had_ifu_pc        (had_ifu_pc),
    .had_ifu_ir        (had_ifu_ir),
    .ifu_had_cmd_ready (ifu_had_cmd_ready),
    .debug_pcgen_pcload(debug_pcgen_pcload),
    .inject_valid      (inject_valid),
    .inject_query      (inject_query),
    .inject_pipedown   (inject_pipedown),
    .debug_busy        (debug_busy),
    .debug_restore     (debug_restore),
    .debug_pcgen_pc    (debug_pcgen_pc),
    .inject_pc         (inject_pc),
    .inject_inst       (inject_inst),
    .inject_accept     (debug_inject_accept)
  );
  rv32_ifu_bp_top #(
    .STAGED_BHT(1)
  ) u_bp_top (
    .forever_cpuclk                    (forever_cpuclk),
    .cpurst_b                          (cpurst_b),
    .iu_ifu_mispred_stall              (iu_ifu_mispred_stall),
    .frontend_cancel                   (global_flush),
    .bp_maint_vld                      (bp_maint_vld),
    .bp_maint_mask                     (bp_maint_mask),
    .bp_init_done                      (bp_init_done),
    .bp_maint_ready                    (bp_maint_ready),
    .bp_maint_done                     (bp_maint_done),
    .bp_recovery_stall                 (bp_recovery_stall),
    .rtu_ifu_retire0_vld               (rtu_ifu_retire0_vld),
    .rtu_ifu_retire1_vld               (rtu_ifu_retire1_vld),
    .rtu_ifu_retire2_vld               (rtu_ifu_retire2_vld),
    .if_pc                             (bp_if_pc),
    .if_query_pc                       (bp_query_pc),
    .ib_query_ghr                      (ind_query_ghr),
    .ip_pc                             (pipe_ifdp_ipdp_vpc),
    .ib_pred_target                    (jump_target),
    .local_recover_vld                 (ib_redirect),
    .local_recover_ghr                 (ib_recover_ghr),
    .bht_train_drop                    (bht_train_drop),
    .bht_train_drop_count              (bht_train_drop_count),
    .cp0_ifu_bht_en                    (cp0_ifu_bht_en),
    .cp0_ifu_icg_en                    (cp0_ifu_icg_en),
    .cp0_yy_clk_en                     (cp0_yy_clk_en),
    .ifctrl_bht_pipedown               (bp_pipedown),
    .ifctrl_bht_stall                  (bp_read_stall),
    .ipctrl_bht_con_br_gateclk_en      (bht_event),
    .ipctrl_bht_con_br_taken           (bht_taken),
    .ipctrl_bht_con_br_vld             (bht_event),
    .ipctrl_bht_more_br                (bht_more),
    .ipctrl_bht_vld                    (pipe_ip_valid),
    .iu_ifu_bht_check_vld              (iu_ifu_bht_check_vld),
    .iu_ifu_bht_condbr_taken           (iu_ifu_bht_condbr_taken),
    .iu_ifu_bht_pred                   (iu_ifu_bht_pred),
    .iu_ifu_chgflw_vld                 (iu_ifu_chgflw_vld),
    .iu_ifu_chk_idx                    (iu_ifu_chk_idx),
    .iu_ifu_cur_pc                     (iu_ifu_cur_pc),
    .lbuf_bht_active_state             (1'b0),
    .lbuf_bht_con_br_taken             (1'b0),
    .lbuf_bht_con_br_vld               (1'b0),
    .pad_yy_icg_scan_en                (pad_yy_icg_scan_en),
    .pcgen_bht_chgflw                  (1'b0),
    .pcgen_bht_chgflw_short            (1'b0),
    .pcgen_bht_seq_read                (bp_read),
    .rtu_ifu_flush                     (predictor_commit_restore),
    .rtu_ifu_retire0_condbr            (rtu_ifu_retire0_condbr),
    .rtu_ifu_retire0_condbr_taken      (rtu_ifu_retire0_condbr_taken),
    .rtu_ifu_retire1_condbr            (rtu_ifu_retire1_condbr),
    .rtu_ifu_retire1_condbr_taken      (rtu_ifu_retire1_condbr_taken),
    .rtu_ifu_retire2_condbr            (rtu_ifu_retire2_condbr),
    .rtu_ifu_retire2_condbr_taken      (rtu_ifu_retire2_condbr_taken),
    .bht_ipdp_pre_array_data_ntake     (bht_ipdp_pre_array_data_ntake),
    .bht_ipdp_pre_array_data_taken     (bht_ipdp_pre_array_data_taken),
    .bht_ipdp_pre_offset_onehot        (bht_ipdp_pre_offset_onehot),
    .bht_ipdp_sel_array_result         (bht_ipdp_sel_array_result),
    .bht_ipdp_vghr                     (bht_ipdp_vghr),
    .bht_lbuf_pre_ntaken_result        (bht_lbuf_pre_ntaken_result),
    .bht_lbuf_pre_taken_result         (bht_lbuf_pre_taken_result),
    .bht_lbuf_vghr                     (bht_lbuf_vghr),
    .ras_top_valid                     (ras_top_valid),
    .cp0_ifu_ras_en                    (cp0_ifu_ras_en),
    .cp0_yy_priv_mode                  (cp0_yy_priv_mode),
    .ibctrl_ras_inst_pcall             (ras_push),
    .ibctrl_ras_pcall_vld              (ras_push),
    .ibctrl_ras_pcall_vld_for_gateclk  (ras_push),
    .ibctrl_ras_preturn_vld            (ras_pop),
    .ibctrl_ras_preturn_vld_for_gateclk(ras_pop),
    .ibdp_ras_push_pc                  (push_pc),
    .rtu_ifu_retire0_inc_pc            (rtu_ifu_retire0_inc_pc),
    .rtu_ifu_retire0_mispred           (rtu_ifu_retire0_mispred),
    .rtu_ifu_retire0_pcall             (rtu_ifu_retire0_pcall),
    .rtu_ifu_retire0_preturn           (rtu_ifu_retire0_preturn),
    .ras_ipdp_data_vld                 (ras_ipdp_data_vld),
    .ras_ipdp_pc                       (ras_ipdp_pc),
    .ras_l0_btb_pc                     (ras_l0_btb_pc),
    .ras_l0_btb_push_pc                (ras_l0_btb_push_pc),
    .ras_l0_btb_ras_push               (ras_l0_btb_ras_push),
    .ind_result_vld                    (ind_result_vld),
    .cp0_ifu_ind_btb_en                (cp0_ifu_ind_btb_en),
    .ibctrl_ind_btb_check_vld          (jump_accept),
    .ibctrl_ind_btb_fifo_stall         (1'b0),
    .ipctrl_ind_btb_con_br_vld         (1'b0),
    .ipdp_ind_btb_jmp_detect           (ind_query),
    .rtu_ifu_retire0_chk_idx           (rtu_ifu_retire0_chk_idx),
    .rtu_ifu_retire0_jmp               (rtu_ifu_retire0_jmp),
    .rtu_ifu_retire0_jmp_mispred       (rtu_ifu_retire0_jmp_mispred),
    .rtu_ifu_retire0_next_pc           (rtu_ifu_retire0_next_pc),
    .rtu_ifu_retire1_chk_idx           (rtu_ifu_retire1_chk_idx),
    .rtu_ifu_retire1_jmp               (rtu_ifu_retire1_jmp),
    .rtu_ifu_retire2_chk_idx           (rtu_ifu_retire2_chk_idx),
    .rtu_ifu_retire2_jmp               (rtu_ifu_retire2_jmp),
    .ind_btb_ibctrl_dout               (ind_btb_ibctrl_dout),
    .ind_btb_ibctrl_priv_mode          (ind_btb_ibctrl_priv_mode),
    .cp0_ifu_btb_en                    (cp0_ifu_btb_en),
    .btb_lookup_vld                    (ifctrl_btb_lookup_vld),
    .btb_lookup_ready                  (btb_lookup_ready),
    .btb_lookup_pc                     (ifctrl_btb_lookup_pc),
    .btb_result_vld                    (btb_result_vld),
    .btb_hit                           (btb_hit),
    .btb_target                        (btb_target),
    .btb_way_hint                      (btb_way_hint),
    .btb_update_vld                    (train_valid),
    .btb_update_ready                  (btb_update_ready),
    .btb_update_pc                     (train_pc),
    .btb_update_target                 (train_target),
    .btb_update_way                    (train_way),
    .btb_if_vld                        (btb_if_vld),
    .btb_if_pc                         (btb_if_pc),
    .btb_if_hit                        (btb_if_hit),
    .btb_if_target                     (btb_if_target),
    .btb_if_way_hint                   (btb_if_way_hint),
    .cp0_ifu_l0btb_en                  (cp0_ifu_l0btb_en),
    .l0_lookup_vld                     (ifctrl_l0_btb_lookup_vld),
    .l0_lookup_pc                      (ifdp_l0_btb_pc),
    .l0_hit                            (l0_hit),
    .l0_hit_index                      (l0_hit_index),
    .l0_hit_slot                       (l0_hit_slot),
    .l0_hit_type                       (l0_hit_type),
    .l0_target                         (l0_target),
    .l0_way_hint                       (l0_way_hint),
    .l0_update_vld                     (train_valid),
    .l0_update_pc                      (train_pc),
    .l0_update_target                  (train_target),
    .l0_update_type                    (train_type),
    .l0_update_taken                   (train_taken),
    .l0_update_cnt_lo                  (train_cnt_lo),
    .l0_update_ras                     (train_ras),
    .l0_update_way                     (train_way),
    .l0_directed_inv_vld               (l0_invalidate),
    .l0_directed_inv_mask              (l0_invalidate_mask),
    .bht_pred                          (bht_pred),
    .bht_chk_idx                       (bht_chk_idx),
    .ind_target_valid                  (ind_target_valid),
    .ind_target                        (ind_target)
  );
  rv32_ifu_sfp u_sfp (
    .forever_cpuclk(forever_cpuclk),
    .cpurst_b      (cpurst_b),
    .enable        (cp0_ifu_nsfe),
    .invalidate    (clear_sfp),
    .cancel        (global_flush),
    .lookup_accept (ifctrl_ifdp_pipedown),
    .lookup_pc     (ifdp_l0_btb_pc),
    .lookup_mask   (sfp_mask),
    .no_spec       (sfp_no_spec),
    .retire_valid  (sfp_retire_valid),
    .retire_load   (sfp_retire_load),
    .retire_store  (sfp_retire_store),
    .retire_hit    (sfp_retire_hit),
    .retire_miss   (sfp_retire_miss),
    .retire_mispred(sfp_retire_mispred),
    .retire_pc     (sfp_retire_pc)
  );
  rv32_ifu_region #(
    .REGION_COUNT(REGION_COUNT),
    .REGION_BASE (REGION_BASE),
    .REGION_LIMIT(REGION_LIMIT),
    .REGION_ATTR (REGION_ATTR)
  ) u_region_fast (
    .pa  (pcgen_icache_if_index),
    .attr(region_ifctrl_attr)
  );
  rv32_ifu_region #(
    .REGION_COUNT(REGION_COUNT),
    .REGION_BASE (REGION_BASE),
    .REGION_LIMIT(REGION_LIMIT),
    .REGION_ATTR (REGION_ATTR)
  ) u_region_issue (
    .pa  (ifctrl_ifdp_issue_pc),
    .attr(region_ifdp_attr)
  );
  rv32_ifu_region #(
    .REGION_COUNT(REGION_COUNT),
    .REGION_BASE (REGION_BASE),
    .REGION_LIMIT(REGION_LIMIT),
    .REGION_ATTR (REGION_ATTR)
  ) u_region_prefetch (
    .pa  (prefetch_region_pc),
    .attr(prefetch_region_attr)
  );
endmodule
