// SPDX-License-Identifier: Apache-2.0
// RV32I adaptation of C910 refill/IPB responsibilities; no Cache lookup FSM.
// Generated by scripts/build_memory.py. All PCs are physical byte addresses.
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
module rv32_ifu_memory (
  input  wire         forever_cpuclk,
  input  wire         cpurst_b,
  input  wire         cancel,
  input  wire         invalidate,
  input  wire         demand_valid,
  output wire         demand_ready,
  input  wire [ 31:0] demand_pc,
  input  wire         demand_way,
  input  wire         demand_allocate,
  input  wire [  4:0] demand_attr,
  input  wire [  1:0] demand_priv,
  output wire         refill_array_req,
  input  wire         ifctrl_refill_grant,
  output wire         l1_refill_icache_if_wr,
  output wire         l1_refill_icache_if_first,
  output wire         l1_refill_icache_if_last,
  output wire         l1_refill_icache_if_install,
  output wire         l1_refill_icache_if_fifo,
  output wire [ 31:0] l1_refill_icache_if_index,
  output wire [127:0] l1_refill_icache_if_inst_data,
  output wire [ 31:0] l1_refill_icache_if_pre_code,
  output wire [ 16:0] l1_refill_icache_if_ptag,
  output wire         l1_refill_ifctrl_active,
  output wire         l1_refill_ifctrl_live,
  output wire         l1_refill_ifctrl_vld,
  output wire [ 31:0] l1_refill_ifctrl_pc,
  input  wire         ifctrl_l1_refill_ready,
  output wire [127:0] l1_refill_ifdp_inst_data,
  output wire [ 31:0] l1_refill_ifdp_precode,
  output wire         l1_refill_ifdp_acc_err,
  output wire         refill_idle,
  output wire         protocol_error,
  input  wire         enable,
  input  wire         stop,
  output wire [ 31:0] region_pc,
  input  wire [  4:0] region_attr,
  output wire         ipb_array_req,
  input  wire         ifctrl_ipb_grant,
  input  wire [ 17:0] icache_if_ipb_tag_data0,
  input  wire [ 17:0] icache_if_ipb_tag_data1,
  output wire [ 31:0] ipb_icache_if_index,
  output wire         ipb_icache_if_req,
  output wire         ipb_icache_if_req_for_gateclk,
  output wire         prefetch_idle,
  output wire         launch,
  output wire         demand_hit,
  input  wire [  1:0] cp0_yy_priv_mode,
  input  wire         cp0_ifu_insde,
  output wire         ifu_biu_rd_req,
  output wire         ifu_biu_rd_req_gate,
  output wire         ifu_biu_rd_id,
  output wire [ 31:0] ifu_biu_rd_addr,
  output wire [  1:0] ifu_biu_rd_len,
  output wire [  1:0] ifu_biu_rd_burst,
  output wire [  1:0] ifu_biu_rd_domain,
  output wire [  1:0] ifu_biu_rd_user,
  output wire [  2:0] ifu_biu_rd_size,
  output wire [  2:0] ifu_biu_rd_prot,
  output wire [  3:0] ifu_biu_rd_cache,
  output wire [  3:0] ifu_biu_rd_snoop,
  input  wire         biu_ifu_rd_grnt,
  input  wire         biu_ifu_rd_data_vld,
  input  wire         biu_ifu_rd_id,
  input  wire         biu_ifu_rd_last,
  input  wire [127:0] biu_ifu_rd_data,
  input  wire [  1:0] biu_ifu_rd_resp,
  output wire         ifu_biu_r_ready,
  output wire         bus_idle
);
  wire         refill_memory_request;
  wire         refill_memory_grant;
  wire [ 31:0] refill_memory_pc;
  wire         refill_memory_allocate;
  wire [  4:0] refill_memory_attr;
  wire [  1:0] refill_memory_priv;
  wire         refill_memory_valid;
  wire         refill_memory_error;
  wire         refill_memory_last;
  wire [127:0] refill_memory_data;
  wire         refill_memory_ready;
  wire         refill_request_accepted;
  wire         prefetch_trigger;
  wire [ 31:0] trigger_pc;
  wire         prefetch_memory_request;
  wire         prefetch_memory_grant;
  wire [ 31:0] prefetch_memory_pc;
  wire [  4:0] prefetch_memory_attr;
  wire         prefetch_memory_valid;
  wire         prefetch_memory_error;
  wire         prefetch_memory_last;
  wire [127:0] prefetch_memory_data;
  wire         prefetch_memory_ready;
  wire         reuse_request;
  wire         prefetch_demand_match;
  wire         prefetch_demand_grant;
  wire         replay_valid;
  wire         replay_last;
  wire [127:0] replay_data;
  wire         replay_ready;
  wire         reuse_match;
  wire         bus_demand_valid;
  wire [127:0] response_data;
  wire         response_error;
  wire         response_last;
  assign reuse_match           = prefetch_demand_match && refill_memory_allocate;
  assign reuse_request         = refill_memory_request && refill_memory_allocate;
  assign prefetch_trigger      = refill_request_accepted && refill_memory_allocate;
  assign trigger_pc            = refill_memory_pc;
  assign refill_memory_valid   = bus_demand_valid || replay_valid;
  assign refill_memory_data    = replay_valid ? replay_data : response_data;
  assign refill_memory_last    = replay_valid ? replay_last : response_last;
  assign refill_memory_error   = !replay_valid && response_error;
  assign replay_ready          = refill_memory_ready;
  assign prefetch_memory_data  = response_data;
  assign prefetch_memory_last  = response_last;
  assign prefetch_memory_error = response_error;
  rv32_ifu_l1_refill u_l1_refill (
    .forever_cpuclk               (forever_cpuclk),
    .cpurst_b                     (cpurst_b),
    .cancel                       (cancel),
    .invalidate                   (invalidate),
    .demand_valid                 (demand_valid),
    .demand_ready                 (demand_ready),
    .demand_pc                    (demand_pc),
    .demand_way                   (demand_way),
    .demand_allocate              (demand_allocate),
    .demand_attr                  (demand_attr),
    .demand_priv                  (demand_priv),
    .memory_request               (refill_memory_request),
    .memory_grant                 (refill_memory_grant),
    .memory_pc                    (refill_memory_pc),
    .memory_allocate              (refill_memory_allocate),
    .memory_attr                  (refill_memory_attr),
    .memory_priv                  (refill_memory_priv),
    .memory_valid                 (refill_memory_valid),
    .memory_error                 (refill_memory_error),
    .memory_last                  (refill_memory_last),
    .memory_data                  (refill_memory_data),
    .memory_ready                 (refill_memory_ready),
    .refill_array_req             (refill_array_req),
    .ifctrl_refill_grant          (ifctrl_refill_grant),
    .l1_refill_icache_if_wr       (l1_refill_icache_if_wr),
    .l1_refill_icache_if_first    (l1_refill_icache_if_first),
    .l1_refill_icache_if_last     (l1_refill_icache_if_last),
    .l1_refill_icache_if_install  (l1_refill_icache_if_install),
    .l1_refill_icache_if_fifo     (l1_refill_icache_if_fifo),
    .l1_refill_icache_if_index    (l1_refill_icache_if_index),
    .l1_refill_icache_if_inst_data(l1_refill_icache_if_inst_data),
    .l1_refill_icache_if_pre_code (l1_refill_icache_if_pre_code),
    .l1_refill_icache_if_ptag     (l1_refill_icache_if_ptag),
    .l1_refill_ifctrl_active      (l1_refill_ifctrl_active),
    .l1_refill_ifctrl_live        (l1_refill_ifctrl_live),
    .l1_refill_ifctrl_vld         (l1_refill_ifctrl_vld),
    .l1_refill_ifctrl_pc          (l1_refill_ifctrl_pc),
    .ifctrl_l1_refill_ready       (ifctrl_l1_refill_ready),
    .l1_refill_ifdp_inst_data     (l1_refill_ifdp_inst_data),
    .l1_refill_ifdp_precode       (l1_refill_ifdp_precode),
    .l1_refill_ifdp_acc_err       (l1_refill_ifdp_acc_err),
    .idle                         (refill_idle),
    .protocol_error               (protocol_error),
    .request_accepted             (refill_request_accepted)
  );
  rv32_ifu_ipb u_ipb (
    .forever_cpuclk               (forever_cpuclk),
    .cpurst_b                     (cpurst_b),
    .enable                       (enable),
    .stop                         (stop),
    .invalidate                   (invalidate),
    .trigger                      (prefetch_trigger),
    .trigger_pc                   (trigger_pc),
    .region_pc                    (region_pc),
    .region_attr                  (region_attr),
    .ipb_array_req                (ipb_array_req),
    .ifctrl_ipb_grant             (ifctrl_ipb_grant),
    .icache_if_ipb_tag_data0      (icache_if_ipb_tag_data0),
    .icache_if_ipb_tag_data1      (icache_if_ipb_tag_data1),
    .ipb_icache_if_index          (ipb_icache_if_index),
    .ipb_icache_if_req            (ipb_icache_if_req),
    .ipb_icache_if_req_for_gateclk(ipb_icache_if_req_for_gateclk),
    .memory_request               (prefetch_memory_request),
    .memory_grant                 (prefetch_memory_grant),
    .memory_pc                    (prefetch_memory_pc),
    .memory_attr                  (prefetch_memory_attr),
    .memory_valid                 (prefetch_memory_valid),
    .memory_error                 (prefetch_memory_error),
    .memory_last                  (prefetch_memory_last),
    .memory_data                  (prefetch_memory_data),
    .memory_ready                 (prefetch_memory_ready),
    .demand_request               (reuse_request),
    .demand_pc                    (refill_memory_pc),
    .demand_match                 (prefetch_demand_match),
    .demand_grant                 (prefetch_demand_grant),
    .replay_valid                 (replay_valid),
    .replay_last                  (replay_last),
    .replay_data                  (replay_data),
    .replay_ready                 (replay_ready),
    .idle                         (prefetch_idle),
    .launch                       (launch),
    .demand_hit                   (demand_hit)
  );
  rv32_ifu_biu u_biu (
    .forever_cpuclk       (forever_cpuclk),
    .cpurst_b             (cpurst_b),
    .demand_request       (refill_memory_request),
    .prefetch_request     (prefetch_memory_request),
    .demand_allocate      (refill_memory_allocate),
    .demand_pc            (refill_memory_pc),
    .prefetch_pc          (prefetch_memory_pc),
    .demand_attr          (refill_memory_attr),
    .prefetch_attr        (prefetch_memory_attr),
    .demand_priv          (refill_memory_priv),
    .cp0_yy_priv_mode     (cp0_yy_priv_mode),
    .cp0_ifu_insde        (cp0_ifu_insde),
    .prefetch_match       (reuse_match),
    .prefetch_replay_grant(prefetch_demand_grant),
    .demand_grant         (refill_memory_grant),
    .prefetch_grant       (prefetch_memory_grant),
    .demand_ready         (refill_memory_ready),
    .prefetch_ready       (prefetch_memory_ready),
    .demand_valid         (bus_demand_valid),
    .prefetch_valid       (prefetch_memory_valid),
    .response_data        (response_data),
    .response_error       (response_error),
    .response_last        (response_last),
    .ifu_biu_rd_req       (ifu_biu_rd_req),
    .ifu_biu_rd_req_gate  (ifu_biu_rd_req_gate),
    .ifu_biu_rd_id        (ifu_biu_rd_id),
    .ifu_biu_rd_addr      (ifu_biu_rd_addr),
    .ifu_biu_rd_len       (ifu_biu_rd_len),
    .ifu_biu_rd_burst     (ifu_biu_rd_burst),
    .ifu_biu_rd_domain    (ifu_biu_rd_domain),
    .ifu_biu_rd_user      (ifu_biu_rd_user),
    .ifu_biu_rd_size      (ifu_biu_rd_size),
    .ifu_biu_rd_prot      (ifu_biu_rd_prot),
    .ifu_biu_rd_cache     (ifu_biu_rd_cache),
    .ifu_biu_rd_snoop     (ifu_biu_rd_snoop),
    .biu_ifu_rd_grnt      (biu_ifu_rd_grnt),
    .biu_ifu_rd_data_vld  (biu_ifu_rd_data_vld),
    .biu_ifu_rd_id        (biu_ifu_rd_id),
    .biu_ifu_rd_last      (biu_ifu_rd_last),
    .biu_ifu_rd_data      (biu_ifu_rd_data),
    .biu_ifu_rd_resp      (biu_ifu_rd_resp),
    .ifu_biu_r_ready      (ifu_biu_r_ready),
    .idle                 (bus_idle)
  );
endmodule
