// SPDX-License-Identifier: Apache-2.0
// RV32I adaptation of C910 refill/IPB responsibilities; no Cache lookup FSM.
// Generated by scripts/build_memory.py. All PCs are physical byte addresses.
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
module rv32_ifu_l1_refill (
  input  wire         forever_cpuclk,
  input  wire         cpurst_b,
  input  wire         cancel,
  input  wire         invalidate,
  input  wire         demand_valid,
  output wire         demand_ready,
  input  wire [ 31:0] demand_pc,
  input  wire         demand_way,
  input  wire         demand_allocate,
  input  wire [  4:0] demand_attr,
  input  wire [  1:0] demand_priv,
  output wire         memory_request,
  input  wire         memory_grant,
  output wire [ 31:0] memory_pc,
  output wire         memory_allocate,
  output wire [  4:0] memory_attr,
  output wire [  1:0] memory_priv,
  input  wire         memory_valid,
  input  wire         memory_error,
  input  wire         memory_last,
  input  wire [127:0] memory_data,
  output wire         memory_ready,
  output wire         refill_array_req,
  input  wire         ifctrl_refill_grant,
  output wire         l1_refill_icache_if_wr,
  output wire         l1_refill_icache_if_first,
  output wire         l1_refill_icache_if_last,
  output wire         l1_refill_icache_if_install,
  output wire         l1_refill_icache_if_fifo,
  output wire [ 31:0] l1_refill_icache_if_index,
  output wire [127:0] l1_refill_icache_if_inst_data,
  output wire [ 31:0] l1_refill_icache_if_pre_code,
  output wire [ 16:0] l1_refill_icache_if_ptag,
  output wire         l1_refill_ifctrl_active,
  output wire         l1_refill_ifctrl_live,
  output wire         l1_refill_ifctrl_vld,
  output wire [ 31:0] l1_refill_ifctrl_pc,
  input  wire         ifctrl_l1_refill_ready,
  output wire [127:0] l1_refill_ifdp_inst_data,
  output wire [ 31:0] l1_refill_ifdp_precode,
  output wire         l1_refill_ifdp_acc_err,
  output wire         idle,
  output wire         protocol_error,
  output wire         request_accepted
);
  wire start, receive, write_done, first, last, error, finish;
  wire [  1:0] block;
  wire [ 31:0] incoming_precode;
  reg  [  1:0] state_q;
  wire [  1:0] state_nxt;
  wire         state_en;
  reg  [ 41:0] desc_q;
  wire [ 41:0] desc_nxt;
  wire         desc_en;
  reg          live_q;
  wire         live_nxt;
  wire         live_en;
  reg          killed_q;
  wire         killed_nxt;
  wire         killed_en;
  reg  [  1:0] count_q;
  wire [  1:0] count_nxt;
  wire         count_en;
  reg          pending_q;
  wire         pending_nxt;
  wire         pending_en;
  reg  [164:0] beat_q;
  wire [164:0] beat_nxt;
  wire         beat_en;
  reg          error_q;
  wire         error_nxt;
  wire         error_en;
  reg          forward_valid_q;
  wire         forward_valid_nxt;
  wire         forward_valid_en;
  reg  [160:0] forward_q;
  wire [160:0] forward_nxt;
  wire         forward_en;
  reg          protocol_q;
  wire         protocol_nxt;
  wire         protocol_en;

  localparam [1:0] IDLE = 0, REQ = 1, WAIT = 2, DONE = 3;
  assign start = demand_valid && demand_ready;
  assign demand_ready = state_q == IDLE && !invalidate && !cancel;
  assign memory_request = state_q == REQ && !cancel && !invalidate;
  assign request_accepted = memory_request && memory_grant;
  assign memory_pc = desc_q[41:10];
  assign memory_allocate = desc_q[9];
  assign memory_attr = desc_q[8:4];
  assign memory_priv = desc_q[3:2];
  assign idle = state_q == IDLE;
  assign memory_ready = state_q == WAIT && !pending_q;
  assign receive = memory_valid && memory_ready;
  assign first = count_q == 0;
  assign last = memory_last;
  assign error = memory_error || (memory_last != (memory_allocate ? count_q == 3 : count_q == 0));
  assign block = memory_pc[5:4] + count_q;
  assign refill_array_req = pending_q && memory_allocate && !killed_q && !invalidate;
  assign
    write_done = pending_q && (!memory_allocate || killed_q || invalidate || ifctrl_refill_grant);
  assign finish = state_q == DONE && !pending_q && !forward_valid_q;
  assign l1_refill_icache_if_wr = refill_array_req;
  assign l1_refill_icache_if_first = beat_q[162];
  assign l1_refill_icache_if_last = beat_q[163];
  assign l1_refill_icache_if_install = refill_array_req && beat_q[163] && !error_q && !beat_q[164];
  assign l1_refill_icache_if_index = {memory_pc[31:6], beat_q[161:160], 4'b0};
  assign l1_refill_icache_if_fifo = desc_q[1];
  assign l1_refill_icache_if_ptag = memory_pc[31:15];
  assign l1_refill_icache_if_inst_data = beat_q[127:0];
  assign l1_refill_icache_if_pre_code = beat_q[159:128];
  assign l1_refill_ifctrl_active = !idle;
  assign l1_refill_ifctrl_live = live_q && !cancel && !invalidate;
  assign l1_refill_ifctrl_vld = forward_valid_q && l1_refill_ifctrl_live;
  assign l1_refill_ifctrl_pc = memory_pc;
  assign l1_refill_ifdp_inst_data = forward_q[127:0];
  assign l1_refill_ifdp_precode = forward_q[159:128];
  assign l1_refill_ifdp_acc_err = forward_q[160];
  assign protocol_error = protocol_q;
  rv32_ifu_icache_precode u_precode (
    .data   (memory_data),
    .precode(incoming_precode)
  );
  assign state_en = 1'b1;
  assign state_nxt = start ? REQ : (state_q == REQ && (cancel || invalidate)) ? IDLE :
    request_accepted ? WAIT : (receive && last) ? DONE : finish ? IDLE : state_q;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_state
    if (!cpurst_b) state_q <= IDLE;
    else if (state_en) state_q <= state_nxt;
  end
  assign desc_en  = start;
  assign desc_nxt = {demand_pc, demand_allocate, demand_attr, demand_priv, demand_way, 1'b0};
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_desc
    if (!cpurst_b) desc_q <= 42'b0;
    else if (desc_en) desc_q <= desc_nxt;
  end
  assign live_en  = start || cancel || invalidate || finish;
  assign live_nxt = start;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_live
    if (!cpurst_b) live_q <= 1'b0;
    else if (live_en) live_q <= live_nxt;
  end
  assign killed_en  = start || invalidate;
  assign killed_nxt = !start;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_killed
    if (!cpurst_b) killed_q <= 1'b0;
    else if (killed_en) killed_q <= killed_nxt;
  end
  assign count_en  = start || receive;
  assign count_nxt = start ? 2'd0 : count_q + 2'd1;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_count
    if (!cpurst_b) count_q <= 2'b0;
    else if (count_en) count_q <= count_nxt;
  end
  assign pending_en  = start || receive || write_done;
  assign pending_nxt = !start && receive;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_pending
    if (!cpurst_b) pending_q <= 1'b0;
    else if (pending_en) pending_q <= pending_nxt;
  end
  assign beat_en  = receive;
  assign beat_nxt = {error, last, first, block, incoming_precode, memory_data};
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_beat
    if (!cpurst_b) beat_q <= 165'b0;
    else if (beat_en) beat_q <= beat_nxt;
  end
  assign error_en  = start || receive;
  assign error_nxt = !start && (error_q || error);
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_error
    if (!cpurst_b) error_q <= 1'b0;
    else if (error_en) error_q <= error_nxt;
  end
  assign forward_valid_en = start || cancel || invalidate || (receive && first) ||
    ifctrl_l1_refill_ready;
  assign forward_valid_nxt = !start && !cancel && !invalidate &&
    ((receive && first && live_q) || (forward_valid_q && !ifctrl_l1_refill_ready));
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_forward_valid
    if (!cpurst_b) forward_valid_q <= 1'b0;
    else if (forward_valid_en) forward_valid_q <= forward_valid_nxt;
  end
  assign forward_en  = receive && first;
  assign forward_nxt = {error, incoming_precode, memory_data};
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_forward
    if (!cpurst_b) forward_q <= 161'b0;
    else if (forward_en) forward_q <= forward_nxt;
  end
  assign protocol_en = receive;
  assign
    protocol_nxt = protocol_q || (memory_last != (memory_allocate ? count_q == 3 : count_q == 0));
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_protocol
    if (!cpurst_b) protocol_q <= 1'b0;
    else if (protocol_en) protocol_q <= protocol_nxt;
  end

endmodule
