// SPDX-License-Identifier: Apache-2.0
// RV32I adaptation of C910 support-stage duties. See doc/pipeline_zh.md.
// Generated by scripts/build_support.py. All PCs are physical byte addresses.
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
module rv32_ifu_maintenance (
  input wire forever_cpuclk,
  input wire cpurst_b,
  input wire recovery,
  input wire [31:0] recovery_pc,
  input wire memory_idle,
  input wire refill_array_req,
  input wire bp_init_done,
  input wire bp_maint_ready,
  input wire bp_maint_done,
  output wire bp_maint_vld,
  output wire [4:0] bp_maint_mask,
  input wire cp0_ifu_maint_vld,
  output wire ifu_cp0_maint_ready,
  input wire [1:0] cp0_ifu_maint_op,
  input wire [31:0] cp0_ifu_maint_pa,
  input wire [31:0] cp0_ifu_maint_resume_pc,
  input wire [7:0] cp0_ifu_maint_pred_mask,
  output wire ifu_cp0_maint_done,
  input wire lsu_ifu_icache_inv_vld,
  input wire lsu_ifu_icache_inv_all,
  input wire [31:0] lsu_ifu_icache_inv_pa,
  input wire [31:0] lsu_ifu_icache_inv_resume_pc,
  output wire ifu_lsu_icache_inv_ready,
  output wire ifu_lsu_icache_inv_done,
  output wire init_done,
  output wire busy,
  output wire invalidate,
  output wire flush,
  output wire resume,
  output wire [31:0] resume_pc,
  output wire clear_sfp,
  output wire maintenance_array_req,
  input wire ifctrl_maintenance_grant,
  output wire [31:0] ifctrl_icache_if_index,
  output wire ifctrl_icache_if_inv_fifo,
  output wire ifctrl_icache_if_inv_on,
  output wire ifctrl_icache_if_reset_req,
  output wire ifctrl_icache_if_tag_req,
  output wire [2:0] ifctrl_icache_if_tag_wen,
  output wire ifctrl_icache_if_read_req_data0,
  output wire ifctrl_icache_if_read_req_data1,
  output wire ifctrl_icache_if_read_req_tag,
  output wire [31:0] ifctrl_icache_if_read_req_index,
  input wire [127:0] icache_if_ifctrl_inst_data0,
  input wire [127:0] icache_if_ifctrl_inst_data1,
  input wire [17:0] icache_if_ifctrl_tag_data0,
  input wire [17:0] icache_if_ifctrl_tag_data1,
  input wire [31:0] icache_if_ifdp_precode0,
  input wire [31:0] icache_if_ifdp_precode1,
  input wire icache_if_ifdp_fifo,
  input wire cp0_ifu_icache_read_req,
  output wire ifu_cp0_icache_read_ready,
  input wire [10:0] cp0_ifu_icache_read_index,
  input wire cp0_ifu_icache_read_way,
  input wire [1:0] cp0_ifu_icache_read_kind,
  input wire cp0_ifu_icache_read_data_ready,
  output wire ifu_cp0_icache_read_data_vld,
  output wire [127:0] ifu_cp0_icache_read_data,
  output wire software_idle
);
  wire cp0_fire,lsu_fire,command,sw_fire,grant,tag_operation,all_operation;
  wire [1:0] line_match;
  wire [17:0] sw_tag;
  wire [127:0] sw_data,sw_payload;
  wire [31:0] sw_precode;
  wire [3:0] after_bp;
  reg [3:0] state_q;
  wire [3:0] state_nxt;
  wire state_en;
  reg init_q;
  wire init_nxt;
  wire init_en;
  reg [8:0] index_q;
  wire [8:0] index_nxt;
  wire index_en;
  reg source_q;
  wire source_nxt;
  wire source_en;
  reg [1:0] op_q;
  wire [1:0] op_nxt;
  wire op_en;
  reg [31:0] pa_q;
  wire [31:0] pa_nxt;
  wire pa_en;
  reg [31:0] resume_q;
  wire [31:0] resume_nxt;
  wire resume_en;
  reg [4:0] pred_q;
  wire [4:0] pred_nxt;
  wire pred_en;
  reg [13:0] sw_desc_q;
  wire [13:0] sw_desc_nxt;
  wire sw_desc_en;
  reg [127:0] sw_response_q;
  wire [127:0] sw_response_nxt;
  wire sw_response_en;

  localparam [3:0] INIT=0,BOOT=1,IDLE=2,DRAIN=3,BP_REQ=4,BP_WAIT=5,
    ALL=6,LINE_READ=7,LINE_WRITE=8,DONE=9,SW_READ=10,SW_CAPTURE=11,SW_RESPONSE=12;
  assign ifu_lsu_icache_inv_ready=state_q==IDLE && !recovery;
  assign ifu_cp0_maint_ready=state_q==IDLE && !recovery && !lsu_ifu_icache_inv_vld;
  assign lsu_fire=lsu_ifu_icache_inv_vld && ifu_lsu_icache_inv_ready;
  assign cp0_fire=cp0_ifu_maint_vld && ifu_cp0_maint_ready;
  assign command=lsu_fire || cp0_fire;
  assign flush=command;
  assign busy=state_q< IDLE || (state_q>=DRAIN && state_q<=DONE);
  assign invalidate=busy || command;
  assign init_done=init_q;
  assign resume=state_q==DONE && !recovery;
  assign resume_pc=resume_q;
  assign ifu_cp0_maint_done=state_q==DONE && !source_q;
  assign ifu_lsu_icache_inv_done=state_q==DONE && source_q;
  assign clear_sfp=command && !lsu_fire &&
    (cp0_ifu_maint_op==0 || (cp0_ifu_maint_op==3 && cp0_ifu_maint_pred_mask[6]));
  assign bp_maint_vld=state_q==BP_REQ;
  assign bp_maint_mask=pred_q;
  assign after_bp=op_q==3 ? DONE : op_q==2 ? LINE_READ : ALL;
  assign all_operation=state_q==INIT || state_q==ALL;
  assign tag_operation=all_operation || state_q==LINE_READ || state_q==LINE_WRITE;
  assign maintenance_array_req=tag_operation || (state_q==SW_READ && !refill_array_req);
  assign grant=maintenance_array_req && ifctrl_maintenance_grant;
  assign ifctrl_icache_if_index=all_operation ? {17'b0,index_q,6'b0} : pa_q;
  assign ifctrl_icache_if_inv_fifo=1'b0;
  assign ifctrl_icache_if_reset_req=1'b0;
  assign ifctrl_icache_if_inv_on=all_operation || state_q==LINE_WRITE;
  assign ifctrl_icache_if_tag_req=tag_operation;
  assign line_match={icache_if_ifctrl_tag_data1=={1'b1,pa_q[31:15]},
                     icache_if_ifctrl_tag_data0=={1'b1,pa_q[31:15]}};
  assign ifctrl_icache_if_tag_wen=state_q==LINE_READ ? 3'b111 :
    state_q==LINE_WRITE ? {1'b1,~line_match} : 3'b000;
  assign ifu_cp0_icache_read_ready=state_q==IDLE && !recovery &&
    !lsu_ifu_icache_inv_vld && !cp0_ifu_maint_vld && !refill_array_req;
  assign sw_fire=cp0_ifu_icache_read_req && ifu_cp0_icache_read_ready;
  assign ifctrl_icache_if_read_req_index={17'b0,sw_desc_q[13:3],4'b0};
  assign ifctrl_icache_if_read_req_data0=state_q==SW_READ && !sw_desc_q[2] && sw_desc_q[1:0]!=1;
  assign ifctrl_icache_if_read_req_data1=state_q==SW_READ && sw_desc_q[2] && sw_desc_q[1:0]!=1;
  assign ifctrl_icache_if_read_req_tag=state_q==SW_READ && sw_desc_q[1:0]==1;
  assign sw_data=sw_desc_q[2] ? icache_if_ifctrl_inst_data1 : icache_if_ifctrl_inst_data0;
  assign sw_tag=sw_desc_q[2] ? icache_if_ifctrl_tag_data1 : icache_if_ifctrl_tag_data0;
  assign sw_precode=sw_desc_q[2] ? icache_if_ifdp_precode1 : icache_if_ifdp_precode0;
  assign sw_payload=sw_desc_q[1:0]==0 ? sw_data : sw_desc_q[1:0]==1 ?
    {109'b0,icache_if_ifdp_fifo,sw_tag} : sw_desc_q[1:0]==2 ? {96'b0,sw_precode} : 128'b0;
  assign ifu_cp0_icache_read_data_vld=state_q==SW_RESPONSE;
  assign ifu_cp0_icache_read_data=sw_response_q;
  assign software_idle=state_q<SW_READ;
  assign state_en=1'b1;
  assign state_nxt=state_q==INIT ? ((grant && index_q==511) ? BOOT : INIT) :
  state_q==BOOT ? (bp_init_done ? IDLE : BOOT) : command ? DRAIN :
  state_q==DRAIN ? (memory_idle ? BP_REQ : DRAIN) :
  state_q==BP_REQ ? (bp_maint_ready ? BP_WAIT : BP_REQ) :
  state_q==BP_WAIT ? (bp_maint_done ? after_bp : BP_WAIT) :
  state_q==ALL ? ((grant && index_q==511) ? DONE : ALL) :
  state_q==LINE_READ ? (grant ? LINE_WRITE : LINE_READ) :
  state_q==LINE_WRITE ? (grant ? DONE : LINE_WRITE) : state_q==DONE ? IDLE :
  sw_fire ? SW_READ : state_q==SW_READ ? (grant ? SW_CAPTURE : SW_READ) :
  state_q==SW_CAPTURE ? SW_RESPONSE :
  (state_q==SW_RESPONSE && cp0_ifu_icache_read_data_ready) ? IDLE : state_q;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_state
    if(!cpurst_b) state_q<=INIT;
    else if(state_en) state_q<=state_nxt;
  end
  assign init_en=state_q==BOOT && bp_init_done;
  assign init_nxt=1'b1;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_init
    if(!cpurst_b) init_q<=1'b0;
    else if(init_en) init_q<=init_nxt;
  end
  assign index_en=command || (all_operation && grant);
  assign index_nxt=command ? 9'b0 : index_q+9'd1;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_index
    if(!cpurst_b) index_q<=9'b0;
    else if(index_en) index_q<=index_nxt;
  end
  assign source_en=command;
  assign source_nxt=lsu_fire;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_source
    if(!cpurst_b) source_q<=1'b0;
    else if(source_en) source_q<=source_nxt;
  end
  assign op_en=command;
  assign op_nxt=lsu_fire ? (lsu_ifu_icache_inv_all ? 2'd1 : 2'd2) : cp0_ifu_maint_op;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_op
    if(!cpurst_b) op_q<=2'b0;
    else if(op_en) op_q<=op_nxt;
  end
  assign pa_en=command;
  assign pa_nxt=lsu_fire ? lsu_ifu_icache_inv_pa : cp0_ifu_maint_pa;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_pa
    if(!cpurst_b) pa_q<=32'b0;
    else if(pa_en) pa_q<=pa_nxt;
  end
  assign resume_en=command || (busy && recovery);
  assign resume_nxt=recovery ? recovery_pc : lsu_fire ? lsu_ifu_icache_inv_resume_pc : cp0_ifu_maint_resume_pc;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_resume
    if(!cpurst_b) resume_q<=32'b0;
    else if(resume_en) resume_q<=resume_nxt;
  end
  assign pred_en=command;
  assign pred_nxt=lsu_fire ? 5'b0 : cp0_ifu_maint_op==0 ? 5'b11111 : cp0_ifu_maint_op==3 ? cp0_ifu_maint_pred_mask[4:0] : 5'b0;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_pred
    if(!cpurst_b) pred_q<=5'b0;
    else if(pred_en) pred_q<=pred_nxt;
  end
  assign sw_desc_en=sw_fire;
  assign sw_desc_nxt={cp0_ifu_icache_read_index,cp0_ifu_icache_read_way,cp0_ifu_icache_read_kind};
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_sw_desc
    if(!cpurst_b) sw_desc_q<=14'b0;
    else if(sw_desc_en) sw_desc_q<=sw_desc_nxt;
  end
  assign sw_response_en=state_q==SW_CAPTURE;
  assign sw_response_nxt=sw_payload;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_sw_response
    if(!cpurst_b) sw_response_q<=128'b0;
    else if(sw_response_en) sw_response_q<=sw_response_nxt;
  end

endmodule
