// SPDX-License-Identifier: Apache-2.0
// RV32I word-stage adaptation of the corresponding C910 IFU stage duties.
// Generated by scripts/build_pipeline.py. See doc/pipeline_zh.md.
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
module rv32_ifu_ipdp (
  input  wire [ 31:0] ifdp_ipdp_vpc,
  input  wire [127:0] ifdp_ipdp_inst_data0,
  input  wire [127:0] ifdp_ipdp_inst_data1,
  input  wire [  2:0] ifdp_ipdp_tag_match0,
  input  wire [  2:0] ifdp_ipdp_tag_match1,
  input  wire [  1:0] ifdp_ipdp_way_pred,
  input  wire         ifdp_ipdp_fault,
  input  wire         ifdp_ipdp_lbuf_on,
  input  wire [  3:0] ifdp_ipdp_cause,
  input  wire [  3:0] ifdp_ipdp_bkpta,
  input  wire [  3:0] ifdp_ipdp_bkptb,
  input  wire [  3:0] ifdp_ipdp_no_spec,
  input  wire [  3:0] remaining_mask,
  input  wire         bht_pred,
  input  wire [ 24:0] bht_chk_idx,
  input  wire [  3:0] ifdp_ipdp_btb_hit,
  input  wire [127:0] ifdp_ipdp_btb_target,
  input  wire [  7:0] ifdp_ipdp_btb_way,
  output wire [  1:0] tag_hit,
  output wire [  1:0] data_hit,
  output wire [  3:0] control_mask,
  output wire [  3:0] cond_mask,
  output wire [  3:0] taken_mask,
  output wire [767:0] slot_packet,
  output wire [127:0] slot_npc
);

  wire [127:0] data;
  genvar lane;
  assign tag_hit  = {(&ifdp_ipdp_tag_match1), (&ifdp_ipdp_tag_match0)};
  assign data_hit = tag_hit & ifdp_ipdp_way_pred;
  assign data     = data_hit[0] ? ifdp_ipdp_inst_data0 : ifdp_ipdp_inst_data1;
  generate
    for (lane = 0; lane < 4; lane = lane + 1) begin : g_word
      localparam [1:0] LANE = lane;
      wire [31:0] inst, pc, target, link, npc, early_target;
      wire condbr, jal, jalr, auipc, pc_oper, dst, push, pop, usable, bad;
      wire [2:0] cf_type;
      wire prediction_taken, btb_hit, fence;
      wire [127:0] packet;
      assign inst = ifdp_ipdp_fault ? 32'h00000013 : data[lane*32+:32];
      assign pc   = ifdp_ipdp_fault ? ifdp_ipdp_vpc : {ifdp_ipdp_vpc[31:4], LANE, 2'b00};
      rv32_ifu_bp_decode u_decode (
        .inst             (inst),
        .pc               (pc),
        .condbr           (condbr),
        .jal              (jal),
        .jalr             (jalr),
        .auipc            (auipc),
        .pc_oper          (pc_oper),
        .dst_vld          (dst),
        .cf_type          (cf_type),
        .ras_push         (push),
        .ras_pop          (pop),
        .ras_target_usable(usable),
        .direct_target    (target),
        .direct_misaligned(bad),
        .link_pc          (link)
      );
      assign btb_hit = ifdp_ipdp_btb_hit[lane] && ifdp_ipdp_btb_target[lane*32+:2] == 2'b00;
      assign early_target = btb_hit ? ifdp_ipdp_btb_target[lane*32+:32] : target;
      assign
        prediction_taken = !ifdp_ipdp_fault && ((condbr && bht_pred) || jal || (jalr && btb_hit));
      assign npc = prediction_taken && (jalr || !bad) ? early_target : link;
      assign fence = inst[6:0] == 7'h0f && inst[14:12] == 0;
      // Internal reserved bits carry source Way until PCFIFO strips them from
      // the external IDU packet. A same-line direct target can reuse this hint.
      assign packet = {
        3'b0,
        (data_hit[0] ? 2'b01 : 2'b10),
        prediction_taken,
        13'b0,
        cf_type,
        pc_oper && !ifdp_ipdp_fault,
        ifdp_ipdp_bkptb[lane],
        ifdp_ipdp_bkpta[lane],
        fence,
        ifdp_ipdp_no_spec[lane],
        (ifdp_ipdp_fault ? ifdp_ipdp_cause : 4'b0),
        ifdp_ipdp_fault,
        npc,
        pc,
        inst
      };
      assign slot_packet[lane*192+:192] = {
        ifdp_ipdp_lbuf_on,
        btb_hit,
        usable,
        pop,
        push,
        (jalr && !btb_hit),
        dst,
        bht_chk_idx,
        target,
        packet
      };
      assign slot_npc[lane*32+:32] = npc;
      assign cond_mask[lane] = remaining_mask[lane] && condbr && !ifdp_ipdp_fault;
      assign
        control_mask[lane] = remaining_mask[lane] && (condbr || jal || jalr || ifdp_ipdp_fault);
      assign
        taken_mask[lane] = remaining_mask[lane] && (prediction_taken || jalr || ifdp_ipdp_fault);
    end
  endgenerate

endmodule
