// SPDX-License-Identifier: Apache-2.0
// RV32I adaptation of C910 support-stage duties. See doc/pipeline_zh.md.
// Generated by scripts/build_support.py. All PCs are physical byte addresses.
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
module rv32_ifu_lbuf (
  input wire forever_cpuclk,
  input wire cpurst_b,
  input wire enable,
  input wire invalidate,
  input wire cancel,
  input wire record_accept,
  input wire [2:0] record_count,
  input wire [767:0] record_packet,
  input wire ibuf_empty,
  input wire ib_empty,
  input wire memory_idle,
  input wire [31:0] lookup_pc,
  input wire lookup_accept,
  output wire active,
  output wire waiting,
  output wire hit,
  output wire capture_done,
  output wire [31:0] restart_pc,
  output wire [21:0] restart_ghr,
  output wire [127:0] data,
  output wire [3:0] word_mask
);
  reg [63:0] entry_q [0:15];
  wire [63:0] entry_nxt [0:15];
  wire [15:0] entry_en;
  wire [191:0] last_packet;
  wire [2:0] last_index;
  wire backward,forward,bad_record,start,recording,append,close,path_ok,overflow,exit_replay;
  wire [4:0] total;
  wire [3:0] bad_lane,found;
  wire [4:0] prefix;
  genvar lane,entry;
  reg [2:0] state_q;
  wire [2:0] state_nxt;
  wire state_en;
  reg [4:0] count_q;
  wire [4:0] count_nxt;
  wire count_en;
  reg [31:0] start_q;
  wire [31:0] start_nxt;
  wire start_en;
  reg [31:0] end_q;
  wire [31:0] end_nxt;
  wire end_en;
  reg [31:0] expected_q;
  wire [31:0] expected_nxt;
  wire expected_en;

  // Record one observed direct-loop traversal (<=16 complete instructions).
  // Forward branches record the observed body; a newly selected uncached body
  // exits to the ordinary fetch path without reusing any dynamic metadata.
  localparam [2:0] IDLE=0,FILL=1,FRONT_BRANCH=2,CACHE=3,ACTIVE=4,FRONT_FILL=5,FRONT_CACHE=6;
  assign last_index=record_count-3'd1;
  assign last_packet=record_packet[{29'b0,last_index}*32'd192+:192];
  assign backward=record_accept && last_packet[122] &&
    (last_packet[108:106]==1 || last_packet[108:106]==2) && last_packet[95:64]<last_packet[63:32];
  assign forward=record_accept && last_packet[122] && last_packet[95:64]>last_packet[63:32]+32'd4;
  assign bad_record=|bad_lane;
  assign start=enable && state_q==IDLE && backward && !bad_record && !cancel && !invalidate;
  assign recording=state_q==FILL || state_q==FRONT_BRANCH || state_q==FRONT_FILL;
  assign path_ok=record_packet[63:32]==expected_q;
  assign total=count_q+{2'b0,record_count};
  assign overflow={1'b0,count_q}+{3'b0,record_count}>6'd16;
  assign append=recording && record_accept && path_ok && !overflow && !bad_record && !cancel && !invalidate;
  assign close=append && backward && last_packet[63:32]==end_q && last_packet[95:64]==start_q;
  assign capture_done=close;
  assign restart_pc=start_q;
  assign restart_ghr=last_packet[108:106]==1 ?
    {last_packet[180:160],last_packet[122]} : last_packet[181:160];
  assign active=state_q==ACTIVE;
  assign waiting=state_q==CACHE || state_q==FRONT_CACHE;
  assign hit=active && word_mask[lookup_pc[3:2]];
  assign exit_replay=active && lookup_accept && !hit;
  assign prefix[0]=1'b1;
  generate
    for(lane=0;lane<4;lane=lane+1) begin : g_word
      localparam [1:0] LANE=lane;
      wire [31:0] pc;
      wire [15:0] match_entry;
      wire [31:0] mux_value [0:16];
      assign bad_lane[lane]=lane<record_count &&
        (record_packet[lane*192+96] || record_packet[lane*192+187] || record_packet[lane*192+188] || record_packet[lane*192+106+:3]==3);
      assign pc={lookup_pc[31:4],LANE,2'b0};
      assign mux_value[0]=32'b0;
      for(entry=0;entry<16;entry=entry+1) begin : g_match
        assign match_entry[entry]=entry<count_q && entry_q[entry][63:32]==pc;
        assign mux_value[entry+1]=mux_value[entry] | ({32{match_entry[entry]}} & entry_q[entry][31:0]);
      end
      assign found[lane]=|match_entry;
      assign prefix[lane+1]=prefix[lane] && (LANE<lookup_pc[3:2] || found[lane]);
      assign word_mask[lane]=active && LANE>=lookup_pc[3:2] && prefix[lane+1];
      assign data[lane*32+:32]=mux_value[16];
    end
    for(entry=0;entry<16;entry=entry+1) begin : g_entry
      localparam [4:0] ENTRY=entry;
      wire [4:0] source;
      assign source=ENTRY-count_q;
      assign entry_en[entry]=append && ENTRY>=count_q && ENTRY<total;
      assign entry_nxt[entry]=record_packet[{27'b0,source}*32'd192+:64];
      always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_entry
        if(!cpurst_b) entry_q[entry]<=64'b0;
        else if(entry_en[entry]) entry_q[entry]<=entry_nxt[entry];
      end
    end
  endgenerate
  assign state_en=1'b1;
  assign state_nxt=(!enable || invalidate || cancel || exit_replay) ? IDLE : start ? FILL :
   (recording && record_accept && (!path_ok || overflow || bad_record)) ? IDLE :
   close ? (state_q==FILL ? CACHE : FRONT_CACHE) :
   (append && forward) ? FRONT_BRANCH : (state_q==FRONT_BRANCH && append) ? FRONT_FILL :
   (waiting && ibuf_empty && ib_empty && memory_idle) ? ACTIVE : state_q;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_state
    if(!cpurst_b) state_q<=IDLE;
    else if(state_en) state_q<=state_nxt;
  end
  assign count_en=start || append;
  assign count_nxt=start ? 5'b0 : total;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_count
    if(!cpurst_b) count_q<=5'b0;
    else if(count_en) count_q<=count_nxt;
  end
  assign start_en=start;
  assign start_nxt=last_packet[95:64];
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_start
    if(!cpurst_b) start_q<=32'b0;
    else if(start_en) start_q<=start_nxt;
  end
  assign end_en=start;
  assign end_nxt=last_packet[63:32];
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_end
    if(!cpurst_b) end_q<=32'b0;
    else if(end_en) end_q<=end_nxt;
  end
  assign expected_en=start || append;
  assign expected_nxt=last_packet[95:64];
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_expected
    if(!cpurst_b) expected_q<=32'b0;
    else if(expected_en) expected_q<=expected_nxt;
  end

endmodule
