/*Copyright 2019-2021 T-Head Semiconductor Co., Ltd.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// RV32I adaptation of ct_ifu_ifdp.v; generated by scripts/build_ifdp.py.
// IF compares Tag slices; IP combines them and decides hit/miss/Way replay.
// All full PCs are physical byte addresses. Word0 is data[31:0].
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
// [ICACHE 参数化] 与 rv32_ifu_icache_if.v 同套 define/公式; 默认 = 1 KiB/16 B 行。
`ifdef ICACHE_BYTES
  `define IC_BYTES_VAL `ICACHE_BYTES
`else
  `define IC_BYTES_VAL 1024
`endif
`ifdef ICACHE_LINE_BYTES
  `define IC_LINE_VAL `ICACHE_LINE_BYTES
`else
  `define IC_LINE_VAL 16
`endif

module rv32_ifu_ifdp #(
  parameter IC_BYTES  = `IC_BYTES_VAL,
  parameter IC_LINE   = `IC_LINE_VAL,
  parameter IC_SETS   = IC_BYTES/(2*IC_LINE),
  parameter SET_BITS  = $clog2(IC_SETS),
  parameter LINE_BITS = $clog2(IC_LINE),
  parameter TAG_BITS  = 32 - SET_BITS - LINE_BITS,
  parameter TAG_WIDTH = 1 + TAG_BITS,
  parameter TAG_BASE  = 32 - TAG_BITS,
  parameter BEATS     = IC_LINE/16
) (
  input  wire         forever_cpuclk,
  input  wire         cpurst_b,
  input  wire         cp0_ifu_icache_en,
  input  wire [  1:0] cp0_yy_priv_mode,
  input  wire [  4:0] region_ifdp_attr,
  input  wire         ifctrl_ifdp_issue,
  input  wire         ifctrl_ifdp_hold,
  input  wire         ifctrl_ifdp_held,
  input  wire         ifctrl_ifdp_pipedown,
  input  wire [ 31:0] ifctrl_ifdp_issue_pc,
  input  wire [  1:0] ifctrl_ifdp_issue_way,
  input  wire [  1:0] ifctrl_ifdp_issue_kind,
  input  wire [127:0] icache_if_ifdp_inst_data0,
  input  wire [127:0] icache_if_ifdp_inst_data1,
  input  wire [ 31:0] icache_if_ifdp_precode0,
  input  wire [ 31:0] icache_if_ifdp_precode1,
  input  wire [TAG_WIDTH-1:0] icache_if_ifdp_tag_data0,
  input  wire [TAG_WIDTH-1:0] icache_if_ifdp_tag_data1,
  input  wire         icache_if_ifdp_fifo,
  input  wire         l1_refill_ifdp_acc_err,
  input  wire [127:0] l1_refill_ifdp_inst_data,
  input  wire [ 31:0] l1_refill_ifdp_precode,
  input  wire         btb_ifdp_vld,
  input  wire [ 31:0] btb_ifdp_pc,
  input  wire [  3:0] btb_ifdp_hit,
  input  wire [127:0] btb_ifdp_target,
  input  wire [  7:0] btb_ifdp_way,
  input  wire         l0_btb_ifdp_hit,
  input  wire         bp_recovery_stall,
  input  wire [  3:0] l0_btb_ifdp_index,
  input  wire [  1:0] l0_btb_ifdp_slot,
  input  wire [  1:0] l0_btb_ifdp_way,
  input  wire [  2:0] l0_btb_ifdp_type,
  input  wire [ 31:0] l0_btb_ifdp_target,
  input  wire         had_ifu_bkpta_en,
  input  wire         had_ifu_bkptb_en,
  input  wire [ 31:0] had_yy_xx_bkpta_base,
  input  wire [ 31:0] had_yy_xx_bkptb_base,
  input  wire [ 31:0] had_yy_xx_bkpta_mask,
  input  wire [ 31:0] had_yy_xx_bkptb_mask,
  input  wire         sfp_ifdp_vld,
  input  wire [ 31:0] sfp_ifdp_pc,
  input  wire [  3:0] sfp_ifdp_no_spec,
  output wire         ifdp_ifctrl_fault,
  output wire         ifdp_ifctrl_l0_vld,
  output wire [ 31:0] ifdp_ifctrl_l0_target,
  output wire [ 31:0] ifdp_l0_btb_pc,
  output wire [ 31:0] ifdp_bht_pc,
  output wire [  1:0] ifdp_ifctrl_l0_way,
  output wire [ 31:0] ifdp_ipdp_vpc,
  output wire [  4:0] ifdp_ipdp_attr,
  output wire [  1:0] ifdp_ipdp_priv_mode,
  output wire [  1:0] ifdp_ipdp_way_pred,
  output wire         ifdp_ipdp_refill_on,
  output wire         ifdp_ipdp_cache_bypass,
  output wire         ifdp_ipdp_fifo,
  output wire         ifdp_ipdp_fault,
  output wire [  3:0] ifdp_ipdp_cause,
  output wire [  3:0] ifdp_ipdp_word_mask,
  output wire [  3:0] ifdp_ipdp_bkpta,
  output wire [  3:0] ifdp_ipdp_bkptb,
  output wire [127:0] ifdp_ipdp_inst_data0,
  output wire [127:0] ifdp_ipdp_inst_data1,
  output wire [ 31:0] ifdp_ipdp_precode0,
  output wire [ 31:0] ifdp_ipdp_precode1,
  output wire [  2:0] ifdp_ipdp_tag_match0,
  output wire [  2:0] ifdp_ipdp_tag_match1,
  output wire         ifdp_ipdp_btb_vld,
  output wire [  3:0] ifdp_ipdp_btb_hit,
  output wire [127:0] ifdp_ipdp_btb_target,
  output wire [  7:0] ifdp_ipdp_btb_way,
  output wire         ifdp_ipdp_l0_hit,
  output wire [  3:0] ifdp_ipdp_l0_index,
  output wire [  1:0] ifdp_ipdp_l0_slot,
  output wire [  2:0] ifdp_ipdp_l0_type,
  output wire [ 31:0] ifdp_ipdp_l0_target,
  output wire [  1:0] ifdp_ipdp_l0_way,
  output wire [  3:0] ifdp_ipdp_no_spec,
  output wire [ 31:0] ifdp_ipdp_seq_pc,
  output wire [127:0] ifdp_ipdp_word_pc,
  output wire [ 15:0] ifdp_ipdp_l0_entry_mask,
  output wire [  3:0] ifdp_ipdp_l0_btb_target_match
);
  localparam PACKET_WIDTH = 576;
  localparam P_VPC = 544;
  localparam P_ATTR = 539;
  localparam P_PRIV_MODE = 537;
  localparam P_WAY_PRED = 535;
  localparam P_REFILL_ON = 534;
  localparam P_CACHE_BYPASS = 533;
  localparam P_FIFO = 532;
  localparam P_FAULT = 531;
  localparam P_CAUSE = 527;
  localparam P_WORD_MASK = 523;
  localparam P_BKPTA = 519;
  localparam P_BKPTB = 515;
  localparam P_INST_DATA0 = 387;
  localparam P_INST_DATA1 = 259;
  localparam P_PRECODE0 = 227;
  localparam P_PRECODE1 = 195;
  localparam P_TAG_MATCH0 = 192;
  localparam P_TAG_MATCH1 = 189;
  localparam P_BTB_VLD = 188;
  localparam P_BTB_HIT = 184;
  localparam P_BTB_TARGET = 56;
  localparam P_BTB_WAY = 48;
  localparam P_L0_HIT = 47;
  localparam P_L0_INDEX = 43;
  localparam P_L0_SLOT = 41;
  localparam P_L0_TYPE = 38;
  localparam P_L0_TARGET = 6;
  localparam P_L0_WAY = 4;
  localparam P_NO_SPEC = 0;

  localparam [1:0] CACHE = 2'd0, FAULT = 2'd1, BYPASS = 2'd2, REFILL = 2'd3;
  localparam META_WIDTH = 213;
  genvar capture;
  genvar way;
  genvar part;
  genvar slot;
  genvar breakpoint;
  genvar entry;
  reg  [  META_WIDTH-1:0] meta_q;
  wire [  META_WIDTH-1:0] meta_nxt;
  wire                    meta_en;
  reg  [PACKET_WIDTH-1:0] packet_q            [0:1];
  wire [PACKET_WIDTH-1:0] packet_nxt          [0:1];
  wire [             1:0] packet_en;
  wire [PACKET_WIDTH-1:0] response_packet;
  wire [PACKET_WIDTH-1:0] selected_packet;
  wire [            31:0] if_pc;
  wire [             4:0] if_attr;
  wire [             1:0] if_priv;
  wire [             1:0] if_way;
  wire [             1:0] if_kind;
  wire                    if_cache_en;
  wire [           127:0] forward_data;
  wire [            31:0] forward_precode;
  wire                    forward_error;
  wire [             3:0] breakpoint_hit      [0:1];
  wire [             3:0] breakpoint_issue_hit[0:1];
  wire [            63:0] breakpoint_base;
  wire [            63:0] breakpoint_mask;
  wire [             1:0] breakpoint_enable;
  wire                    is_cache;
  wire                    is_refill;
  wire                    is_bypass;
  wire                    if_fault;
  wire [             3:0] if_cause;
  wire [             3:0] word_mask;
  wire                    raw_fifo;
  wire                    btb_match;
  wire                    l0_eligible;
  wire [             3:0] sfp_mask;
  wire [           127:0] array_data          [0:1];
  wire [            31:0] array_precode       [0:1];
  wire [  TAG_WIDTH-1:0] array_tag           [0:1];
  wire [           127:0] way_data            [0:1];
  wire [            31:0] way_precode         [0:1];
  wire [             2:0] tag_match           [0:1];

  //----------------------------------------------------------------------------
  // Metadata belongs to the granted request, never to a later live PC bus.
  //----------------------------------------------------------------------------
  assign meta_en = ifctrl_ifdp_issue;
  assign meta_nxt = {
    ifctrl_ifdp_issue_pc,
    region_ifdp_attr,
    cp0_yy_priv_mode,
    ifctrl_ifdp_issue_way,
    ifctrl_ifdp_issue_kind,
    cp0_ifu_icache_en,
    l1_refill_ifdp_inst_data,
    l1_refill_ifdp_precode,
    l1_refill_ifdp_acc_err,
    breakpoint_issue_hit[1],
    breakpoint_issue_hit[0]
  };
  assign {if_pc, if_attr, if_priv, if_way, if_kind, if_cache_en, forward_data, forward_precode,
          forward_error, breakpoint_hit[1], breakpoint_hit[0]} = meta_q;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_meta
    if (!cpurst_b) begin
      meta_q <= {META_WIDTH{1'b0}};
    end else if (meta_en) begin
      meta_q <= meta_nxt;
    end
  end

  assign breakpoint_base   = {had_yy_xx_bkptb_base, had_yy_xx_bkpta_base};
  assign breakpoint_mask   = {had_yy_xx_bkptb_mask, had_yy_xx_bkpta_mask};
  assign breakpoint_enable = {had_ifu_bkptb_en, had_ifu_bkpta_en};
  generate
    for (breakpoint = 0; breakpoint < 2; breakpoint = breakpoint + 1) begin : g_breakpoint
      for (slot = 0; slot < 4; slot = slot + 1) begin : g_slot
        localparam [1:0] SLOT = slot;
        wire [31:0] word_pc;
        assign word_pc = {ifctrl_ifdp_issue_pc[31:4], SLOT, 2'b00};
        // Excel mask bit=1 means ignore this bit.
        assign breakpoint_issue_hit[breakpoint][slot] = breakpoint_enable[breakpoint] &&
          ((word_pc & ~breakpoint_mask[breakpoint*32+:32]) ==
           (breakpoint_base[breakpoint*32+:32] & ~breakpoint_mask[breakpoint*32+:32]));
      end
    end
  endgenerate

  //----------------------------------------------------------------------------
  // Raw IF data selection and partial physical Tag comparisons.
  //----------------------------------------------------------------------------
  assign is_cache         = (if_kind == CACHE);
  assign is_refill        = (if_kind == REFILL);
  assign is_bypass        = (if_kind == BYPASS);
  assign if_fault         = (if_kind == FAULT) || (is_refill && forward_error);
  assign if_cause         = (|if_pc[1:0]) ? 4'd0 : 4'd1;
  assign array_data[0]    = icache_if_ifdp_inst_data0;
  assign array_data[1]    = icache_if_ifdp_inst_data1;
  assign array_precode[0] = icache_if_ifdp_precode0;
  assign array_precode[1] = icache_if_ifdp_precode1;
  assign array_tag[0]     = icache_if_ifdp_tag_data0;
  assign array_tag[1]     = icache_if_ifdp_tag_data1;
  assign raw_fifo         = is_cache && icache_if_ifdp_fifo;
  generate
    for (way = 0; way < 2; way = way + 1) begin : g_way
      assign way_data[way] = if_fault ? 128'b0 : is_refill ? ((way == 0) ? forward_data : 128'b0) :
        array_data[way] & {128{is_cache && if_way[way]}};
      assign way_precode[way] = if_fault ? 32'b0 : is_refill ?
        ((way == 0) ? forward_precode : 32'b0) : array_precode[way] & {32{is_cache && if_way[way]}};
      for (part = 0; part < 3; part = part + 1) begin : g_tag_part
        wire equal_part;
        if (part == 2) begin : g_valid_and_high
          assign equal_part = array_tag[way][TAG_WIDTH-1:16] == {1'b1, if_pc[31 -: TAG_WIDTH-17]};
        end else begin : g_low
          assign equal_part = array_tag[way][part*8+:8] == if_pc[TAG_BASE+part*8+:8];
        end
        assign tag_match[way][part] = !if_fault &&
          ((is_refill && (way == 0)) || (is_cache && if_cache_en && equal_part));
      end
    end
    for (slot = 0; slot < 4; slot = slot + 1) begin : g_word
      localparam [1:0] SLOT = slot;
      assign word_mask[slot] = if_fault ?
        (SLOT == if_pc[3:2]) : (SLOT >= if_pc[3:2]);
      assign ifdp_ipdp_word_pc[slot*32+:32] = {ifdp_ipdp_vpc[31:4], SLOT, 2'b00};
      assign ifdp_ipdp_l0_btb_target_match[slot] = ifdp_ipdp_btb_vld && ifdp_ipdp_btb_hit[slot] &&
        ifdp_ipdp_l0_hit && (ifdp_ipdp_btb_target[slot*32+:32] == ifdp_ipdp_l0_target);
    end
    for (entry = 0; entry < 16; entry = entry + 1) begin : g_l0_entry
      localparam [3:0] ENTRY = entry;
      assign ifdp_ipdp_l0_entry_mask[entry] = ifdp_ipdp_l0_hit && (ifdp_ipdp_l0_index == ENTRY);
    end
  endgenerate

  assign btb_match = btb_ifdp_vld && (btb_ifdp_pc == if_pc) && !if_fault && !is_bypass;
  assign l0_eligible = l0_btb_ifdp_hit && !if_fault && !is_bypass &&
    (l0_btb_ifdp_slot >= if_pc[3:2]) && !(|l0_btb_ifdp_target[1:0]);
  assign sfp_mask = (sfp_ifdp_vld && (sfp_ifdp_pc == if_pc) && !if_fault) ? sfp_ifdp_no_spec : 4'b0;
  assign response_packet = {
    if_pc,
    if_attr,
    if_priv,
    if_way,
    is_refill,
    is_bypass,
    raw_fifo,
    if_fault,
    if_cause,
    word_mask,
    breakpoint_hit[0] & word_mask,
    breakpoint_hit[1] & word_mask,
    way_data[0],
    way_data[1],
    way_precode[0],
    way_precode[1],
    tag_match[0],
    tag_match[1],
    btb_match,
    btb_ifdp_hit & {4{btb_match}},
    btb_ifdp_target & {128{btb_match}},
    btb_ifdp_way & {8{btb_match}},
    l0_eligible,
    l0_btb_ifdp_index,
    l0_btb_ifdp_slot,
    l0_btb_ifdp_type,
    l0_btb_ifdp_target,
    l0_btb_ifdp_way,
    sfp_mask & word_mask
  };

  // First stalled edge saves the complete response before another array owner
  // can overwrite SRAM Q. Subsequent stalls never re-sample changing predictors.
  assign selected_packet = ifctrl_ifdp_held ? packet_q[0] : response_packet;
  assign packet_en = {ifctrl_ifdp_pipedown, ifctrl_ifdp_hold};
  assign packet_nxt[0] = response_packet;
  assign packet_nxt[1] = selected_packet;
  generate
    for (capture = 0; capture < 2; capture = capture + 1) begin : g_capture
      always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_packet
        if (!cpurst_b) begin
          packet_q[capture] <= {PACKET_WIDTH{1'b0}};
        end else if (packet_en[capture]) begin
          packet_q[capture] <= packet_nxt[capture];
        end
      end
    end
  endgenerate
  assign ifdp_ifctrl_fault = selected_packet[P_FAULT];
  // C910 defers speculative RAS/IND repair until the recovery retirement point.
  // A held indirect L0 hint must also be suppressed while that state is unsafe.
  assign ifdp_ifctrl_l0_vld = selected_packet[P_L0_HIT] && !selected_packet[P_FAULT] &&
    !((selected_packet[P_L0_TYPE+:3] == 3'd3) && bp_recovery_stall);
  assign ifdp_ifctrl_l0_target = selected_packet[P_L0_TARGET+:32];
  assign ifdp_ifctrl_l0_way = selected_packet[P_L0_WAY+:2];
  assign ifdp_l0_btb_pc = if_pc;
  assign ifdp_bht_pc = if_pc;
  assign ifdp_ipdp_vpc = packet_q[1][P_VPC+:32];
  assign ifdp_ipdp_attr = packet_q[1][P_ATTR+:5];
  assign ifdp_ipdp_priv_mode = packet_q[1][P_PRIV_MODE+:2];
  assign ifdp_ipdp_way_pred = packet_q[1][P_WAY_PRED+:2];
  assign ifdp_ipdp_refill_on = packet_q[1][P_REFILL_ON+:1];
  assign ifdp_ipdp_cache_bypass = packet_q[1][P_CACHE_BYPASS+:1];
  assign ifdp_ipdp_fifo = packet_q[1][P_FIFO+:1];
  assign ifdp_ipdp_fault = packet_q[1][P_FAULT+:1];
  assign ifdp_ipdp_cause = packet_q[1][P_CAUSE+:4];
  assign ifdp_ipdp_word_mask = packet_q[1][P_WORD_MASK+:4];
  assign ifdp_ipdp_bkpta = packet_q[1][P_BKPTA+:4];
  assign ifdp_ipdp_bkptb = packet_q[1][P_BKPTB+:4];
  assign ifdp_ipdp_inst_data0 = packet_q[1][P_INST_DATA0+:128];
  assign ifdp_ipdp_inst_data1 = packet_q[1][P_INST_DATA1+:128];
  assign ifdp_ipdp_precode0 = packet_q[1][P_PRECODE0+:32];
  assign ifdp_ipdp_precode1 = packet_q[1][P_PRECODE1+:32];
  assign ifdp_ipdp_tag_match0 = packet_q[1][P_TAG_MATCH0+:3];
  assign ifdp_ipdp_tag_match1 = packet_q[1][P_TAG_MATCH1+:3];
  assign ifdp_ipdp_btb_vld = packet_q[1][P_BTB_VLD+:1];
  assign ifdp_ipdp_btb_hit = packet_q[1][P_BTB_HIT+:4];
  assign ifdp_ipdp_btb_target = packet_q[1][P_BTB_TARGET+:128];
  assign ifdp_ipdp_btb_way = packet_q[1][P_BTB_WAY+:8];
  assign ifdp_ipdp_l0_hit = packet_q[1][P_L0_HIT+:1];
  assign ifdp_ipdp_l0_index = packet_q[1][P_L0_INDEX+:4];
  assign ifdp_ipdp_l0_slot = packet_q[1][P_L0_SLOT+:2];
  assign ifdp_ipdp_l0_type = packet_q[1][P_L0_TYPE+:3];
  assign ifdp_ipdp_l0_target = packet_q[1][P_L0_TARGET+:32];
  assign ifdp_ipdp_l0_way = packet_q[1][P_L0_WAY+:2];
  assign ifdp_ipdp_no_spec = packet_q[1][P_NO_SPEC+:4];
  assign ifdp_ipdp_seq_pc = {ifdp_ipdp_vpc[31:4] + 28'd1, 4'b0};
endmodule
