// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/build_cluster.py. Predictor-only integration boundary.
// All top-level PCs are 32-bit byte addresses; only BHT leaf ports use P=PC>>1.
// Stage controls are accepted events from the future IF/IP/IB controllers.

//------------------------------------------------------------------------------
// Verilog-2001 (IEEE Std 1364-2001)
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
module rv32_ifu_bp_top #(parameter STAGED_BHT=0) (

  // Clock, reset and configuration
  input wire  forever_cpuclk,
  input wire  cpurst_b,

  // Execution check and recovery
  input wire  iu_ifu_mispred_stall,

  // Predictor and pipeline interface
  input wire  frontend_cancel,
  input wire  bp_maint_vld,
  input wire [4:0] bp_maint_mask,
  output wire  bp_init_done,
  output wire  bp_maint_ready,
  output wire  bp_maint_done,
  output wire  bp_recovery_stall,

  // Retirement interface
  input wire  rtu_ifu_retire0_vld,
  input wire  rtu_ifu_retire1_vld,
  input wire  rtu_ifu_retire2_vld,

  // Predictor and pipeline interface
  input wire [31:0] if_pc,
  input wire [31:0] if_query_pc,
  input wire [7:0] ib_query_ghr,
  input wire [31:0] ip_pc,
  input wire [31:0] ib_pred_target,
  input wire  local_recover_vld,
  input wire [21:0] local_recover_ghr,
  output wire  bht_train_drop,
  output wire [31:0] bht_train_drop_count,

  // Clock, reset and configuration
  input wire  cp0_ifu_bht_en,
  input wire  cp0_ifu_icg_en,
  input wire  cp0_yy_clk_en,

  // Predictor and pipeline interface
  input wire  ifctrl_bht_pipedown,
  input wire  ifctrl_bht_stall,
  input wire  ipctrl_bht_con_br_gateclk_en,
  input wire  ipctrl_bht_con_br_taken,
  input wire  ipctrl_bht_con_br_vld,
  input wire  ipctrl_bht_more_br,
  input wire  ipctrl_bht_vld,

  // Execution check and recovery
  input wire  iu_ifu_bht_check_vld,
  input wire  iu_ifu_bht_condbr_taken,
  input wire  iu_ifu_bht_pred,
  input wire  iu_ifu_chgflw_vld,
  input wire [24:0] iu_ifu_chk_idx,
  input wire [31:0] iu_ifu_cur_pc,

  // Predictor and pipeline interface
  input wire  lbuf_bht_active_state,
  input wire  lbuf_bht_con_br_taken,
  input wire  lbuf_bht_con_br_vld,

  // Clock, reset and configuration
  input wire  pad_yy_icg_scan_en,

  // Predictor and pipeline interface
  input wire  pcgen_bht_chgflw,
  input wire  pcgen_bht_chgflw_short,
  input wire  pcgen_bht_seq_read,

  // Retirement interface
  input wire  rtu_ifu_flush,
  input wire  rtu_ifu_retire0_condbr,
  input wire  rtu_ifu_retire0_condbr_taken,
  input wire  rtu_ifu_retire1_condbr,
  input wire  rtu_ifu_retire1_condbr_taken,
  input wire  rtu_ifu_retire2_condbr,
  input wire  rtu_ifu_retire2_condbr_taken,

  // Predictor and pipeline interface
  output wire [31:0] bht_ipdp_pre_array_data_ntake,
  output wire [31:0] bht_ipdp_pre_array_data_taken,
  output wire [15:0] bht_ipdp_pre_offset_onehot,
  output wire [1:0] bht_ipdp_sel_array_result,
  output wire [21:0] bht_ipdp_vghr,
  output wire [31:0] bht_lbuf_pre_ntaken_result,
  output wire [31:0] bht_lbuf_pre_taken_result,
  output wire [21:0] bht_lbuf_vghr,
  output wire  ras_top_valid,

  // Clock, reset and configuration
  input wire  cp0_ifu_ras_en,
  input wire [1:0] cp0_yy_priv_mode,

  // Predictor and pipeline interface
  input wire  ibctrl_ras_inst_pcall,
  input wire  ibctrl_ras_pcall_vld,
  input wire  ibctrl_ras_pcall_vld_for_gateclk,
  input wire  ibctrl_ras_preturn_vld,
  input wire  ibctrl_ras_preturn_vld_for_gateclk,
  input wire [31:0] ibdp_ras_push_pc,

  // Retirement interface
  input wire [31:0] rtu_ifu_retire0_inc_pc,
  input wire  rtu_ifu_retire0_mispred,
  input wire  rtu_ifu_retire0_pcall,
  input wire  rtu_ifu_retire0_preturn,

  // Predictor and pipeline interface
  output wire  ras_ipdp_data_vld,
  output wire [31:0] ras_ipdp_pc,
  output wire [31:0] ras_l0_btb_pc,
  output wire [31:0] ras_l0_btb_push_pc,
  output wire  ras_l0_btb_ras_push,
  output wire  ind_result_vld,

  // Clock, reset and configuration
  input wire  cp0_ifu_ind_btb_en,

  // Predictor and pipeline interface
  input wire  ibctrl_ind_btb_check_vld,
  input wire  ibctrl_ind_btb_fifo_stall,
  input wire  ipctrl_ind_btb_con_br_vld,
  input wire  ipdp_ind_btb_jmp_detect,

  // Retirement interface
  input wire [7:0] rtu_ifu_retire0_chk_idx,
  input wire  rtu_ifu_retire0_jmp,
  input wire  rtu_ifu_retire0_jmp_mispred,
  input wire [31:0] rtu_ifu_retire0_next_pc,
  input wire [7:0] rtu_ifu_retire1_chk_idx,
  input wire  rtu_ifu_retire1_jmp,
  input wire [7:0] rtu_ifu_retire2_chk_idx,
  input wire  rtu_ifu_retire2_jmp,

  // Predictor and pipeline interface
  output wire [34:0] ind_btb_ibctrl_dout,
  output wire [1:0] ind_btb_ibctrl_priv_mode,

  // Clock, reset and configuration
  input wire  cp0_ifu_btb_en,

  // Predictor and pipeline interface
  input wire  btb_lookup_vld,
  output wire  btb_lookup_ready,
  input wire [31:0] btb_lookup_pc,
  output wire  btb_result_vld,
  output wire [3:0] btb_hit,
  output wire [127:0] btb_target,
  output wire [7:0] btb_way_hint,
  input wire  btb_update_vld,
  output wire  btb_update_ready,
  input wire [31:0] btb_update_pc,
  input wire [31:0] btb_update_target,
  input wire [1:0] btb_update_way,
  output wire  btb_if_vld,
  output wire [31:0] btb_if_pc,
  output wire [3:0] btb_if_hit,
  output wire [127:0] btb_if_target,
  output wire [7:0] btb_if_way_hint,

  // Clock, reset and configuration
  input wire  cp0_ifu_l0btb_en,

  // Predictor and pipeline interface
  input wire  l0_lookup_vld,
  input wire [31:0] l0_lookup_pc,
  output wire  l0_hit,
  output wire [3:0] l0_hit_index,
  output wire [1:0] l0_hit_slot,
  output wire [2:0] l0_hit_type,
  output wire [31:0] l0_target,
  output wire [1:0] l0_way_hint,
  input wire  l0_update_vld,
  input wire [31:0] l0_update_pc,
  input wire [31:0] l0_update_target,
  input wire [2:0] l0_update_type,
  input wire  l0_update_taken,
  input wire  l0_update_ras,
  input wire [1:0] l0_update_way,
  input wire  l0_directed_inv_vld,
  input wire [15:0] l0_directed_inv_mask,
  output wire  bht_pred,
  output wire [24:0] bht_chk_idx,
  output wire  ind_target_valid,
  output wire [31:0] ind_target
);

//------------------------------------------------------------------------------
// Net declarations
//------------------------------------------------------------------------------
wire  bht_ifctrl_inv_done;
wire  bht_ifctrl_inv_on;
wire [7:0] bht_ind_btb_rtu_ghr;
wire [7:0] bht_ind_btb_vghr;
wire  raw_ras_top_valid;
wire  raw_ras_ipdp_data_vld;
wire  raw_ind_result_vld;
wire  ind_btb_ifctrl_inv_done;
wire  ind_btb_ifctrl_inv_on;
wire  btb_init_done;
reg [2:0] state_q;
reg [4:0] saved_mask_q;
reg done_pulse_q;
wire  maint_fire;
wire  start_invalidate;
wire [4:0] active_mask;
wire  arrays_done;
wire  frontend_ok;
wire [31:0] bht_selected;
reg [1:0] bht_counter;
integer k;

//------------------------------------------------------------------------------
// Combinational logic and register updates
//------------------------------------------------------------------------------
assign maint_fire = bp_maint_vld && bp_maint_ready;
assign start_invalidate = (state_q==0 || state_q==3);
assign active_mask = (state_q==0 || state_q==1) ? 5'b11111 : saved_mask_q;
assign arrays_done = bht_ifctrl_inv_done && ind_btb_ifctrl_inv_done && btb_init_done;
assign frontend_ok = bp_init_done && !frontend_cancel && !maint_fire
                     && !rtu_ifu_flush && !iu_ifu_chgflw_vld && (STAGED_BHT || !local_recover_vld);
assign bht_selected = bht_ipdp_sel_array_result[1]
                            ? bht_ipdp_pre_array_data_taken : bht_ipdp_pre_array_data_ntake;

  assign bp_init_done = state_q==2;

  assign bp_maint_ready = state_q==2 && !rtu_ifu_flush && !iu_ifu_chgflw_vld;

  assign bp_maint_done = done_pulse_q;

  assign bp_recovery_stall = iu_ifu_mispred_stall;

  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_state

    if (!cpurst_b) begin state_q<=0; saved_mask_q<=0; done_pulse_q<=0; end
    else begin
      done_pulse_q<=0;
      case(state_q)
        0: state_q<=1;
        1: if (arrays_done) begin
state_q<=2;
end

        2: if (maint_fire) begin saved_mask_q<=bp_maint_mask; state_q<=3; end
        3: state_q<=4;
        4: if (arrays_done) begin state_q<=2; done_pulse_q<=1; end
        default: state_q<=0;
      endcase
    end
end

  assign ras_top_valid = raw_ras_top_valid && frontend_ok && !bp_recovery_stall;

  assign ras_ipdp_data_vld = raw_ras_ipdp_data_vld && frontend_ok && !bp_recovery_stall;

  assign ind_result_vld = raw_ind_result_vld && frontend_ok && !bp_recovery_stall;

  assign ind_target_valid = ind_result_vld && ind_btb_ibctrl_dout[34]
                            && ind_btb_ibctrl_dout[33:32]==cp0_yy_priv_mode
                            && ind_btb_ibctrl_priv_mode==cp0_yy_priv_mode
                            && ind_btb_ibctrl_dout[1:0]==0;

  assign ind_target = ind_btb_ibctrl_dout[31:0];

  always @(*) begin : p_bht_counter_comb
bht_counter=0;
for(k=0;k<16;k=k+1)
      begin
bht_counter=bht_counter | ({2{bht_ipdp_pre_offset_onehot[k]}} & bht_selected[k*2+:2]);
end
end

  assign bht_pred = cp0_ifu_bht_en && bht_counter[1];

  assign bht_chk_idx = {bht_counter[0],bht_ipdp_sel_array_result,bht_ipdp_vghr};

  rv32_ifu_bht u_bht (
    .local_recover_vld((local_recover_vld && bp_init_done && !maint_fire)),
    .local_recover_ghr(local_recover_ghr),
    .bht_train_drop(bht_train_drop),
    .bht_train_drop_count(bht_train_drop_count),
    .cp0_ifu_bht_en(cp0_ifu_bht_en),
    .cp0_ifu_icg_en(cp0_ifu_icg_en),
    .cp0_yy_clk_en(cp0_yy_clk_en),
    .cpurst_b(cpurst_b),
    .forever_cpuclk(forever_cpuclk),
    .ifctrl_bht_inv(start_invalidate && active_mask[2]),
    .ifctrl_bht_pipedown((ifctrl_bht_pipedown && frontend_ok)),
    .ifctrl_bht_stall(ifctrl_bht_stall),
    .ipctrl_bht_con_br_gateclk_en((ipctrl_bht_con_br_gateclk_en && frontend_ok)),
    .ipctrl_bht_con_br_taken(ipctrl_bht_con_br_taken),
    .ipctrl_bht_con_br_vld((ipctrl_bht_con_br_vld && frontend_ok)),
    .ipctrl_bht_more_br(ipctrl_bht_more_br),
    .ipctrl_bht_vld(ipctrl_bht_vld),
    .ipdp_bht_vpc(ip_pc[31:1]),
    .iu_ifu_bht_check_vld((iu_ifu_bht_check_vld && bp_init_done && !maint_fire)),
    .iu_ifu_bht_condbr_taken(iu_ifu_bht_condbr_taken),
    .iu_ifu_bht_pred(iu_ifu_bht_pred),
    .iu_ifu_chgflw_vld((iu_ifu_chgflw_vld && bp_init_done)),
    .iu_ifu_chk_idx(iu_ifu_chk_idx),
    .iu_ifu_cur_pc(iu_ifu_cur_pc[31:1]),
    .lbuf_bht_active_state(lbuf_bht_active_state),
    .lbuf_bht_con_br_taken(lbuf_bht_con_br_taken),
    .lbuf_bht_con_br_vld((lbuf_bht_con_br_vld && frontend_ok)),
    .pad_yy_icg_scan_en(pad_yy_icg_scan_en),
    .pcgen_bht_chgflw((pcgen_bht_chgflw && frontend_ok)),
    .pcgen_bht_chgflw_short((pcgen_bht_chgflw_short && frontend_ok)),
    .pcgen_bht_ifpc(if_pc[7:1]),
    .pcgen_bht_pcindex((STAGED_BHT ? if_query_pc[13:4] : if_pc[13:4])),
    .pcgen_bht_seq_read((pcgen_bht_seq_read && frontend_ok)),
    .rtu_ifu_flush((rtu_ifu_flush || maint_fire)),
    .rtu_ifu_retire0_condbr((rtu_ifu_retire0_condbr && rtu_ifu_retire0_vld)),
    .rtu_ifu_retire0_condbr_taken(rtu_ifu_retire0_condbr_taken),
    .rtu_ifu_retire1_condbr((rtu_ifu_retire1_condbr && rtu_ifu_retire1_vld)),
    .rtu_ifu_retire1_condbr_taken(rtu_ifu_retire1_condbr_taken),
    .rtu_ifu_retire2_condbr((rtu_ifu_retire2_condbr && rtu_ifu_retire2_vld)),
    .rtu_ifu_retire2_condbr_taken(rtu_ifu_retire2_condbr_taken),
    .bht_ifctrl_inv_done(bht_ifctrl_inv_done),
    .bht_ifctrl_inv_on(bht_ifctrl_inv_on),
    .bht_ind_btb_rtu_ghr(bht_ind_btb_rtu_ghr),
    .bht_ind_btb_vghr(bht_ind_btb_vghr),
    .bht_ipdp_pre_array_data_ntake(bht_ipdp_pre_array_data_ntake),
    .bht_ipdp_pre_array_data_taken(bht_ipdp_pre_array_data_taken),
    .bht_ipdp_pre_offset_onehot(bht_ipdp_pre_offset_onehot),
    .bht_ipdp_sel_array_result(bht_ipdp_sel_array_result),
    .bht_ipdp_vghr(bht_ipdp_vghr),
    .bht_lbuf_pre_ntaken_result(bht_lbuf_pre_ntaken_result),
    .bht_lbuf_pre_taken_result(bht_lbuf_pre_taken_result),
    .bht_lbuf_vghr(bht_lbuf_vghr)
  );

  rv32_ifu_ras u_ras (
    .ras_top_valid(raw_ras_top_valid),
    .ras_clear(start_invalidate && active_mask[4]),
    .cp0_ifu_icg_en(cp0_ifu_icg_en),
    .cp0_ifu_ras_en(cp0_ifu_ras_en),
    .cp0_yy_clk_en(cp0_yy_clk_en),
    .cp0_yy_priv_mode(cp0_yy_priv_mode),
    .cpurst_b(cpurst_b),
    .forever_cpuclk(forever_cpuclk),
    .ibctrl_ras_inst_pcall((ibctrl_ras_inst_pcall && frontend_ok && !bp_recovery_stall)),
    .ibctrl_ras_pcall_vld((ibctrl_ras_pcall_vld && frontend_ok && !bp_recovery_stall)),
    .ibctrl_ras_pcall_vld_for_gateclk((ibctrl_ras_pcall_vld_for_gateclk && frontend_ok && !bp_recovery_stall)),
    .ibctrl_ras_preturn_vld((ibctrl_ras_preturn_vld && frontend_ok && !bp_recovery_stall)),
    .ibctrl_ras_preturn_vld_for_gateclk((ibctrl_ras_preturn_vld_for_gateclk && frontend_ok && !bp_recovery_stall)),
    .ibdp_ras_push_pc(ibdp_ras_push_pc),
    .pad_yy_icg_scan_en(pad_yy_icg_scan_en),
    .rtu_ifu_flush((rtu_ifu_flush || maint_fire)),
    .rtu_ifu_retire0_inc_pc(rtu_ifu_retire0_inc_pc),
    .rtu_ifu_retire0_mispred((rtu_ifu_retire0_mispred && rtu_ifu_retire0_vld)),
    .rtu_ifu_retire0_pcall((rtu_ifu_retire0_pcall && rtu_ifu_retire0_vld)),
    .rtu_ifu_retire0_preturn((rtu_ifu_retire0_preturn && rtu_ifu_retire0_vld)),
    .ras_ipdp_data_vld(raw_ras_ipdp_data_vld),
    .ras_ipdp_pc(ras_ipdp_pc),
    .ras_l0_btb_pc(ras_l0_btb_pc),
    .ras_l0_btb_push_pc(ras_l0_btb_push_pc),
    .ras_l0_btb_ras_push(ras_l0_btb_ras_push)
  );

  rv32_ifu_ind_btb u_ind_btb (
    .cancel(!frontend_ok),
    .ind_result_vld(raw_ind_result_vld),
    .bht_ind_btb_rtu_ghr(bht_ind_btb_rtu_ghr),
    .bht_ind_btb_vghr((STAGED_BHT ? ib_query_ghr : bht_ind_btb_vghr)),
    .cp0_ifu_icg_en(cp0_ifu_icg_en),
    .cp0_ifu_ind_btb_en(cp0_ifu_ind_btb_en),
    .cp0_yy_clk_en(cp0_yy_clk_en),
    .cp0_yy_priv_mode(cp0_yy_priv_mode),
    .cpurst_b(cpurst_b),
    .forever_cpuclk(forever_cpuclk),
    .ibctrl_ind_btb_check_vld((ibctrl_ind_btb_check_vld && frontend_ok && !bp_recovery_stall)),
    .ibctrl_ind_btb_fifo_stall((ibctrl_ind_btb_fifo_stall || bp_recovery_stall || !frontend_ok)),
    .ibctrl_ind_btb_path(ib_pred_target[11:4]),
    .ifctrl_ind_btb_inv(start_invalidate && active_mask[3]),
    .ipctrl_ind_btb_con_br_vld((ipctrl_ind_btb_con_br_vld && frontend_ok)),
    .ipdp_ind_btb_jmp_detect((ipdp_ind_btb_jmp_detect && frontend_ok && !bp_recovery_stall)),
    .pad_yy_icg_scan_en(pad_yy_icg_scan_en),
    .rtu_ifu_flush((rtu_ifu_flush || maint_fire)),
    .rtu_ifu_retire0_chk_idx(rtu_ifu_retire0_chk_idx),
    .rtu_ifu_retire0_jmp((rtu_ifu_retire0_jmp && rtu_ifu_retire0_vld)),
    .rtu_ifu_retire0_jmp_mispred((rtu_ifu_retire0_jmp_mispred && rtu_ifu_retire0_vld)),
    .rtu_ifu_retire0_mispred((rtu_ifu_retire0_mispred && rtu_ifu_retire0_vld)),
    .rtu_ifu_retire0_next_pc(rtu_ifu_retire0_next_pc),
    .rtu_ifu_retire1_chk_idx(rtu_ifu_retire1_chk_idx),
    .rtu_ifu_retire1_jmp((rtu_ifu_retire1_jmp && rtu_ifu_retire1_vld)),
    .rtu_ifu_retire2_chk_idx(rtu_ifu_retire2_chk_idx),
    .rtu_ifu_retire2_jmp((rtu_ifu_retire2_jmp && rtu_ifu_retire2_vld)),
    .ind_btb_ibctrl_dout(ind_btb_ibctrl_dout),
    .ind_btb_ibctrl_priv_mode(ind_btb_ibctrl_priv_mode),
    .ind_btb_ifctrl_inv_done(ind_btb_ifctrl_inv_done),
    .ind_btb_ifctrl_inv_on(ind_btb_ifctrl_inv_on)
  );

  rv32_ifu_btb u_btb (
    .forever_cpuclk(forever_cpuclk),
    .cpurst_b(cpurst_b),
    .invalidate(start_invalidate && active_mask[1]),
    .enable(cp0_ifu_btb_en),
    .lookup_vld((btb_lookup_vld && frontend_ok)),
    .lookup_ready(btb_lookup_ready),
    .lookup_pc(btb_lookup_pc),
    .result_vld(btb_result_vld),
    .hit(btb_hit),
    .target(btb_target),
    .way_hint(btb_way_hint),
    .update_vld((btb_update_vld && frontend_ok)),
    .update_ready(btb_update_ready),
    .update_pc(btb_update_pc),
    .update_target(btb_update_target),
    .update_way(btb_update_way),
    .if_vld(btb_if_vld),
    .if_pc(btb_if_pc),
    .if_hit(btb_if_hit),
    .if_target(btb_if_target),
    .if_way_hint(btb_if_way_hint),
    .init_done(btb_init_done),
    .cancel(!frontend_ok)
  );

  rv32_ifu_l0_btb u_l0 (
    .forever_cpuclk(forever_cpuclk),
    .cpurst_b(cpurst_b),
    .invalidate(start_invalidate && active_mask[0]),
    .enable(cp0_ifu_l0btb_en),
    .lookup_vld((l0_lookup_vld && frontend_ok)),
    .lookup_pc(l0_lookup_pc),
    .hit(l0_hit),
    .hit_index(l0_hit_index),
    .hit_slot(l0_hit_slot),
    .hit_type(l0_hit_type),
    .target(l0_target),
    .way_hint(l0_way_hint),
    .update_vld((l0_update_vld && frontend_ok)),
    .update_pc(l0_update_pc),
    .update_target(l0_update_target),
    .update_type(l0_update_type),
    .update_taken(l0_update_taken),
    .update_ras(l0_update_ras),
    .update_way(l0_update_way),
    .directed_inv_vld(l0_directed_inv_vld),
    .directed_inv_mask(l0_directed_inv_mask),
    .cancel(!frontend_ok),
    .ras_valid(ras_top_valid && !bp_recovery_stall),
    .ras_target(ras_l0_btb_pc)
  );
endmodule
