// SPDX-License-Identifier: Apache-2.0
// RV32I adaptation of C910 refill/IPB responsibilities; no Cache lookup FSM.
// Generated by scripts/build_memory.py. All PCs are physical byte addresses.
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
// [ICACHE 参数化] 与 rv32_ifu_icache_if.v 同套 define/公式; 默认 = 1 KiB/16 B 行。
`ifdef ICACHE_BYTES
  `define IC_BYTES_VAL `ICACHE_BYTES
`else
  `define IC_BYTES_VAL 1024
`endif
`ifdef ICACHE_LINE_BYTES
  `define IC_LINE_VAL `ICACHE_LINE_BYTES
`else
  `define IC_LINE_VAL 16
`endif

module rv32_ifu_ipb #(
  parameter IC_BYTES  = `IC_BYTES_VAL,
  parameter IC_LINE   = `IC_LINE_VAL,
  parameter IC_SETS   = IC_BYTES/(2*IC_LINE),
  parameter SET_BITS  = $clog2(IC_SETS),
  parameter LINE_BITS = $clog2(IC_LINE),
  parameter TAG_BITS  = 32 - SET_BITS - LINE_BITS,
  parameter TAG_WIDTH = 1 + TAG_BITS,
  parameter TAG_BASE  = 32 - TAG_BITS,
  parameter BEATS     = IC_LINE/16
) (
  input wire forever_cpuclk,
  input wire cpurst_b,
  input wire enable,
  input wire stop,
  input wire invalidate,
  input wire trigger,
  input wire [31:0] trigger_pc,
  output wire [31:0] region_pc,
  input wire [4:0] region_attr,
  output wire ipb_array_req,
  input wire ifctrl_ipb_grant,
  input wire [TAG_WIDTH-1:0] icache_if_ipb_tag_data0,
  input wire [TAG_WIDTH-1:0] icache_if_ipb_tag_data1,
  output wire [31:0] ipb_icache_if_index,
  output wire ipb_icache_if_req,
  output wire ipb_icache_if_req_for_gateclk,
  output wire memory_request,
  input wire memory_grant,
  output wire [31:0] memory_pc,
  output wire [4:0] memory_attr,
  input wire memory_valid,
  input wire memory_error,
  input wire memory_last,
  input wire [127:0] memory_data,
  output wire memory_ready,
  input wire demand_request,
  input wire [31:0] demand_pc,
  output wire demand_match,
  output wire demand_grant,
  output wire replay_valid,
  output wire replay_last,
  output wire [127:0] replay_data,
  input wire replay_ready,
  output wire idle,
  output wire launch,
  output wire demand_hit
);
  wire [1:0] demand_beat;
  wire [32:0] next_line;
  wire eligible,start,tag_hit,receive,take_replay,replay_end,match_line;
  reg [127:0] block_q [0:3];
  wire [127:0] block_nxt [0:3];
  wire [3:0] block_en;
  genvar block_index;
  reg [2:0] state_q;
  wire [2:0] state_nxt;
  wire state_en;
  reg [31:0] pc_q;
  wire [31:0] pc_nxt;
  wire pc_en;
  reg [4:0] attr_q;
  wire [4:0] attr_nxt;
  wire attr_en;
  reg [1:0] count_q;
  wire [1:0] count_nxt;
  wire count_en;
  reg error_q;
  wire error_nxt;
  wire error_en;
  reg killed_q;
  wire killed_nxt;
  wire killed_en;
  reg [1:0] replay_count_q;
  wire [1:0] replay_count_nxt;
  wire replay_count_en;
  reg [1:0] replay_offset_q;
  wire [1:0] replay_offset_nxt;
  wire replay_offset_en;

  localparam [2:0] IDLE=0,CACHE=1,CMP=2,REQ=3,FILL=4,VALID=5,REPLAY=6;
  // [ICACHE 参数化] 行粒度; 16 B 行时预取的是下一个 16 B 行(原来固定 64 B ⇒ 1 KB 表被灌 4 倍数据)
  wire [32:0] line_inc = IC_LINE;   // 参数不能直接写进 sized literal
  assign next_line={1'b0,trigger_pc[31:LINE_BITS],{LINE_BITS{1'b0}}}+line_inc;
  assign region_pc=next_line[31:0];
  assign eligible=enable && !stop && !invalidate && !next_line[32] &&
    next_line[31:12]==trigger_pc[31:12] && region_attr[4] && region_attr[3] && region_attr[0];
  assign start=trigger && state_q==IDLE && eligible;
  assign idle=state_q==IDLE || state_q==VALID;
  assign ipb_array_req=state_q==CACHE && !invalidate;
  assign ipb_icache_if_req=ipb_array_req;
  assign ipb_icache_if_req_for_gateclk=ipb_array_req;
  assign ipb_icache_if_index=pc_q;
  assign tag_hit=icache_if_ipb_tag_data0=={1'b1,pc_q[31:TAG_BASE]} ||
                 icache_if_ipb_tag_data1=={1'b1,pc_q[31:TAG_BASE]};
  assign memory_request=state_q==REQ && !invalidate && !stop;
  assign memory_pc=pc_q;
  assign memory_attr=attr_q;
  assign launch=memory_request && memory_grant;
  assign memory_ready=state_q==FILL;
  assign receive=memory_valid && memory_ready;
  assign match_line=demand_pc[31:LINE_BITS]==pc_q[31:LINE_BITS];
  assign demand_match=!invalidate && !killed_q && match_line &&
    (state_q==CACHE || state_q==CMP || state_q==REQ || state_q==FILL || state_q==VALID);
  assign demand_grant=demand_request && demand_match && state_q==VALID;
  assign demand_hit=demand_grant;
  assign replay_valid=state_q==REPLAY;
  assign replay_last=replay_count_q==(BEATS-1);
  assign replay_data=block_q[replay_offset_q];
  assign take_replay=replay_valid && replay_ready;
  assign replay_end=take_replay && replay_last;
  generate
    for(block_index=0;block_index<4;block_index=block_index+1) begin : g_block
      assign block_en[block_index]=receive && count_q==block_index;
      assign block_nxt[block_index]=memory_data;
      always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_block
        if(!cpurst_b) block_q[block_index]<=128'b0;
        else if(block_en[block_index]) block_q[block_index]<=block_nxt[block_index];
      end
    end
  endgenerate
  assign state_en=1'b1;
  assign state_nxt=(invalidate && state_q!=FILL && state_q!=REPLAY) ? IDLE :
      start ? CACHE : (state_q==CACHE && ifctrl_ipb_grant) ? CMP :
      state_q==CMP ? (tag_hit ? IDLE : REQ) : (state_q==REQ && stop) ? IDLE :
      launch ? FILL : (receive && memory_last) ?
        // [ICACHE 参数化] 行长按 BEATS 判; 原来写死 3 ⇒ 16 B 行(count_q 到不了 3)
        // 永远进不了 VALID ⇒ 预取的行永远不能被复用
        ((error_q || memory_error || killed_q || invalidate || count_q!=(BEATS-1)) ? IDLE : VALID) :
      demand_grant ? REPLAY : replay_end ? IDLE : state_q;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_state
    if(!cpurst_b) state_q<=IDLE;
    else if(state_en) state_q<=state_nxt;
  end
  assign pc_en=start;
  assign pc_nxt=next_line[31:0];
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_pc
    if(!cpurst_b) pc_q<=32'b0;
    else if(pc_en) pc_q<=pc_nxt;
  end
  assign attr_en=start;
  assign attr_nxt=region_attr;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_attr
    if(!cpurst_b) attr_q<=5'b0;
    else if(attr_en) attr_q<=attr_nxt;
  end
  assign count_en=start || receive;
  assign count_nxt=start ? 2'b0 : count_q+2'd1;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_count
    if(!cpurst_b) count_q<=2'b0;
    else if(count_en) count_q<=count_nxt;
  end
  assign error_en=start || receive;
  assign error_nxt=!start && (error_q || memory_error);
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_error
    if(!cpurst_b) error_q<=1'b0;
    else if(error_en) error_q<=error_nxt;
  end
  assign killed_en=start || invalidate;
  assign killed_nxt=!start;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_killed
    if(!cpurst_b) killed_q<=1'b0;
    else if(killed_en) killed_q<=killed_nxt;
  end
  assign replay_count_en=demand_grant || take_replay;
  assign replay_count_nxt=demand_grant ? 2'b0 : replay_count_q+2'd1;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_replay_count
    if(!cpurst_b) replay_count_q<=2'b0;
    else if(replay_count_en) replay_count_q<=replay_count_nxt;
  end
  assign replay_offset_en=demand_grant || take_replay;
  // 行内起始拍号: 64 B 行取 PA[5:4]; 16 B 行只有一拍 ⇒ 恒 0
  generate
    if (BEATS > 1) begin : g_demand_beat
      assign demand_beat = demand_pc[LINE_BITS-1:4];
    end else begin : g_no_beat
      assign demand_beat = 2'b0;
    end
  endgenerate
  assign replay_offset_nxt=demand_grant ? demand_beat : replay_offset_q+2'd1;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_replay_offset
    if(!cpurst_b) replay_offset_q<=2'b0;
    else if(replay_offset_en) replay_offset_q<=replay_offset_nxt;
  end

endmodule
