// SPDX-License-Identifier: Apache-2.0
// RV32I word-stage adaptation of the corresponding C910 IFU stage duties.
// Generated by scripts/build_pipeline.py. See doc/pipeline_zh.md.
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
module rv32_ifu_addrgen (
  input  wire [191:0] source_packet,
  input  wire         ras_valid,
  input  wire         ind_valid,
  input  wire [ 31:0] ras_target,
  input  wire [ 31:0] ind_target,
  output wire [191:0] result_packet,
  output wire         correction,
  output wire [ 31:0] corrected_pc,
  output wire [ 21:0] retained_ghr
);

  // The source is the registered IP/IB packet. Validate static targets here,
  // before any token allocation or irreversible IB acceptance.
  wire [2:0] kind;
  wire [31:0] pc, link, chosen, npc, recorded;
  wire direct, jalr, available, bad, taken, unknown;
  wire [127:0] instruction;
  assign kind = source_packet[108:106];
  assign pc = source_packet[63:32];
  assign link = pc + 32'd4;
  assign direct = kind == 1 || kind == 2;
  assign jalr = kind == 3;
  assign available = (source_packet[189] && ras_valid) || ind_valid || source_packet[190];
  assign chosen = (source_packet[189] && ras_valid) ? ras_target :
    ind_valid ? ind_target : source_packet[95:64];
  assign bad = jalr ? (|chosen[1:0]) : (|source_packet[129:128]);
  assign unknown = jalr && (!available || bad);
  assign taken = jalr ? !unknown : source_packet[122];
  assign npc = jalr ?
    (unknown ? link : chosen) : (direct && taken && !bad) ? source_packet[159:128] : link;
  assign recorded = jalr ? (unknown ? link : chosen) : source_packet[159:128];
  assign instruction = {
    source_packet[127:123], taken, source_packet[121:96], npc, source_packet[63:0]
  };
  assign result_packet = {
    source_packet[191:187], unknown, source_packet[185:160], recorded, instruction
  };
  assign correction = !source_packet[96] && npc != source_packet[95:64];
  assign corrected_pc = npc;
  assign retained_ghr = kind == 1 ? {source_packet[180:160], source_packet[122]} :
    source_packet[181:160];

endmodule
