// SPDX-License-Identifier: Apache-2.0
// RV32I adaptation of C910 refill/IPB responsibilities; no Cache lookup FSM.
// Generated by scripts/build_memory.py. All PCs are physical byte addresses.
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
// [ICACHE 参数化] 回填拍数按行大小推导; 默认 = 原 64 B 行(4 拍)。
`ifdef ICACHE_LINE_BYTES
  `define IC_LINE_VAL `ICACHE_LINE_BYTES
`else
  `define IC_LINE_VAL 16
`endif

module rv32_ifu_biu #(
  parameter IC_LINE = `IC_LINE_VAL,
  parameter BEATS   = IC_LINE/16
) (
  input  wire         forever_cpuclk,
  input  wire         cpurst_b,
  input  wire         demand_request,
  input  wire         prefetch_request,
  input  wire         demand_allocate,
  input  wire [ 31:0] demand_pc,
  input  wire [ 31:0] prefetch_pc,
  input  wire [  4:0] demand_attr,
  input  wire [  4:0] prefetch_attr,
  input  wire [  1:0] demand_priv,
  input  wire [  1:0] cp0_yy_priv_mode,
  input  wire         cp0_ifu_insde,
  input  wire         prefetch_match,
  input  wire         prefetch_replay_grant,
  output wire         demand_grant,
  output wire         prefetch_grant,
  input  wire         demand_ready,
  input  wire         prefetch_ready,
  output wire         demand_valid,
  output wire         prefetch_valid,
  output wire [127:0] response_data,
  output wire         response_error,
  output wire         response_last,
  output wire         ifu_biu_rd_req,
  output wire         ifu_biu_rd_req_gate,
  output wire         ifu_biu_rd_id,
  output wire [ 31:0] ifu_biu_rd_addr,
  output wire [  1:0] ifu_biu_rd_len,
  output wire [  1:0] ifu_biu_rd_burst,
  output wire [  1:0] ifu_biu_rd_domain,
  output wire [  1:0] ifu_biu_rd_user,
  output wire [  2:0] ifu_biu_rd_size,
  output wire [  2:0] ifu_biu_rd_prot,
  output wire [  3:0] ifu_biu_rd_cache,
  output wire [  3:0] ifu_biu_rd_snoop,
  input  wire         biu_ifu_rd_grnt,
  input  wire         biu_ifu_rd_data_vld,
  input  wire         biu_ifu_rd_id,
  input  wire         biu_ifu_rd_last,
  input  wire [127:0] biu_ifu_rd_data,
  input  wire [  1:0] biu_ifu_rd_resp,
  output wire         ifu_biu_r_ready,
  output wire         idle
);
  reg [1:0] outstanding_q;
  wire [1:0] outstanding_nxt, outstanding_en;
  wire select_demand, select_prefetch;
  wire [4:0] attr;
  wire [1:0] priv;
  wire allocate, response_fire;
  genvar id;

  assign select_demand = demand_request && !prefetch_match && !outstanding_q[0];
  assign select_prefetch = prefetch_request && !outstanding_q[1] && !select_demand;
  assign ifu_biu_rd_req = cpurst_b && (select_demand || select_prefetch);
  assign ifu_biu_rd_req_gate = ifu_biu_rd_req;
  assign ifu_biu_rd_id = select_prefetch;
  assign ifu_biu_rd_addr = select_demand ? {demand_pc[31:4], 4'b0} : prefetch_pc;
  assign allocate = select_prefetch || demand_allocate;
  assign attr = select_demand ? demand_attr : prefetch_attr;
  assign priv = select_demand ? demand_priv : cp0_yy_priv_mode;
  // 2'b11 = 4 拍(64 B 行) / 2'b00 = 单拍; 16 B 行 ⇒ BEATS==1 ⇒ 单拍
  assign ifu_biu_rd_len = (allocate && (BEATS > 1)) ? 2'b11 : 2'b00;
  assign ifu_biu_rd_burst = allocate ? 2'b10 : 2'b01;
  assign ifu_biu_rd_size = 3'b100;
  assign ifu_biu_rd_cache = {attr[3], attr[3], 1'b1, attr[2]};
  assign ifu_biu_rd_prot = {1'b1, attr[1], priv != 0};
  assign ifu_biu_rd_domain = attr[3] ? {1'b0, !cp0_ifu_insde} : 2'b11;
  assign ifu_biu_rd_snoop = allocate && !cp0_ifu_insde ? 4'b0001 : 4'b0000;
  assign ifu_biu_rd_user = {priv == 3, 1'b0};
  assign
    demand_grant = prefetch_replay_grant || (ifu_biu_rd_req && select_demand && biu_ifu_rd_grnt);
  assign prefetch_grant = ifu_biu_rd_req && select_prefetch && biu_ifu_rd_grnt;
  assign ifu_biu_r_ready = outstanding_q[biu_ifu_rd_id] &&
    (biu_ifu_rd_id ? prefetch_ready : demand_ready);
  assign response_fire = biu_ifu_rd_data_vld && ifu_biu_r_ready;
  assign demand_valid = biu_ifu_rd_data_vld && !biu_ifu_rd_id && outstanding_q[0];
  assign prefetch_valid = biu_ifu_rd_data_vld && biu_ifu_rd_id && outstanding_q[1];
  assign response_data = biu_ifu_rd_data;
  assign response_error = biu_ifu_rd_resp[1];
  assign response_last = biu_ifu_rd_last;
  assign idle = !(|outstanding_q) && !ifu_biu_rd_req;
  generate
    for (id = 0; id < 2; id = id + 1) begin : g_id
      wire launch, complete;
      assign launch              = ifu_biu_rd_req && biu_ifu_rd_grnt && ifu_biu_rd_id == id;
      assign complete            = response_fire && biu_ifu_rd_last && biu_ifu_rd_id == id;
      assign outstanding_en[id]  = launch || complete;
      assign outstanding_nxt[id] = launch;
      always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_outstanding
        if (!cpurst_b) outstanding_q[id] <= 1'b0;
        else if (outstanding_en[id]) outstanding_q[id] <= outstanding_nxt[id];
      end
    end
  endgenerate

endmodule
