// SPDX-License-Identifier: Apache-2.0
// RV32I adaptation of C910 support-stage duties. See doc/pipeline_zh.md.
// Generated by scripts/build_support.py. All PCs are physical byte addresses.
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
module rv32_ifu_debug (
  input  wire        forever_cpuclk,
  input  wire        cpurst_b,
  input  wire        rtu_ifu_dbgon,
  input  wire        quiescent,
  input  wire        global_cancel,
  input  wire        had_ifu_pcload,
  input  wire        had_ifu_ir_vld,
  input  wire [31:0] had_ifu_pc,
  input  wire [31:0] had_ifu_ir,
  output wire        ifu_had_cmd_ready,
  output wire        debug_pcgen_pcload,
  output wire        inject_valid,
  output wire        inject_query,
  output wire        inject_pipedown,
  output wire        debug_busy,
  output wire        debug_restore,
  output wire [31:0] debug_pcgen_pc,
  output wire [31:0] inject_pc,
  output wire [31:0] inject_inst,
  input  wire        inject_accept
);
  wire command, inject;
  reg         debug_on_q;
  wire        debug_on_nxt;
  wire        debug_on_en;
  reg         valid_q;
  wire        valid_nxt;
  wire        valid_en;
  reg  [63:0] payload_q;
  wire [63:0] payload_nxt;
  wire        payload_en;
  reg  [ 1:0] delay_q;
  wire [ 1:0] delay_nxt;
  wire        delay_en;

  assign ifu_had_cmd_ready  = rtu_ifu_dbgon && quiescent && !valid_q && !global_cancel;
  assign command            = ifu_had_cmd_ready && (had_ifu_pcload ^ had_ifu_ir_vld);
  assign inject             = command && had_ifu_ir_vld;
  assign debug_pcgen_pcload = command && had_ifu_pcload;
  assign debug_restore      = (rtu_ifu_dbgon && !debug_on_q) || debug_pcgen_pcload;
  assign debug_pcgen_pc     = had_ifu_pc;
  assign inject_valid       = valid_q && delay_q == 2 && !global_cancel;
  assign inject_query       = valid_q && delay_q == 0 && !global_cancel;
  assign inject_pipedown    = valid_q && delay_q == 1 && !global_cancel;
  assign debug_busy         = valid_q;
  assign inject_pc          = payload_q[63:32];
  assign inject_inst        = payload_q[31:0];
  assign debug_on_en        = 1'b1;
  assign debug_on_nxt       = rtu_ifu_dbgon;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_debug_on
    if (!cpurst_b) debug_on_q <= 1'b0;
    else if (debug_on_en) debug_on_q <= debug_on_nxt;
  end
  assign valid_en  = inject || inject_accept || global_cancel;
  assign valid_nxt = inject && !global_cancel;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_valid
    if (!cpurst_b) valid_q <= 1'b0;
    else if (valid_en) valid_q <= valid_nxt;
  end
  assign payload_en  = inject;
  assign payload_nxt = {had_ifu_pc, had_ifu_ir};
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_payload
    if (!cpurst_b) payload_q <= 64'b0;
    else if (payload_en) payload_q <= payload_nxt;
  end
  assign delay_en  = inject || (valid_q && delay_q != 2);
  assign delay_nxt = inject ? 2'b0 : delay_q + 2'd1;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_delay
    if (!cpurst_b) delay_q <= 2'b0;
    else if (delay_en) delay_q <= delay_nxt;
  end

endmodule
