// SPDX-License-Identifier: Apache-2.0
// RV32I word-stage adaptation of the corresponding C910 IFU stage duties.
// Generated by scripts/build_pipeline.py. See doc/pipeline_zh.md.
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
module rv32_ifu_pipeline (
  input  wire [ 31:0] ifdp_ipdp_vpc,
  input  wire [127:0] ifdp_ipdp_inst_data0,
  input  wire [127:0] ifdp_ipdp_inst_data1,
  input  wire [  2:0] ifdp_ipdp_tag_match0,
  input  wire [  2:0] ifdp_ipdp_tag_match1,
  input  wire [  1:0] ifdp_ipdp_way_pred,
  input  wire         ifdp_ipdp_fault,
  input  wire [  3:0] ifdp_ipdp_cause,
  input  wire [  3:0] ifdp_ipdp_bkpta,
  input  wire [  3:0] ifdp_ipdp_bkptb,
  input  wire [  3:0] ifdp_ipdp_no_spec,
  input  wire         bht_pred,
  input  wire [ 24:0] bht_chk_idx,
  input  wire [  3:0] ifdp_ipdp_btb_hit,
  input  wire [127:0] ifdp_ipdp_btb_target,
  input  wire [  7:0] ifdp_ipdp_btb_way,
  input  wire         forever_cpuclk,
  input  wire         cpurst_b,
  input  wire         cancel_ip,
  input  wire         ifctrl_ipctrl_vld,
  input  wire         ifctrl_ifdp_pipedown,
  input  wire [  3:0] ifdp_ipdp_word_mask,
  input  wire         ifdp_ipdp_cache_bypass,
  input  wire         ifdp_ipdp_fifo,
  input  wire         demand_ready,
  input  wire         ifctrl_ipctrl_if_pcload,
  input  wire         ifdp_ipdp_l0_hit,
  input  wire [  1:0] ifdp_ipdp_l0_slot,
  input  wire [  2:0] ifdp_ipdp_l0_type,
  input  wire [ 31:0] ifdp_ipdp_l0_target,
  input  wire [ 15:0] ifdp_ipdp_l0_entry_mask,
  output wire         ipctrl_ifctrl_stall,
  output wire         demand_valid,
  output wire [ 31:0] demand_pc,
  output wire         demand_way,
  output wire         reissue,
  output wire         ip_redirect,
  output wire [ 31:0] ip_redirect_pc,
  output wire [  1:0] reissue_way,
  output wire         bht_event,
  output wire         bht_taken,
  output wire         bht_more,
  output wire         l0_invalidate,
  output wire [ 15:0] l0_invalidate_mask,
  output wire         fault_accept,
  output wire         way_event,
  output wire         miss_event,
  output wire         ib_accept,
  output wire [  2:0] consume_count,
  input  wire         ras_valid,
  input  wire [ 31:0] ras_target,
  output wire [767:0] corrected_packet,
  input  wire         flush,
  input  wire         recovery_stall,
  input  wire         ind_enable,
  input  wire         ind_result_vld,
  input  wire         ind_target_valid,
  input  wire [ 31:0] ind_target,
  input  wire         btb_update_ready,
  output wire         ind_query,
  output wire         ib_redirect,
  output wire [ 31:0] ib_redirect_pc,
  output wire [ 21:0] local_recover_ghr,
  output wire         ras_push,
  output wire         ras_pop,
  output wire         jump_accept,
  output wire         return_accept,
  output wire         ind_miss_event,
  output wire [ 31:0] push_pc,
  output wire [ 31:0] jump_target,
  output wire         train_valid,
  output wire         train_taken,
  output wire         train_cnt_lo,
  output wire         train_ras,
  output wire         btb_used,
  output wire [ 31:0] train_pc,
  output wire [ 31:0] train_target,
  output wire [  2:0] train_type,
  output wire [  1:0] train_way,
  output wire [  7:0] ind_query_ghr,
  output wire         ib_empty,
  output wire         pcfifo_wait,
  output wire         recovery_wait,
  input  wire [  1:0] iu_ifu_pcfifo_credit,
  input  wire [ 12:0] iu_ifu_pcfifo_alloc0_token,
  input  wire [ 12:0] iu_ifu_pcfifo_alloc1_token,
  output wire [  1:0] create_en,
  output wire [ 63:0] create_pc,
  output wire [ 63:0] create_target,
  output wire [ 63:0] create_npc,
  output wire [  5:0] create_type,
  output wire [  1:0] create_dst,
  output wire [  1:0] create_pred,
  output wire [  1:0] create_unknown,
  output wire [ 49:0] create_chk,
  input  wire [  1:0] idu_ifu_accept_num,
  output wire [  1:0] out_count,
  output wire [383:0] out_packet,
  output wire [ 74:0] out_chk,
  output wire [  5:0] occupancy,
  output wire         ibuf_empty
);
  wire [  3:0] remaining_mask;
  wire [  1:0] tag_hit;
  wire [  1:0] data_hit;
  wire [  3:0] control_mask;
  wire [  3:0] cond_mask;
  wire [  3:0] taken_mask;
  wire [767:0] slot_packet;
  wire [127:0] slot_npc;
  wire         ib_ready;
  wire [  3:0] fragment_mask;
  wire [  2:0] fragment_count;
  wire [767:0] fragment_packet;
  wire         fragment_valid;
  wire         fragment_fire;
  wire         load;
  wire         saved_ind_valid;
  wire [ 31:0] saved_ind_target;
  wire [767:0] raw_packet;
  wire [  3:0] correction;
  wire [127:0] corrected_pc;
  wire [ 87:0] retained_ghr;
  wire [  2:0] allowed_count;
  wire         ibuf_ready;
  wire [  2:0] candidate_count;
  wire [511:0] instruction_packet;
  wire [ 99:0] instruction_chk;
  wire         credit_stall;
  wire         lbuf_bht_active_state;
  wire         lbuf_bht_con_br_taken;
  wire         lbuf_bht_con_br_vld;
  wire         lbuf_ibctrl_active_idle_flush;
  wire [ 31:0] lbuf_ibctrl_chgflw_pc;
  wire [  1:0] lbuf_ibctrl_chgflw_pred;
  wire         lbuf_ibctrl_chgflw_vld;
  wire         lbuf_ibctrl_lbuf_active;
  wire         lbuf_ibctrl_stall;
  wire         lbuf_ibdp_inst0_valid;
  wire [ 31:0] lbuf_ibdp_inst0_data;
  wire [ 31:0] lbuf_ibdp_inst0_pc;
  wire [ 31:0] lbuf_ibdp_inst0_npc;
  wire         lbuf_ibdp_inst0_front_br;
  wire         lbuf_ibdp_inst0_back_br;
  wire         lbuf_ibdp_inst0_fence;
  wire         lbuf_ibdp_inst0_bkpta;
  wire         lbuf_ibdp_inst0_bkptb;
  wire         lbuf_ibdp_inst1_valid;
  wire [ 31:0] lbuf_ibdp_inst1_data;
  wire [ 31:0] lbuf_ibdp_inst1_pc;
  wire [ 31:0] lbuf_ibdp_inst1_npc;
  wire         lbuf_ibdp_inst1_front_br;
  wire         lbuf_ibdp_inst1_back_br;
  wire         lbuf_ibdp_inst1_fence;
  wire         lbuf_ibdp_inst1_bkpta;
  wire         lbuf_ibdp_inst1_bkptb;
  wire         lbuf_ibdp_inst2_valid;
  wire [ 31:0] lbuf_ibdp_inst2_data;
  wire [ 31:0] lbuf_ibdp_inst2_pc;
  wire [ 31:0] lbuf_ibdp_inst2_npc;
  wire         lbuf_ibdp_inst2_front_br;
  wire         lbuf_ibdp_inst2_back_br;
  wire         lbuf_ibdp_inst2_fence;
  wire         lbuf_ibdp_inst2_bkpta;
  wire         lbuf_ibdp_inst2_bkptb;
  wire         lbuf_pcgen_active;
  wire         lbuf_pcgen_vld_mask;
  wire         lbuf_addrgen_active_state;
  wire         lbuf_addrgen_cache_state;
  wire         lbuf_addrgen_chgflw_mask;
  wire         lbuf_pcfifo_if_create_select;
  wire [  1:0] lbuf_pcfifo_if_inst_bht_pre_result;
  wire [  1:0] lbuf_pcfifo_if_inst_bht_sel_result;
  wire [ 31:0] lbuf_pcfifo_if_inst_cur_pc;
  wire         lbuf_pcfifo_if_inst_pc_oper;
  wire [ 31:0] lbuf_pcfifo_if_inst_target_pc;
  wire [ 21:0] lbuf_pcfifo_if_inst_vghr;
  wire         lbuf_ipdp_lbuf_active;
  wire [  5:0] lbuf_debug_st;
  wire [767:0] corrected_packet;
  wire [  3:0] ibdp_lbuf_inst_vld_num;
  wire [  1:0] ibdp_lbuf_bht_sel_array_result;
  wire [ 31:0] ibdp_lbuf_con_br_cur_pc;
  wire [ 31:0] ibdp_lbuf_con_br_offset;
  wire         ibdp_lbuf_con_br_taken;
  wire         ibdp_lbuf_inst0_vld;
  wire [ 31:0] ibdp_lbuf_inst0_data;
  wire         ibdp_lbuf_inst0_con_br;
  wire         ibdp_lbuf_inst0_chgflw;
  wire         ibdp_lbuf_inst0_auipc;
  wire         ibdp_lbuf_inst0_fence;
  wire         ibdp_lbuf_inst0_bkpta;
  wire         ibdp_lbuf_inst0_bkptb;
  wire         ibdp_lbuf_inst1_vld;
  wire [ 31:0] ibdp_lbuf_inst1_data;
  wire         ibdp_lbuf_inst1_con_br;
  wire         ibdp_lbuf_inst1_chgflw;
  wire         ibdp_lbuf_inst1_auipc;
  wire         ibdp_lbuf_inst1_fence;
  wire         ibdp_lbuf_inst1_bkpta;
  wire         ibdp_lbuf_inst1_bkptb;
  wire         ibdp_lbuf_inst2_vld;
  wire [ 31:0] ibdp_lbuf_inst2_data;
  wire         ibdp_lbuf_inst2_con_br;
  wire         ibdp_lbuf_inst2_chgflw;
  wire         ibdp_lbuf_inst2_auipc;
  wire         ibdp_lbuf_inst2_fence;
  wire         ibdp_lbuf_inst2_bkpta;
  wire         ibdp_lbuf_inst2_bkptb;
  wire         ibdp_lbuf_inst3_vld;
  wire [ 31:0] ibdp_lbuf_inst3_data;
  wire         ibdp_lbuf_inst3_con_br;
  wire         ibdp_lbuf_inst3_chgflw;
  wire         ibdp_lbuf_inst3_auipc;
  wire         ibdp_lbuf_inst3_fence;
  wire         ibdp_lbuf_inst3_bkpta;
  wire         ibdp_lbuf_inst3_bkptb;
  wire         cp0_ifu_lbuf_en;
  wire         bht_lbuf_pre_ntaken_result;
  wire         bht_lbuf_pre_taken_result;
  wire         bht_lbuf_vghr;
  wire         ibctrl_lbuf_bju_mispred;
  wire         ibctrl_lbuf_create_vld;
  wire         ibctrl_lbuf_flush;
  wire         ibctrl_lbuf_retire_vld;
  wire         ifctrl_lbuf_ins_inv_on;
  wire         ifctrl_lbuf_inv_req;
  wire         iu_ifu_bht_check_vld;
  wire         iu_ifu_bht_condbr_taken;
  wire         iu_ifu_cur_pc;
  assign cp0_ifu_lbuf_en = 1'b0;
  assign bht_lbuf_pre_ntaken_result = 32'b0;
  assign bht_lbuf_pre_taken_result = 32'b0;
  assign bht_lbuf_vghr = 22'b0;
  assign ibctrl_lbuf_bju_mispred = 1'b0;
  assign ibctrl_lbuf_create_vld = 1'b0;
  assign ibctrl_lbuf_flush = 1'b0;
  assign ibctrl_lbuf_retire_vld = 1'b0;
  assign ifctrl_lbuf_ins_inv_on = 1'b0;
  assign ifctrl_lbuf_inv_req = 1'b0;
  assign iu_ifu_bht_check_vld = 1'b0;
  assign iu_ifu_bht_condbr_taken = 1'b0;
  assign iu_ifu_cur_pc = 32'b0;
  rv32_ifu_ipdp u_ipdp (
    .ifdp_ipdp_vpc       (ifdp_ipdp_vpc),
    .ifdp_ipdp_inst_data0(ifdp_ipdp_inst_data0),
    .ifdp_ipdp_inst_data1(ifdp_ipdp_inst_data1),
    .ifdp_ipdp_tag_match0(ifdp_ipdp_tag_match0),
    .ifdp_ipdp_tag_match1(ifdp_ipdp_tag_match1),
    .ifdp_ipdp_way_pred  (ifdp_ipdp_way_pred),
    .ifdp_ipdp_fault     (ifdp_ipdp_fault),
    .ifdp_ipdp_cause     (ifdp_ipdp_cause),
    .ifdp_ipdp_bkpta     (ifdp_ipdp_bkpta),
    .ifdp_ipdp_bkptb     (ifdp_ipdp_bkptb),
    .ifdp_ipdp_no_spec   (ifdp_ipdp_no_spec),
    .remaining_mask      (remaining_mask),
    .bht_pred            (bht_pred),
    .bht_chk_idx         (bht_chk_idx),
    .ifdp_ipdp_btb_hit   (ifdp_ipdp_btb_hit),
    .ifdp_ipdp_btb_target(ifdp_ipdp_btb_target),
    .ifdp_ipdp_btb_way   (ifdp_ipdp_btb_way),
    .tag_hit             (tag_hit),
    .data_hit            (data_hit),
    .control_mask        (control_mask),
    .cond_mask           (cond_mask),
    .taken_mask          (taken_mask),
    .slot_packet         (slot_packet),
    .slot_npc            (slot_npc)
  );
  rv32_ifu_ipctrl u_ipctrl (
    .forever_cpuclk         (forever_cpuclk),
    .cpurst_b               (cpurst_b),
    .cancel                 (cancel_ip),
    .ifctrl_ipctrl_vld      (ifctrl_ipctrl_vld),
    .ifctrl_ifdp_pipedown   (ifctrl_ifdp_pipedown),
    .ifdp_ipdp_word_mask    (ifdp_ipdp_word_mask),
    .control_mask           (control_mask),
    .cond_mask              (cond_mask),
    .taken_mask             (taken_mask),
    .tag_hit                (tag_hit),
    .data_hit               (data_hit),
    .ifdp_ipdp_fault        (ifdp_ipdp_fault),
    .ifdp_ipdp_cache_bypass (ifdp_ipdp_cache_bypass),
    .ifdp_ipdp_fifo         (ifdp_ipdp_fifo),
    .ifdp_ipdp_vpc          (ifdp_ipdp_vpc),
    .slot_packet            (slot_packet),
    .ib_ready               (ib_ready),
    .demand_ready           (demand_ready),
    .ifctrl_ipctrl_if_pcload(ifctrl_ipctrl_if_pcload),
    .ifdp_ipdp_l0_hit       (ifdp_ipdp_l0_hit),
    .ifdp_ipdp_l0_slot      (ifdp_ipdp_l0_slot),
    .ifdp_ipdp_l0_type      (ifdp_ipdp_l0_type),
    .ifdp_ipdp_l0_target    (ifdp_ipdp_l0_target),
    .ifdp_ipdp_l0_entry_mask(ifdp_ipdp_l0_entry_mask),
    .remaining_mask         (remaining_mask),
    .fragment_mask          (fragment_mask),
    .fragment_count         (fragment_count),
    .fragment_packet        (fragment_packet),
    .fragment_valid         (fragment_valid),
    .fragment_fire          (fragment_fire),
    .ipctrl_ifctrl_stall    (ipctrl_ifctrl_stall),
    .demand_valid           (demand_valid),
    .demand_pc              (demand_pc),
    .demand_way             (demand_way),
    .reissue                (reissue),
    .redirect               (ip_redirect),
    .redirect_pc            (ip_redirect_pc),
    .reissue_way            (reissue_way),
    .bht_event              (bht_event),
    .bht_taken              (bht_taken),
    .bht_more               (bht_more),
    .l0_invalidate          (l0_invalidate),
    .l0_invalidate_mask     (l0_invalidate_mask),
    .fault_accept           (fault_accept),
    .way_event              (way_event),
    .miss_event             (miss_event)
  );
  rv32_ifu_ibdp u_ibdp (
    .forever_cpuclk  (forever_cpuclk),
    .cpurst_b        (cpurst_b),
    .load            (load),
    .consume         (ib_accept),
    .consume_count   (consume_count),
    .fragment_packet (fragment_packet),
    .ras_valid       (ras_valid),
    .ind_valid       (saved_ind_valid),
    .lbuf_addrgen_active_state(lbuf_addrgen_active_state),
    .lbuf_addrgen_cache_state(lbuf_addrgen_cache_state),
    .lbuf_addrgen_chgflw_mask(lbuf_addrgen_chgflw_mask),
    .fragment_count  (fragment_count),
    .ras_target      (ras_target),
    .ind_target      (saved_ind_target),
    .raw_packet      (raw_packet),
    .corrected_packet(corrected_packet),
    .correction      (correction),
    .corrected_pc    (corrected_pc),
    .retained_ghr    (retained_ghr)
  );
  rv32_ifu_ibctrl u_ibctrl (
    .forever_cpuclk   (forever_cpuclk),
    .cpurst_b         (cpurst_b),
    .cancel           (flush),
    .fragment_valid   (fragment_valid),
    .fragment_count   (fragment_count),
    .ib_ready         (ib_ready),
    .load             (load),
    .raw_packet       (raw_packet),
    .corrected_packet (corrected_packet),
    .correction       (correction),
    .corrected_pc     (corrected_pc),
    .retained_ghr     (retained_ghr),
    .recovery_stall   (recovery_stall),
    .ind_enable       (ind_enable),
    .ind_result_vld   (ind_result_vld),
    .ind_target_valid (ind_target_valid),
    .ind_target       (ind_target),
    .btb_update_ready (btb_update_ready),
    .ind_query        (ind_query),
    .saved_ind_valid  (saved_ind_valid),
    .saved_ind_target (saved_ind_target),
    .allowed_count    (allowed_count),
    .ibuf_ready       (ibuf_ready),
    .candidate_count  (candidate_count),
    .consume_count    (consume_count),
    .consume          (ib_accept),
    .redirect         (ib_redirect),
    .redirect_pc      (ib_redirect_pc),
    .local_recover_ghr(local_recover_ghr),
    .ras_push         (ras_push),
    .ras_pop          (ras_pop),
    .jump_accept      (jump_accept),
    .return_accept    (return_accept),
    .ind_miss_event   (ind_miss_event),
    .push_pc          (push_pc),
    .jump_target      (jump_target),
    .train_valid      (train_valid),
    .train_taken      (train_taken),
    .train_cnt_lo     (train_cnt_lo),
    .train_ras        (train_ras),
    .btb_used         (btb_used),
    .train_pc         (train_pc),
    .train_target     (train_target),
    .train_type       (train_type),
    .train_way        (train_way),
    .ind_query_ghr    (ind_query_ghr),
    .empty            (ib_empty),
    .pcfifo_wait      (pcfifo_wait),
    .recovery_wait    (recovery_wait)
  );
  rv32_ifu_pcfifo_if u_pcfifo_if (
    .flush                     (flush),
    .accept                    (ib_accept),
    .candidate_count           (candidate_count),
    .candidate_packet          (corrected_packet),
    .iu_ifu_pcfifo_credit      (iu_ifu_pcfifo_credit),
    .iu_ifu_pcfifo_alloc0_token(iu_ifu_pcfifo_alloc0_token),
    .iu_ifu_pcfifo_alloc1_token(iu_ifu_pcfifo_alloc1_token),
    .allowed_count             (allowed_count),
    .instruction_packet        (instruction_packet),
    .instruction_chk           (instruction_chk),
    .create_en                 (create_en),
    .create_pc                 (create_pc),
    .create_target             (create_target),
    .create_npc                (create_npc),
    .create_type               (create_type),
    .create_dst                (create_dst),
    .create_pred               (create_pred),
    .create_unknown            (create_unknown),
    .create_chk                (create_chk),
    .credit_stall              (credit_stall)
  );
  rv32_ifu_ibuf u_ibuf (
    .forever_cpuclk    (forever_cpuclk),
    .cpurst_b          (cpurst_b),
    .flush             (flush),
    .in_count          (allowed_count),
    .in_packet         (instruction_packet),
    .in_chk            (instruction_chk),
    .in_ready          (ibuf_ready),
    .idu_ifu_accept_num(idu_ifu_accept_num),
    .out_count         (out_count),
    .out_packet        (out_packet),
    .out_chk           (out_chk),
    .occupancy         (occupancy),
    .empty             (ibuf_empty)
  );
  rv32_ifu_lbuf u_lbuf (
    .forever_cpuclk                     (forever_cpuclk),
    .cpurst_b                           (cpurst_b),
    .cp0_ifu_lbuf_en                    (1'b0),
    .bht_lbuf_pre_ntaken_result         (32'b0),
    .bht_lbuf_pre_taken_result          (32'b0),
    .bht_lbuf_vghr                      (22'b0),
    .lbuf_bht_active_state              (lbuf_bht_active_state),
    .lbuf_bht_con_br_taken              (lbuf_bht_con_br_taken),
    .lbuf_bht_con_br_vld                (lbuf_bht_con_br_vld),
    .ibctrl_lbuf_bju_mispred            (1'b0),
    .ibctrl_lbuf_create_vld             (1'b0),
    .ibctrl_lbuf_flush                  (1'b0),
    .ibctrl_lbuf_retire_vld             (1'b0),
    .lbuf_ibctrl_active_idle_flush      (lbuf_ibctrl_active_idle_flush),
    .lbuf_ibctrl_chgflw_pc              (lbuf_ibctrl_chgflw_pc),
    .lbuf_ibctrl_chgflw_pred            (lbuf_ibctrl_chgflw_pred),
    .lbuf_ibctrl_chgflw_vld             (lbuf_ibctrl_chgflw_vld),
    .lbuf_ibctrl_lbuf_active            (lbuf_ibctrl_lbuf_active),
    .lbuf_ibctrl_stall                  (lbuf_ibctrl_stall),
    .ibdp_lbuf_inst_vld_num             (ibdp_lbuf_inst_vld_num),
    .ibdp_lbuf_bht_sel_array_result     (ibdp_lbuf_bht_sel_array_result),
    .ibdp_lbuf_con_br_cur_pc            (ibdp_lbuf_con_br_cur_pc),
    .ibdp_lbuf_con_br_offset            (ibdp_lbuf_con_br_offset),
    .ibdp_lbuf_con_br_taken             (ibdp_lbuf_con_br_taken),
    .ibdp_lbuf_inst0_vld                (ibdp_lbuf_inst0_vld),
    .ibdp_lbuf_inst0_data               (ibdp_lbuf_inst0_data),
    .ibdp_lbuf_inst0_con_br             (ibdp_lbuf_inst0_con_br),
    .ibdp_lbuf_inst0_chgflw             (ibdp_lbuf_inst0_chgflw),
    .ibdp_lbuf_inst0_auipc              (ibdp_lbuf_inst0_auipc),
    .ibdp_lbuf_inst0_fence              (ibdp_lbuf_inst0_fence),
    .ibdp_lbuf_inst0_bkpta              (ibdp_lbuf_inst0_bkpta),
    .ibdp_lbuf_inst0_bkptb              (ibdp_lbuf_inst0_bkptb),
    .ibdp_lbuf_inst1_vld                (ibdp_lbuf_inst1_vld),
    .ibdp_lbuf_inst1_data               (ibdp_lbuf_inst1_data),
    .ibdp_lbuf_inst1_con_br             (ibdp_lbuf_inst1_con_br),
    .ibdp_lbuf_inst1_chgflw             (ibdp_lbuf_inst1_chgflw),
    .ibdp_lbuf_inst1_auipc              (ibdp_lbuf_inst1_auipc),
    .ibdp_lbuf_inst1_fence              (ibdp_lbuf_inst1_fence),
    .ibdp_lbuf_inst1_bkpta              (ibdp_lbuf_inst1_bkpta),
    .ibdp_lbuf_inst1_bkptb              (ibdp_lbuf_inst1_bkptb),
    .ibdp_lbuf_inst2_vld                (ibdp_lbuf_inst2_vld),
    .ibdp_lbuf_inst2_data               (ibdp_lbuf_inst2_data),
    .ibdp_lbuf_inst2_con_br             (ibdp_lbuf_inst2_con_br),
    .ibdp_lbuf_inst2_chgflw             (ibdp_lbuf_inst2_chgflw),
    .ibdp_lbuf_inst2_auipc              (ibdp_lbuf_inst2_auipc),
    .ibdp_lbuf_inst2_fence              (ibdp_lbuf_inst2_fence),
    .ibdp_lbuf_inst2_bkpta              (ibdp_lbuf_inst2_bkpta),
    .ibdp_lbuf_inst2_bkptb              (ibdp_lbuf_inst2_bkptb),
    .ibdp_lbuf_inst3_vld                (ibdp_lbuf_inst3_vld),
    .ibdp_lbuf_inst3_data               (ibdp_lbuf_inst3_data),
    .ibdp_lbuf_inst3_con_br             (ibdp_lbuf_inst3_con_br),
    .ibdp_lbuf_inst3_chgflw             (ibdp_lbuf_inst3_chgflw),
    .ibdp_lbuf_inst3_auipc              (ibdp_lbuf_inst3_auipc),
    .ibdp_lbuf_inst3_fence              (ibdp_lbuf_inst3_fence),
    .ibdp_lbuf_inst3_bkpta              (ibdp_lbuf_inst3_bkpta),
    .ibdp_lbuf_inst3_bkptb              (ibdp_lbuf_inst3_bkptb),
    .lbuf_ibdp_inst0_valid              (lbuf_ibdp_inst0_valid),
    .lbuf_ibdp_inst0_data               (lbuf_ibdp_inst0_data),
    .lbuf_ibdp_inst0_pc                 (lbuf_ibdp_inst0_pc),
    .lbuf_ibdp_inst0_npc                (lbuf_ibdp_inst0_npc),
    .lbuf_ibdp_inst0_front_br           (lbuf_ibdp_inst0_front_br),
    .lbuf_ibdp_inst0_back_br            (lbuf_ibdp_inst0_back_br),
    .lbuf_ibdp_inst0_fence              (lbuf_ibdp_inst0_fence),
    .lbuf_ibdp_inst0_bkpta              (lbuf_ibdp_inst0_bkpta),
    .lbuf_ibdp_inst0_bkptb              (lbuf_ibdp_inst0_bkptb),
    .lbuf_ibdp_inst1_valid              (lbuf_ibdp_inst1_valid),
    .lbuf_ibdp_inst1_data               (lbuf_ibdp_inst1_data),
    .lbuf_ibdp_inst1_pc                 (lbuf_ibdp_inst1_pc),
    .lbuf_ibdp_inst1_npc                (lbuf_ibdp_inst1_npc),
    .lbuf_ibdp_inst1_front_br           (lbuf_ibdp_inst1_front_br),
    .lbuf_ibdp_inst1_back_br            (lbuf_ibdp_inst1_back_br),
    .lbuf_ibdp_inst1_fence              (lbuf_ibdp_inst1_fence),
    .lbuf_ibdp_inst1_bkpta              (lbuf_ibdp_inst1_bkpta),
    .lbuf_ibdp_inst1_bkptb              (lbuf_ibdp_inst1_bkptb),
    .lbuf_ibdp_inst2_valid              (lbuf_ibdp_inst2_valid),
    .lbuf_ibdp_inst2_data               (lbuf_ibdp_inst2_data),
    .lbuf_ibdp_inst2_pc                 (lbuf_ibdp_inst2_pc),
    .lbuf_ibdp_inst2_npc                (lbuf_ibdp_inst2_npc),
    .lbuf_ibdp_inst2_front_br           (lbuf_ibdp_inst2_front_br),
    .lbuf_ibdp_inst2_back_br            (lbuf_ibdp_inst2_back_br),
    .lbuf_ibdp_inst2_fence              (lbuf_ibdp_inst2_fence),
    .lbuf_ibdp_inst2_bkpta              (lbuf_ibdp_inst2_bkpta),
    .lbuf_ibdp_inst2_bkptb              (lbuf_ibdp_inst2_bkptb),
    .ibuf_lbuf_empty                    (ibuf_empty),
    .ifctrl_lbuf_ins_inv_on             (1'b0),
    .ifctrl_lbuf_inv_req                (1'b0),
    .iu_ifu_bht_check_vld               (1'b0),
    .iu_ifu_bht_condbr_taken            (1'b0),
    .iu_ifu_cur_pc                      (32'b0),
    .lbuf_pcgen_active                  (lbuf_pcgen_active),
    .lbuf_pcgen_vld_mask                (lbuf_pcgen_vld_mask),
    .lbuf_addrgen_active_state          (lbuf_addrgen_active_state),
    .lbuf_addrgen_cache_state           (lbuf_addrgen_cache_state),
    .lbuf_addrgen_chgflw_mask           (lbuf_addrgen_chgflw_mask),
    .lbuf_pcfifo_if_create_select       (lbuf_pcfifo_if_create_select),
    .lbuf_pcfifo_if_inst_bht_pre_result (lbuf_pcfifo_if_inst_bht_pre_result),
    .lbuf_pcfifo_if_inst_bht_sel_result (lbuf_pcfifo_if_inst_bht_sel_result),
    .lbuf_pcfifo_if_inst_cur_pc         (lbuf_pcfifo_if_inst_cur_pc),
    .lbuf_pcfifo_if_inst_pc_oper        (lbuf_pcfifo_if_inst_pc_oper),
    .lbuf_pcfifo_if_inst_target_pc      (lbuf_pcfifo_if_inst_target_pc),
    .lbuf_pcfifo_if_inst_vghr           (lbuf_pcfifo_if_inst_vghr),
    .lbuf_ipdp_lbuf_active              (lbuf_ipdp_lbuf_active),
    .lbuf_debug_st                      (lbuf_debug_st)
  );
endmodule
