// SPDX-License-Identifier: Apache-2.0
// RV32I adaptation of C910 support-stage duties. See doc/pipeline_zh.md.
// Generated by scripts/build_support.py. All PCs are physical byte addresses.
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
module rv32_ifu_sfp (
  input  wire        forever_cpuclk,
  input  wire        cpurst_b,
  input  wire        enable,
  input  wire        invalidate,
  input  wire        cancel,
  input  wire        lookup_accept,
  input  wire [31:0] lookup_pc,
  input  wire [ 3:0] lookup_mask,
  output wire [ 3:0] no_spec,
  input  wire [ 2:0] retire_valid,
  input  wire [ 2:0] retire_load,
  input  wire [ 2:0] retire_store,
  input  wire [ 2:0] retire_hit,
  input  wire [ 2:0] retire_miss,
  input  wire [ 2:0] retire_mispred,
  input  wire [95:0] retire_pc
);
  reg  [66:0] entry_q  [0:11];
  wire [66:0] entry_nxt[0:11];
  wire [11:0] entry_en, hit, selected;
  wire [2:0] event_valid, choose;
  wire [31:0] event_pc;
  wire event_store, event_miss, event_hit, event_mispred, feedback;
  wire [31:0] key;
  wire        allocate;
  wire [ 4:0] read_bar;
  wire [3:0] sf_hit, bar_hit;
  genvar lane, entry;
  reg  [ 3:0] pointer_q;
  wire [ 3:0] pointer_nxt;
  wire        pointer_en;
  reg  [31:0] last_store_q;
  wire [31:0] last_store_nxt;
  wire        last_store_en;
  reg         mode_q;
  wire        mode_nxt;
  wire        mode_en;

  // C910 SF/BAR pair: store feedback identifies SF, subsequent load feedback
  // identifies its barrier. Oldest retirement feedback wins the single port.
  assign event_valid = retire_valid & (retire_load | retire_store) &
    (retire_hit | retire_miss | retire_mispred);
  assign choose = {
    event_valid[2] && !(|event_valid[1:0]), event_valid[1] && !event_valid[0], event_valid[0]
  };
  assign event_pc = ({32{choose[0]}} & retire_pc[31:0]) | ({32{choose[1]}} & retire_pc[63:32]) |
    ({32{choose[2]}} & retire_pc[95:64]);
  assign event_store = |(choose & retire_store);
  assign event_miss = |(choose & retire_miss);
  assign event_hit = |(choose & retire_hit);
  assign event_mispred = |(choose & retire_mispred);
  assign feedback = enable && (|choose) && !invalidate;
  assign key = event_store ? event_pc : last_store_q;
  assign allocate = feedback && event_store && event_miss && !(|hit);
  assign read_bar[0] = mode_q;
  generate
    for (entry = 0; entry < 12; entry = entry + 1) begin : g_entry
      wire [1:0] count, increment, decrement, updated;
      assign hit[entry] = entry_q[entry][66] && entry_q[entry][31:0] == key;
      assign selected[entry] = feedback && (hit[entry] || (allocate && pointer_q == entry));
      assign count = entry_q[entry][65:64];
      assign increment = count == 3 ? 2'd3 : count + 2'd1;
      assign decrement = count == 0 ? 2'd0 : count - 2'd1;
      assign updated = event_store ? (event_mispred ? 2'd0 : event_miss ? 2'd1 : count) :
        event_miss ? 2'd1 : event_hit ? increment : decrement;
      assign entry_en[entry] = invalidate || selected[entry];
      assign entry_nxt[entry] = invalidate ? 67'b0 :
        {1'b1, updated, (event_store ? (allocate ? 32'b0 : entry_q[entry][63:32]) : event_pc), key};
      always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_entry
        if (!cpurst_b) entry_q[entry] <= 67'b0;
        else if (entry_en[entry]) entry_q[entry] <= entry_nxt[entry];
      end
    end
    for (lane = 0; lane < 4; lane = lane + 1) begin : g_lookup
      localparam [1:0] LANE = lane;
      wire [11:0] sf_matches, bar_matches;
      wire [31:0] pc;
      assign pc = {lookup_pc[31:4], LANE, 2'b0};
      for (entry = 0; entry < 12; entry = entry + 1) begin : g_compare
        assign sf_matches[entry] = entry_q[entry][66] && (|entry_q[entry][65:64]) &&
          entry_q[entry][31:0] == pc;
        assign bar_matches[entry] = entry_q[entry][66] && (|entry_q[entry][65:64]) &&
          entry_q[entry][63:32] == pc;
      end
      assign sf_hit[lane] = lookup_mask[lane] && (|sf_matches);
      assign bar_hit[lane] = lookup_mask[lane] && (|bar_matches);
      assign no_spec[lane] = enable && !invalidate &&
        (sf_hit[lane] || (read_bar[lane] && bar_hit[lane]));
      assign read_bar[lane+1] = sf_hit[lane] || (read_bar[lane] && !bar_hit[lane]);
    end
  endgenerate
  assign pointer_en  = invalidate || allocate;
  assign pointer_nxt = invalidate ? 4'b0 : pointer_q == 11 ? 4'b0 : pointer_q + 4'd1;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_pointer
    if (!cpurst_b) pointer_q <= 4'b0;
    else if (pointer_en) pointer_q <= pointer_nxt;
  end
  assign last_store_en  = invalidate || (feedback && event_store);
  assign last_store_nxt = invalidate ? 32'b0 : event_pc;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_last_store
    if (!cpurst_b) last_store_q <= 32'b0;
    else if (last_store_en) last_store_q <= last_store_nxt;
  end
  assign mode_en  = invalidate || cancel || lookup_accept;
  assign mode_nxt = !invalidate && !cancel && read_bar[4];
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_mode
    if (!cpurst_b) mode_q <= 1'b0;
    else if (mode_en) mode_q <= mode_nxt;
  end

endmodule
