// SPDX-License-Identifier: Apache-2.0
// RV32I word-stage adaptation of the corresponding C910 IFU stage duties.
// Generated by scripts/build_pipeline.py. See doc/pipeline_zh.md.
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
module rv32_ifu_ibuf (
  input  wire         forever_cpuclk,
  input  wire         cpurst_b,
  input  wire         flush,
  input  wire [  2:0] in_count,
  input  wire [511:0] in_packet,
  output wire         in_ready,
  input  wire [  1:0] idu_ifu_accept_num,
  output wire [  1:0] out_count,
  output wire [383:0] out_packet,
  output wire [  5:0] occupancy,
  output wire         empty
);

  // Ring entries contain complete, already allocated instruction packets.
  // Admission uses only OLD queue pop, so candidate valid cannot depend on
  // accept when IB is visible in an output lane (old count is then < 3).
  reg  [127:0] entry_q  [0:31];
  wire [127:0] entry_nxt[0:31];
  wire [ 31:0] entry_en;
  reg [4:0] head_q, tail_q;
  wire [4:0] head_nxt, tail_nxt;
  reg  [5:0] count_q;
  wire [5:0] count_nxt;
  wire       pointer_en;
  wire [2:0] accepted, pop_count, bypass_count, push_count, admitted;
  wire [6:0] available_count;
  genvar entry, lane;
  assign occupancy = count_q;
  assign empty = count_q == 0;
  assign pop_count = flush ?
    3'd0 : (({4'b0, idu_ifu_accept_num} < count_q) ? {1'b0, idu_ifu_accept_num} : count_q[2:0]);
  assign in_ready = !flush && (in_count <= 4) &&
    ({1'b0, count_q} + {4'b0, in_count} <= 7'd32 + {4'b0, pop_count});
  assign admitted = in_ready ? in_count : 3'd0;
  assign available_count = {1'b0, count_q} + {4'b0, admitted};
  assign out_count = flush ? 2'd0 : available_count >= 3 ? 2'd3 : available_count[1:0];
  assign accepted = flush ? 3'd0 : {1'b0, idu_ifu_accept_num};
  assign bypass_count = accepted - pop_count;
  assign push_count = admitted - bypass_count;
  assign pointer_en = flush || (|pop_count) || (|push_count);
  assign head_nxt = flush ? 5'd0 : head_q + {2'b0, pop_count};
  assign tail_nxt = flush ? 5'd0 : tail_q + {2'b0, push_count};
  assign count_nxt = flush ? 6'd0 : count_q - {3'b0, pop_count} + {3'b0, push_count};
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_head
    if (!cpurst_b) head_q <= 5'd0;
    else if (pointer_en) head_q <= head_nxt;
  end
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_tail
    if (!cpurst_b) tail_q <= 5'd0;
    else if (pointer_en) tail_q <= tail_nxt;
  end
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_count
    if (!cpurst_b) count_q <= 6'd0;
    else if (pointer_en) count_q <= count_nxt;
  end
  generate
    for (entry = 0; entry < 32; entry = entry + 1) begin : g_entry
      localparam [4:0] INDEX = entry;
      wire [4:0] distance;
      wire [2:0] source;
      assign distance         = INDEX - tail_q;
      assign source           = distance[2:0] + bypass_count;
      assign entry_en[entry]  = !flush && ({1'b0, distance} < {3'b0, push_count});
      assign entry_nxt[entry] = in_packet[{source, 7'b0}+:128];
      always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_entry
        if (!cpurst_b) entry_q[entry] <= 128'b0;
        else if (entry_en[entry]) entry_q[entry] <= entry_nxt[entry];
      end
    end
    for (lane = 0; lane < 3; lane = lane + 1) begin : g_lane
      localparam [5:0] LANE = lane;
      wire [4:0] index;
      wire [5:0] source;
      assign index = head_q + LANE[4:0];
      assign source = LANE - count_q;
      assign out_packet[lane*128+:128] = (LANE >= {4'b0, out_count}) ?
        128'b0 : (LANE < count_q) ? entry_q[index] : in_packet[{source, 7'b0}+:128];
    end
  endgenerate

endmodule
