// SPDX-License-Identifier: Apache-2.0
// RV32I word-stage adaptation of the corresponding C910 IFU stage duties.
// Generated by scripts/build_pipeline.py. See doc/pipeline_zh.md.
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
module rv32_ifu_ipctrl (
  input  wire         forever_cpuclk,
  input  wire         cpurst_b,
  input  wire         cancel,
  input  wire         ifctrl_ipctrl_vld,
  input  wire         ifctrl_ifdp_pipedown,
  input  wire [  3:0] ifdp_ipdp_word_mask,
  input  wire [  3:0] control_mask,
  input  wire [  3:0] cond_mask,
  input  wire [  3:0] taken_mask,
  input  wire [  1:0] tag_hit,
  input  wire [  1:0] data_hit,
  input  wire         ifdp_ipdp_fault,
  input  wire         ifdp_ipdp_cache_bypass,
  input  wire         ifdp_ipdp_fifo,
  input  wire [ 31:0] ifdp_ipdp_vpc,
  input  wire [767:0] slot_packet,
  input  wire         ib_ready,
  input  wire         demand_ready,
  input  wire         ifctrl_ipctrl_if_pcload,
  input  wire         ifdp_ipdp_l0_hit,
  input  wire [  1:0] ifdp_ipdp_l0_slot,
  input  wire [  2:0] ifdp_ipdp_l0_type,
  input  wire [ 31:0] ifdp_ipdp_l0_target,
  input  wire [ 15:0] ifdp_ipdp_l0_entry_mask,
  output wire [  3:0] remaining_mask,
  output wire [  3:0] fragment_mask,
  output wire [  2:0] fragment_count,
  output wire [767:0] fragment_packet,
  output wire         fragment_valid,
  output wire         fragment_fire,
  output wire         ipctrl_ifctrl_stall,
  output wire         demand_valid,
  output wire [ 31:0] demand_pc,
  output wire         demand_way,
  output wire         reissue,
  output wire         redirect,
  output wire [ 31:0] redirect_pc,
  output wire [  1:0] reissue_way,
  output wire         bht_event,
  output wire         bht_taken,
  output wire         bht_more,
  output wire         l0_invalidate,
  output wire [ 15:0] l0_invalidate_mask,
  output wire         fault_accept,
  output wire         way_event,
  output wire         miss_event
);

  reg  [3:0] processed_q;
  wire [3:0] processed_nxt;
  wire       processed_en;
  wire [3:0] first_control, last_slot;
  wire [2:0] rank[0:4];
  wire wrong_way, miss, valid_data, terminal, done;
  wire [  1:0] last_index;
  wire [191:0] last_packet;
  wire reaches_l0, l0_in_fragment, l0_correct, path_change, short_block;
  genvar lane, bit_index;
  assign remaining_mask = ifdp_ipdp_word_mask & ~processed_q;
  assign wrong_way      = !ifdp_ipdp_fault && !ifdp_ipdp_cache_bypass && (|tag_hit) && !(|data_hit);
  assign miss           = !ifdp_ipdp_fault && (ifdp_ipdp_cache_bypass || !(|tag_hit));
  assign valid_data     = ifctrl_ipctrl_vld && !cancel && !wrong_way && !miss;
  assign demand_valid   = ifctrl_ipctrl_vld && !cancel && miss;
  assign demand_pc      = ifdp_ipdp_vpc;
  assign demand_way     = ifdp_ipdp_fifo;
  assign miss_event     = demand_valid && demand_ready;
  assign way_event      = ifctrl_ipctrl_vld && !cancel && wrong_way;
  assign reissue        = way_event || miss_event;
  assign reissue_way    = wrong_way ? tag_hit : 2'b11;
  assign rank[0]        = 0;
  generate
    for (lane = 0; lane < 4; lane = lane + 1) begin : g_prefix
      localparam [2:0] LANE = lane;
      if (lane == 0) begin : g_first
        assign first_control[lane] = control_mask[lane];
        assign fragment_mask[lane] = remaining_mask[lane];
      end else begin : g_later
        assign first_control[lane] = control_mask[lane] && !(|control_mask[lane-1:0]);
        assign fragment_mask[lane] = remaining_mask[lane] && !(|control_mask[lane-1:0]);
      end
      if (lane == 3) begin : g_final
        assign last_slot[lane] = fragment_mask[lane];
      end else begin : g_before_final
        assign last_slot[lane] = fragment_mask[lane] && !(|fragment_mask[3:lane+1]);
      end
      assign rank[lane+1] = rank[lane] + {2'b0, fragment_mask[lane]};
      wire [191:0] mux_value[0:4];
      genvar source;
      assign mux_value[0] = 192'b0;
      for (source = 0; source < 4; source = source + 1) begin : g_compact
        assign mux_value[source+1] = mux_value[source] |
          ({192{fragment_mask[source] && rank[source] == LANE}} & slot_packet[source*192+:192]);
      end
      assign fragment_packet[lane*192+:192] = mux_value[4];
    end
  endgenerate
  assign fragment_count = rank[4];
  assign last_index = {last_slot[2] || last_slot[3], last_slot[1] || last_slot[3]};
  assign last_packet = slot_packet[{30'b0, last_index}*32'd192+:192];
  assign terminal = |(fragment_mask & taken_mask);
  assign fragment_valid = valid_data && (|fragment_mask);
  assign fragment_fire = fragment_valid && ib_ready;
  assign done = reissue || (fragment_fire && (terminal || fragment_mask == remaining_mask));
  assign ipctrl_ifctrl_stall = ifctrl_ipctrl_vld && !done && !cancel;
  assign processed_en = cancel || ifctrl_ifdp_pipedown || fragment_fire || done;
  assign
    processed_nxt = (cancel || ifctrl_ifdp_pipedown || done) ? 4'b0 : processed_q | fragment_mask;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_processed
    if (!cpurst_b) processed_q <= 4'b0;
    else if (processed_en) processed_q <= processed_nxt;
  end
  assign bht_event = fragment_fire && (|(fragment_mask & cond_mask));
  // Direction history describes the prediction, even when execution must later
  // report a misaligned actual target at the source instruction.
  assign bht_taken = last_packet[122];
  assign bht_more = valid_data && !terminal && (|(remaining_mask & ~fragment_mask));
  assign reaches_l0 = ifctrl_ipctrl_if_pcload &&
    (terminal || fragment_mask[ifdp_ipdp_l0_slot] || fragment_mask == remaining_mask);
  // L0 预测的那条分支就在本 fragment 里. 这时 IF 级已经按 L0 的目标改向过了, 而
  // IP 级译码发现它其实没跳 (L0 的 taken 位是粘滞的, BHT 翻转后仍可能留着武装
  // 状态) —— 必须把取指拉回该分支的【顺序后继】, 也就是本 fragment 最后一个已
  // 派发 slot 的 npc. 用 {vpc[31:4]+1,4'b0} (下一个 16B 块) 会把这之后还没取过
  // 的 slot 整个跳过 (实测: coremark 里 bltu 在 slot1, 0x858/0x85c 被丢掉).
  // 只有 "整块都走过、始终没碰到 L0 那条分支" 时才该顺序切到下一块.
  assign l0_in_fragment = ifctrl_ipctrl_if_pcload && fragment_mask[ifdp_ipdp_l0_slot];
  assign l0_correct = ifdp_ipdp_l0_hit && last_index == ifdp_ipdp_l0_slot && last_packet[108:106] ==
    ifdp_ipdp_l0_type && last_packet[122] && last_packet[95:64] == ifdp_ipdp_l0_target;
  assign short_block = !terminal && fragment_mask == remaining_mask && last_index != 3;
  assign
    path_change = terminal ? (!ifctrl_ipctrl_if_pcload || !l0_correct) : reaches_l0 || short_block;
  assign redirect = fragment_fire && !ifdp_ipdp_fault && path_change;
  assign redirect_pc = (terminal || short_block || l0_in_fragment) ?
    last_packet[95:64] : {ifdp_ipdp_vpc[31:4] + 28'd1, 4'b0};
  assign l0_invalidate = fragment_fire && reaches_l0 && !l0_correct;
  assign l0_invalidate_mask = ifdp_ipdp_l0_entry_mask;
  assign fault_accept = fragment_fire && ifdp_ipdp_fault;

endmodule
