// SPDX-License-Identifier: Apache-2.0
// RV32I word-stage adaptation of the corresponding C910 IFU stage duties.
// Generated by scripts/build_pipeline.py. See doc/pipeline_zh.md.
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
module rv32_ifu_ibdp (
  input  wire         forever_cpuclk,
  input  wire         cpurst_b,
  input  wire         load,
  input  wire         consume,
  input  wire [  2:0] consume_count,
  input  wire [767:0] fragment_packet,
  input  wire         ras_valid,
  input  wire         ind_valid,
  input  wire [ 31:0] ras_target,
  input  wire [ 31:0] ind_target,
  output wire [767:0] raw_packet,
  output wire [767:0] corrected_packet,
  output wire [  3:0] correction,
  output wire [127:0] corrected_pc,
  output wire [ 87:0] retained_ghr
);

  reg  [191:0] lane_q  [0:3];
  wire [191:0] lane_nxt[0:3];
  wire         lane_en;
  genvar lane;
  assign lane_en = load || consume;
  generate
    for (lane = 0; lane < 4; lane = lane + 1) begin : g_lane
      wire [2:0] source;
      assign source = consume_count + lane;
      assign lane_nxt[lane] = load ?
        fragment_packet[lane*192+:192] : (source < 4 ? lane_q[source] : 192'b0);
      always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_lane
        if (!cpurst_b) lane_q[lane] <= 192'b0;
        else if (lane_en) lane_q[lane] <= lane_nxt[lane];
      end
      assign raw_packet[lane*192+:192] = lane_q[lane];
      rv32_ifu_addrgen u_addrgen (
        .source_packet(lane_q[lane]),
        .ras_valid    (ras_valid),
        .ras_target   (ras_target),
        .ind_valid    (ind_valid),
        .ind_target   (ind_target),
        .result_packet(corrected_packet[lane*192+:192]),
        .correction   (correction[lane]),
        .corrected_pc (corrected_pc[lane*32+:32]),
        .retained_ghr (retained_ghr[lane*22+:22])
      );
    end
  endgenerate

endmodule
