// SPDX-License-Identifier: Apache-2.0
// RV32I word-stage adaptation of the corresponding C910 IFU stage duties.
// Generated by scripts/build_pipeline.py. See doc/pipeline_zh.md.
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
module rv32_ifu_pcfifo_if (
  input  wire         flush,
  input  wire         accept,
  input  wire [  2:0] candidate_count,
  input  wire [767:0] candidate_packet,
  input  wire [  1:0] iu_ifu_pcfifo_credit,
  input  wire [ 12:0] iu_ifu_pcfifo_alloc0_token,
  input  wire [ 12:0] iu_ifu_pcfifo_alloc1_token,
  output wire [  2:0] allowed_count,
  output wire [511:0] instruction_packet,
  output wire [  1:0] create_en,
  output wire [ 63:0] create_pc,
  output wire [ 63:0] create_target,
  output wire [ 63:0] create_npc,
  output wire [  5:0] create_type,
  output wire [  1:0] create_dst,
  output wire [  1:0] create_pred,
  output wire [  1:0] create_unknown,
  output wire [ 49:0] create_chk,
  output wire         credit_stall
);

  wire [ 2:0] pc_count[0:4];
  wire [ 3:0] allowed;
  wire [25:0] tokens;
  genvar lane, record, bit_index;
  assign tokens = {iu_ifu_pcfifo_alloc1_token, iu_ifu_pcfifo_alloc0_token};
  assign pc_count[0] = 3'd0;
  assign allowed_count = {2'b0, allowed[0]} + {2'b0, allowed[1]} + {2'b0, allowed[2]} +
    {2'b0, allowed[3]};
  assign credit_stall = !flush && allowed_count < candidate_count;
  generate
    for (lane = 0; lane < 4; lane = lane + 1) begin : g_lane
      localparam [2:0] LANE = lane;
      wire [191:0] packet;
      wire [ 12:0] token;
      assign packet = candidate_packet[lane*192+:192];
      assign pc_count[lane+1] = pc_count[lane] + {2'b0, (LANE < candidate_count && packet[105])};
      assign allowed[lane] = !flush && LANE < candidate_count && pc_count[lane+1] <=
        (packet[191] ? 3'd1 : 3'd2) && pc_count[lane+1] <= {1'b0, iu_ifu_pcfifo_credit};
      assign token = packet[105] ? tokens[({29'b0, pc_count[lane]}*32'd13)+:13] : 13'b0;
      assign instruction_packet[lane*128+:128] = allowed[lane] ?
        {5'b0, packet[122], token, packet[108:0]} : 128'b0;
    end
    for (record = 0; record < 2; record = record + 1) begin : g_record
      localparam [2:0] RECORD = record;
      wire [  3:0] select_lane;
      wire [191:0] selected;
      for (lane = 0; lane < 4; lane = lane + 1) begin : g_select
        assign select_lane[lane] = allowed[lane] && candidate_packet[lane*192+105] &&
          pc_count[lane] == RECORD;
      end
      wire [191:0] mux_value[0:4];
      assign mux_value[0] = 192'b0;
      for (lane = 0; lane < 4; lane = lane + 1) begin : g_mux
        assign mux_value[lane+1] = mux_value[lane] |
          ({192{select_lane[lane]}} & candidate_packet[lane*192+:192]);
      end
      assign selected                     = mux_value[4];
      assign create_en[record]            = accept && !flush && (|select_lane);
      assign create_pc[record*32+:32]     = selected[63:32];
      assign create_target[record*32+:32] = selected[159:128];
      assign create_npc[record*32+:32]    = selected[95:64];
      assign create_type[record*3+:3]     = selected[108:106];
      assign create_dst[record]           = selected[185];
      assign create_pred[record]          = selected[108:106] == 3'd1 && selected[122];
      assign create_unknown[record]       = selected[186];
      assign create_chk[record*25+:25]    = selected[184:160];
    end
  endgenerate

endmodule
