// SPDX-License-Identifier: Apache-2.0
// RV32I word-stage adaptation of the corresponding C910 IFU stage duties.
// Generated by scripts/build_pipeline.py. See doc/pipeline_zh.md.
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
module rv32_ifu_ibctrl (
  input  wire         forever_cpuclk,
  input  wire         cpurst_b,
  input  wire         cancel,
  input  wire         fragment_valid,
  input  wire [  2:0] fragment_count,
  output wire         ib_ready,
  output wire         load,
  input  wire [767:0] raw_packet,
  input  wire [767:0] corrected_packet,
  input  wire [  3:0] correction,
  input  wire [127:0] corrected_pc,
  input  wire [ 87:0] retained_ghr,
  input  wire         recovery_stall,
  input  wire         ind_enable,
  input  wire         ind_result_vld,
  input  wire         ind_target_valid,
  input  wire [ 31:0] ind_target,
  input  wire         btb_update_ready,
  output wire         ind_query,
  output wire         saved_ind_valid,
  output wire [ 31:0] saved_ind_target,
  input  wire [  2:0] allowed_count,
  input  wire         ibuf_ready,
  output wire [  2:0] candidate_count,
  output wire [  2:0] consume_count,
  output wire         consume,
  output wire         redirect,
  output wire [ 31:0] redirect_pc,
  output wire [ 21:0] local_recover_ghr,
  output wire         ras_push,
  output wire         ras_pop,
  output wire         jump_accept,
  output wire         return_accept,
  output wire         ind_miss_event,
  output wire [ 31:0] push_pc,
  output wire [ 31:0] jump_target,
  output wire         train_valid,
  output wire         train_taken,
  output wire         train_ras,
  output wire         btb_used,
  output wire [ 31:0] train_pc,
  output wire [ 31:0] train_target,
  output wire [  2:0] train_type,
  output wire [  1:0] train_way,
  output wire [  7:0] ind_query_ghr,
  output wire         empty,
  output wire         pcfifo_wait,
  output wire         recovery_wait
);

  reg  [ 2:0] count_q;
  wire [ 2:0] count_nxt;
  wire        count_en;
  reg  [ 1:0] wait_q;
  wire [ 1:0] wait_nxt;
  wire        wait_en;
  reg  [33:0] indirect_q;
  wire [33:0] indirect_nxt;
  wire        indirect_en;
  wire [3:0] active, needs_recovery, is_jalr, accepted, selected_jump, selected_correction,
    selected_train, has_train;
  wire [1:0] jump_index, correction_index, train_index, query_index;
  wire [191:0] jump_packet, train_packet;
  wire query_needed, resolve_ready, done;
  genvar lane;
  assign empty = count_q == 0;
  generate
    for (lane = 0; lane < 4; lane = lane + 1) begin : g_lane
      assign active[lane] = lane < count_q;
      assign needs_recovery[lane] = active[lane] &&
        (raw_packet[lane*192+187] || raw_packet[lane*192+188] || raw_packet[lane*192+106+:3] == 3);
      assign is_jalr[lane] = active[lane] && raw_packet[lane*192+106+:3] == 3;
      assign has_train[lane] = active[lane] && raw_packet[lane*192+106+:3] != 0 &&
        raw_packet[lane*192+106+:3] < 4;
      assign accepted[lane] = consume && lane < consume_count;
      assign selected_jump[lane] = accepted[lane] &&
        (corrected_packet[lane*192+106+:3] == 2 || corrected_packet[lane*192+106+:3] == 3);
      assign selected_correction[lane] = accepted[lane] && correction[lane];
      assign selected_train[lane] = accepted[lane] && has_train[lane];
    end
  endgenerate
  assign recovery_wait = recovery_stall && (|needs_recovery);
  assign query_needed  = ind_enable && (|is_jalr) && !indirect_q[33];
  assign ind_query     = query_needed && !cancel && !recovery_wait;
  assign wait_en       = cancel || load || ind_query;
  assign wait_nxt      = (cancel || load) ? 2'b0 : wait_q == 2 ? 2'd2 : wait_q + 2'd1;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_wait
    if (!cpurst_b) wait_q <= 2'b0;
    else if (wait_en) wait_q <= wait_nxt;
  end
  assign indirect_en  = cancel || load || (ind_query && wait_q == 2 && ind_result_vld);
  assign indirect_nxt = (cancel || load) ? 34'b0 : {1'b1, ind_target_valid, ind_target};
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_indirect
    if (!cpurst_b) indirect_q <= 34'b0;
    else if (indirect_en) indirect_q <= indirect_nxt;
  end
  assign saved_ind_valid = indirect_q[33] && indirect_q[32];
  assign saved_ind_target = indirect_q[31:0];
  assign resolve_ready = !cancel && !recovery_wait && !query_needed &&
    (!(|has_train) || btb_update_ready);
  assign candidate_count = resolve_ready ? count_q : 3'd0;
  assign consume = resolve_ready && ibuf_ready && (allowed_count != 0);
  assign consume_count = consume ? allowed_count : 3'd0;
  assign done = consume && consume_count == count_q;
  assign ib_ready = !cancel && (empty || (done && !redirect));
  assign load = fragment_valid && ib_ready;
  assign count_en = cancel || load || consume;
  assign count_nxt = cancel ? 3'd0 : load ? fragment_count : count_q - consume_count;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_count
    if (!cpurst_b) count_q <= 3'b0;
    else if (count_en) count_q <= count_nxt;
  end
  assign redirect = |selected_correction;
  assign correction_index = {
    selected_correction[2] || selected_correction[3],
    selected_correction[1] || selected_correction[3]
  };
  assign redirect_pc = corrected_pc[{30'b0, correction_index}*32'd32+:32];
  assign local_recover_ghr = retained_ghr[{30'b0, correction_index}*32'd22+:22];
  assign jump_index = {selected_jump[2] || selected_jump[3], selected_jump[1] || selected_jump[3]};
  assign jump_packet = corrected_packet[{30'b0, jump_index}*32'd192+:192];
  assign jump_accept = |selected_jump;
  assign ind_miss_event = jump_accept && jump_packet[108:106] == 3 && !saved_ind_valid;
  assign ras_push = jump_accept && jump_packet[187];
  assign ras_pop = jump_accept && jump_packet[188];
  assign return_accept = ras_pop;
  assign push_pc = jump_packet[63:32] + 32'd4;
  assign jump_target = jump_packet[95:64];
  assign train_valid = |selected_train;
  assign train_index = {
    selected_train[2] || selected_train[3], selected_train[1] || selected_train[3]
  };
  assign train_packet = corrected_packet[{30'b0, train_index}*32'd192+:192];
  assign train_pc = train_packet[63:32];
  assign train_target = train_packet[159:128];
  assign train_type = train_packet[108:106];
  assign train_way = !train_packet[191] && train_packet[159:134] == train_packet[63:38] ?
    train_packet[124:123] : 2'b11;
  assign train_taken = train_packet[122];
  assign train_ras = train_packet[189];
  assign btb_used = train_valid && train_packet[190];
  assign query_index = {is_jalr[2] || is_jalr[3], is_jalr[1] || is_jalr[3]};
  assign ind_query_ghr = raw_packet[{30'b0, query_index}*32'd192+160+:8];
  assign pcfifo_wait = candidate_count != 0 && allowed_count < candidate_count;

endmodule
