// SPDX-License-Identifier: Apache-2.0
// RV32I adaptation of C910 support-stage duties. See doc/pipeline_zh.md.
// Generated by scripts/build_support.py. All PCs are physical byte addresses.
// Coding style : CCI500-style Verilog-2001 (see doc/coding_style_zh.md)
//------------------------------------------------------------------------------
// Module Declaration
//------------------------------------------------------------------------------
module rv32_ifu_vector (
  input  wire        forever_cpuclk,
  input  wire        cpurst_b,
  input  wire        init_done,
  input  wire [31:0] cp0_ifu_rvbr,
  output wire        vector_pcgen_reset_on,
  output wire        vector_pcgen_pcload,
  output wire [31:0] vector_pcgen_pc
);
  reg         captured_q;
  wire        captured_nxt;
  wire        captured_en;
  reg  [31:0] pc_q;
  wire [31:0] pc_nxt;
  wire        pc_en;
  reg         loaded_q;
  wire        loaded_nxt;
  wire        loaded_en;

  assign vector_pcgen_reset_on = !loaded_q;
  assign vector_pcgen_pcload   = init_done && !loaded_q;
  assign vector_pcgen_pc       = pc_q;
  assign captured_en           = !captured_q;
  assign captured_nxt          = 1'b1;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_captured
    if (!cpurst_b) captured_q <= 1'b0;
    else if (captured_en) captured_q <= captured_nxt;
  end
  assign pc_en  = !captured_q;
  assign pc_nxt = cp0_ifu_rvbr;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_pc
    if (!cpurst_b) pc_q <= 32'b0;
    else if (pc_en) pc_q <= pc_nxt;
  end
  assign loaded_en  = vector_pcgen_pcload;
  assign loaded_nxt = 1'b1;
  always @(posedge forever_cpuclk or negedge cpurst_b) begin : p_loaded
    if (!cpurst_b) loaded_q <= 1'b0;
    else if (loaded_en) loaded_q <= loaded_nxt;
  end

endmodule
